### ISSUE TITLE
UnicodeDecodeError on WinVault with umlaut in password

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#101]
Originally reported [on the mailing list](https://groups.google.com/d/topic/python-keyring/Y4AsTotxuME/discussion), the user reported issues if the password contains an umlaut.

More details can be found in [this bug report](http://bz.selenic.com/show_bug.cgi?id=3696).

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/101
- Originally reported by: Jason R. Coombs
- Originally created at: 2013-06-08T00:18:46.058

**Comment by jaraco** [comment]
I'm surprised that this error was reported, as the tests are pretty serious about exercising Unicode support. For example, see [test_backend](/kang/python-keyring-lib/src/c1018b992cb504ad86f870b00a8496e1f955a242/keyring/tests/test_backend.py?at=default). That test is the base class for all the backends, so every backend tests getting and setting a password where the 'system', 'username', and 'password' are all unicode characters (including russian, hebrew, and others).

Perhaps the umlaut fails because it's being passed in another encoding (latin-1, for example).

We should try putting together a test case that reproduces the issue. It's possible it's been solved.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
I just got another report: https://bitbucket.org/Mekk/mercurial_keyring/issue/33/unicodedecodeerror-when-entering-password

---

Original comment by: Marcin Kasperski

**Comment by jaraco** [comment]
Here is the traceback as reported in the upstream library.

```
** Mercurial version (2.8.1).  TortoiseHg version (2.10.1)
** Command: 
** CWD: Z:\ituvs\jusurb
** Encoding: cp1257
** Extensions loaded: purge, mercurial_keyring
** Python version: 2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)]
** Windows version: sys.getwindowsversion(major=6, minor=2, build=9200, platform=2, service_pack='')
** Processor architecture: x64
** Qt-4.8.4 PyQt-4.10.2 QScintilla-2.7.2
Traceback (most recent call last):
  File "tortoisehg\hgqt\thread.pyo", line 269, in run
  File "tortoisehg\util\hglib.pyo", line 708, in dispatch
  File "mercurial\dispatch.pyo", line 806, in _dispatch
  File "mercurial\dispatch.pyo", line 585, in runcommand
  File "mercurial\dispatch.pyo", line 897, in _runcommand
  File "mercurial\dispatch.pyo", line 868, in checkargs
  File "mercurial\dispatch.pyo", line 803, in <lambda>
  File "mercurial\util.pyo", line 512, in check
  File "mercurial\commands.pyo", line 4590, in pull
  File "mercurial\hg.pyo", line 122, in peer
  File "mercurial\hg.pyo", line 102, in _peerorrepo
  File "mercurial\httppeer.pyo", line 238, in instance
  File "mercurial\httppeer.pyo", line 57, in _fetchcaps
  File "mercurial\httppeer.pyo", line 171, in _call
  File "mercurial\httppeer.pyo", line 118, in _callstream
  File "urllib2.pyo", line 406, in open
  File "urllib2.pyo", line 519, in http_response
  File "urllib2.pyo", line 438, in error
  File "urllib2.pyo", line 378, in _call_chain
  File "urllib2.pyo", line 890, in http_error_401
  File "mercurial\url.pyo", line 436, in http_error_auth_reqed
  File "hgext\mercurial_keyring.pyo", line 389, in basic_http_error_auth_reqed
  File "urllib2.pyo", line 865, in http_error_auth_reqed
  File "urllib2.pyo", line 878, in retry_http_basic_auth
  File "urllib2.pyo", line 406, in open
  File "urllib2.pyo", line 519, in http_response
  File "urllib2.pyo", line 438, in error
  File "urllib2.pyo", line 378, in _call_chain
  File "urllib2.pyo", line 890, in http_error_401
  File "mercurial\url.pyo", line 436, in http_error_auth_reqed
  File "hgext\mercurial_keyring.pyo", line 389, in basic_http_error_auth_reqed
  File "urllib2.pyo", line 865, in http_error_auth_reqed
  File "urllib2.pyo", line 878, in retry_http_basic_auth
  File "urllib2.pyo", line 406, in open
  File "urllib2.pyo", line 519, in http_response
  File "urllib2.pyo", line 438, in error
  File "urllib2.pyo", line 378, in _call_chain
  File "urllib2.pyo", line 890, in http_error_401
  File "mercurial\url.pyo", line 436, in http_error_auth_reqed
  File "hgext\mercurial_keyring.pyo", line 389, in basic_http_error_auth_reqed
  File "urllib2.pyo", line 865, in http_error_auth_reqed
  File "urllib2.pyo", line 871, in retry_http_basic_auth
  File "hgext\mercurial_keyring.pyo", line 383, in find_user_password
  File "hgext\mercurial_keyring.pyo", line 268, in find_auth
  File "hgext\mercurial_keyring.pyo", line 121, in set_http_password
  File "keyring\core.pyo", line 42, in set_password
  File "keyring\backends\Windows.pyo", line 146, in set_password
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 6: ordinal not in range(128)
```

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
After further investigation, I've determined that the error is caused by invalid usage--namely, passing byte strings to set_password, which is not supported. Passwords must be unicode.

---

Original comment by: Jason R. Coombs
