### ISSUE TITLE
Keyring backend detecting

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#118]
After upgrade from 1.6.1 to 3.0.5 keyring can't detect automatically kwallet backend in my KDE. Need manually add ~/.local/share/python_keyring/keyringrc.cfg with contents:

``` ini
[backend]
default-keyring = keyring.backends.kwallet.Keyring
```

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/118
- Originally reported by: Vladislav Polukhin
- Originally created at: 2013-10-05T12:59:24.022

**Comment by jaraco** [comment]
Hi Vladislav, thanks for the bug report. It sounds like in #119 you discovered the underlying issue with the backend (missing required KDE libraries). I'm not sure why the upgrade from 1.6 to 3.0 made a difference. I don't see anything in the changelog that seems relevant. Have you found yet why the KDE libraries might have changed?

For others to reference, if the expected preferred keyring is not being selected, one can always troubleshoot by invoking the backend directly. For example:

```
import keyring.backends.kwallet
print(keyring.backends.kwallet.Keyring.priority)
```

On my system, that yields:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".\keyring\util\properties.py", line 22, in __get__
    return self.fget.__get__(None, owner)()
  File ".\keyring\backends\kwallet.py", line 60, in priority
    raise RuntimeError("KDE libraries not available")
RuntimeError: KDE libraries not available
```

That error message indicates to me the reason why that backend isn't viable. If it does actually print a number, the number is the priority of that backend compared to others, so may be another indicator of why another backend might be preferred.

I'm going to close this ticket, but do please comment further if you have any unresolved issues.

---

Original comment by: Jason R. Coombs
