### ISSUE TITLE
NameError: global name 'KWallet' is not defined

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#119]
Using 3.0.5. My ~/.local/share/python_keyring/keyringrc.cfg:

``` ini
[backend]
default-keyring = keyring.backends.kwallet.Keyring
```

While try:

``` bash
$ LC_ALL=C hg in                                                                                                                                                                            
** Unknown exception encountered with possibly-broken third-party extension mercurial_keyring
** which supports versions unknown of Mercurial.
** Please disable mercurial_keyring and try your action again.
** If that fixes the bug please report it to the extension author.
** Python 2.7.5 (default, Sep  6 2013, 09:55:21) [GCC 4.8.1 20130725 (prerelease)]
** Mercurial Distributed SCM (version 2.7.2)
** Extensions loaded: graphlog, mq, convert, progress, rebase, record, transplant, purge, mercurial_keyring
```

Get:

``` python
Traceback (most recent call last):
  File "/usr/bin/hg", line 38, in <module>
    mercurial.dispatch.run()
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 28, in run
    sys.exit((dispatch(request(sys.argv[1:])) or 0) & 255)
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 69, in dispatch
    ret = _runcatch(req)
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 97, in _runcatch
    return _dispatch(req)
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 778, in _dispatch
    cmdpats, cmdoptions)
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 549, in runcommand
    ret = _runcommand(ui, options, cmd, d)
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 869, in _runcommand
    return checkargs()
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 840, in checkargs
    return cmdfunc()
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 775, in <lambda>
    d = lambda: util.checksignature(func)(ui, *args, **cmdoptions)
  File "/usr/lib/python2.7/site-packages/mercurial/util.py", line 507, in check
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mercurial/extensions.py", line 143, in wrap
    util.checksignature(origfn), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mercurial/util.py", line 507, in check
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/hgext/mq.py", line 3533, in mqcommand
    return orig(ui, repo, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mercurial/util.py", line 507, in check
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mercurial/commands.py", line 3872, in incoming
    return hg.incoming(ui, repo, source, opts)
  File "/usr/lib/python2.7/site-packages/mercurial/hg.py", line 548, in incoming
    return _incoming(display, subreporecurse, ui, repo, source, opts)
  File "/usr/lib/python2.7/site-packages/mercurial/hg.py", line 500, in _incoming
    other = peer(repo, opts, source)
  File "/usr/lib/python2.7/site-packages/mercurial/hg.py", line 122, in peer
    return _peerorrepo(rui, path, create).peer()
  File "/usr/lib/python2.7/site-packages/mercurial/hg.py", line 102, in _peerorrepo
    obj = _peerlookup(path).instance(ui, path, create)
  File "/usr/lib/python2.7/site-packages/mercurial/httppeer.py", line 238, in instance
    inst._fetchcaps()
  File "/usr/lib/python2.7/site-packages/mercurial/httppeer.py", line 57, in _fetchcaps
    self.caps = set(self._call('capabilities').split())
  File "/usr/lib/python2.7/site-packages/mercurial/httppeer.py", line 171, in _call
    fp = self._callstream(cmd, **args)
  File "/usr/lib/python2.7/site-packages/mercurial/httppeer.py", line 118, in _callstream
    resp = self.urlopener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 897, in http_error_401
    url, req, headers)
  File "/usr/lib/python2.7/site-packages/mercurial/url.py", line 431, in http_error_auth_reqed
    self, auth_header, host, req, headers)
  File "/usr/lib/python2.7/site-packages/mercurial_keyring.py", line 386, in basic_http_error_auth_reqed
    return basic_http_error_auth_reqed.orig(self, authreq, host, req, headers)
  File "/usr/lib/python2.7/urllib2.py", line 872, in http_error_auth_reqed
    response = self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib/python2.7/urllib2.py", line 878, in retry_http_basic_auth
    user, pw = self.passwd.find_user_password(realm, host)
  File "/usr/lib/python2.7/site-packages/mercurial_keyring.py", line 380, in find_user_password
    return self._pwd_handler.find_auth(self, realm, authuri, req)
  File "/usr/lib/python2.7/site-packages/mercurial_keyring.py", line 231, in find_auth
    pwd = password_store.get_http_password(keyring_url, user)
  File "/usr/lib/python2.7/site-packages/mercurial_keyring.py", line 114, in get_http_password
    self._format_http_key(url, username))
  File "/usr/lib/python2.7/site-packages/keyring/core.py", line 36, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python2.7/site-packages/keyring/backends/kwallet.py", line 68, in get_password
    network = KWallet.Wallet.NetworkWallet()
NameError: global name 'KWallet' is not defined
```

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/119
- Originally reported by: Vladislav Polukhin
- Originally created at: 2013-10-18T05:07:47.034

**Comment by jaraco** [comment]
Reading the code, I suspect the issue is that the latest code doesn't check the viability of a keyring specified explicitly in the config, but instead just tries to use it.

I've created #120 to track the need to give better error messages in the general case.

However, for your specific case, could you try something for me? In your Python environment:

```
import keyring
print(keyring._keyring_backend.priority)
```

I suspect that call will trigger a RuntimeError with a message "KDE libraries not available". To use KDE, the PyKDE4 and PyQt4 libraries must be present and importable.

Let me know what you find.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
``` python
In [1]: import keyring

In [2]: print(keyring._keyring_backend.priority)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-9679929176d6> in <module>()
----> 1 print(keyring._keyring_backend.priority)

AttributeError: 'module' object has no attribute '_keyring_backend'
```

---

Original comment by: Vladislav Polukhin

**Comment by jaraco** [comment]
Ugh. My mistake. I meant

`print(keyring.core._keyring_backend.priority)`

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
``` python
In [1]: import keyring

In [2]: print(keyring.core._keyring_backend.priority)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-68316a6eb7b3> in <module>()
----> 1 print(keyring.core._keyring_backend.priority)

/usr/lib/python2.7/site-packages/keyring/util/properties.pyc in __get__(self, cls, owner)
     18     """
     19     def __get__(self, cls, owner):
---> 20         return self.fget.__get__(None, owner)()
     21 
     22 # borrowed from jaraco.util.dictlib

/usr/lib/python2.7/site-packages/keyring/backends/kwallet.pyc in priority(cls)
     57             KWallet.__name__
     58         if exc:
---> 59             raise RuntimeError("KDE libraries not available")
     60         if 'KDE_SESSION_ID' not in os.environ:
     61             return 0

RuntimeError: KDE libraries not available
```

---

Original comment by: Vladislav Polukhin

**Comment by jaraco** [comment]
So that confirms my suspicion that you don't have the requisite libraries installed for KDE support. More information on installing the requisite libraries can be found in [their tech base](http://techbase.kde.org/Development/Languages/Python). Once you have the libraries installed, I suspect those errors will go away. Please report back if you find otherwise.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Big thanks! Please, replace `NameError` for more informative message.For example:

```
Please, install python KDE bindings
```

---

Original comment by: Vladislav Polukhin

**Comment by jaraco** [comment]
Indeed. That's what #120 is about.

---

Original comment by: Jason R. Coombs
