### ISSUE TITLE
How to install keyring using Python3

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#121]
I am not able to install keyring using Python3. Below are the error logs:
[rtnpro@rtnpro keyring-0.3-bak]$ python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    from extensions import get_extensions
  File "/home/rtnpro/rpmbuild/SOURCES/keyring-0.3-bak/extensions.py", line 9, in <module>
    import commands
ImportError: No module named 'commands'

It seems that support for `commands` has been removed from Python3. Is there any work around it. I need to re package keyring for Fedora and I need it for that.

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/121
- Originally reported by: Ratnadeep Debnath
- Originally created at: 2013-10-22T21:20:29.331

**Comment by jaraco** [comment]
You have a very old version of keyring there (0.3). The latest is 3.0. Please try again with the latest version - it should work just fine with Python 3.

---

Original comment by: Jason R. Coombs
