### ISSUE TITLE
DBUS Error when importing keyring library

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#127]
My backup (using backintime) fails lately. My investigation concluded that an error is thrown by the python keyring library. As I neither know python nor keyring I'm stuck. Any idea why root cannot import the keyring library?

The following command fails (for the superuser only!):

```
#!unknown

ppz@ubuntu1310:~[19:19]% sudo python -c "import keyring"
ERROR:dbus.proxies:Introspect error on :1.1:/org/freedesktop/secrets/aliases/default: dbus.exceptions.DBusException: org.freedesktop.Secret.Error.NoSuchObject: The '/org/freedesktop/secrets/aliases/default' object does not exist
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/keyring/__init__.py", line 9, in <module>
    from core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 166, in <module>
    init_backend()
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 65, in init_backend
    keyrings.sort(key = lambda x: -x.supported())
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 65, in <lambda>
    keyrings.sort(key = lambda x: -x.supported())
  File "/usr/lib/python2.7/dist-packages/keyring/backends/SecretService.py", line 23, in supported
    secretstorage.Collection(bus)
  File "/usr/lib/python2.7/dist-packages/secretstorage/collection.py", line 43, in __init__
    self.collection_props_iface.Get(COLLECTION_IFACE, 'Label')
  File "/usr/lib/python2.7/dist-packages/secretstorage/util.py", line 27, in function_out
    raise ItemNotFoundException(e.get_dbus_message())
secretstorage.exceptions.ItemNotFoundException: The '/org/freedesktop/secrets/aliases/default' object does not exist
```

However the same command works for any regular user:

```
#!unknown

ppz@ubuntu1310:~[19:19]% python -c "import keyring"
ppz@ubuntu1310:~[19:19]%
```

Environment Details of the affected host (where it fails for root):
- Ubuntu Desktop 13.10 "saucy" 64bit
- `python -c "import dbus;print dbus.__version__"` ===> 1.2.0
- `python --version` ===> Python 2.7.5+

Note that on other Ubuntu hosts this error cannot be reproduced:

```
#!unknown

ppz@ubuntu1204:~[19:19]% sudo python -c "import keyring"
ppz@ubuntu1204:~[19:19]%
```

Environment Details of Host 2 (where it works also for root):
- Ubuntu Desktop 12.04 LTS "precise" 64bit
- `python -c "import dbus;print dbus.__version__"` ===> 1.0.0
- `python --version` ===> Python 2.7.3

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/127
- Originally reported by: Anonymous
- Originally created at: 2013-11-20T20:19:19.740

**Comment by jaraco** [comment]
Sorry to say but it WORKS NOW!

I cannot reproduce the error. What happens now is that the command 
`python -c "import keyring"` takes 25 seconds (only for root, for a regular user it's fast) but it eventually works. Very strange. I have no idea what changed. There were some Ubuntu updates in between but maybe it's just my broken setup here. Version numbers of Ubuntu (13.10), Python (2.7.5+) and Dbus (1.2.0) have not changed. 

I'm sorry I didn't verify with a fresh installation. Please resolve/DELETE this bug.

---

Original comment by: [anonymous345](http://bitbucket.org/anonymous345)

**Comment by jaraco** [comment]
Glad it's working for you. I don't know about the stall, but I would be surprised if the delay was due to anything over which keyring has control. That said, if the problem continues, please try to replicate the issue on another system and if you find the same issue there, please open a ticket describing how to reproduce the stall.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
FIX:
As this happened again on the same host as originally reported I spent some more time searching for answers and I think I it is the [python keyring bug 1242412](https://bugs.launchpad.net/ubuntu/+source/python-keyring/+bug/1242412):

I was able to fix the issue on the affected host it with these comands:

```
#!shell

sudo apt-get install python-setuptools
sudo apt-get install python-pip
sudo easy_install keyring
sudo pip install keyring --upgrade
```

---

Original comment by: [anonymous345](http://bitbucket.org/anonymous345)

**Comment by jaraco** [comment]
Glad to hear it. Thanks for the follow up.

---

Original comment by: Jason R. Coombs
