### ISSUE TITLE
Windows config path missing

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#128]
As mentioned in the documentation, path to config files is platform specific, and can be determined by running the command...
python -c "import keyring.util.platform_; print(keyring.util.platform_.data_root())"
...
However, when I try running this command, I'm told about a path that doesn't exist. In my case, this is "C:\Users\tclarke\AppData\Local\Python Keyring" . Note that the path  "C:\Users\tclarke\AppData\Local\" does exist, it's just the "Python Keyring" folder that is missing.

I've also tried searching for keyringrc.cfg on the filesystem, no results returned.

For what it's worth I'm running Windows 7 64-bit, Python 2.7 32-bit, keyring 3.2.1 (installed through pip 1.4.1).

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/128
- Originally reported by: Tom Clarke
- Originally created at: 2013-11-29T22:41:16.105

**Comment by jaraco** [comment]
I also experience the same behavior, and the path doesn't exist on my system either. If you want to create a keyringrc.cfg, you can create that folder and then create the file in that folder.

Having a keyring config is not necessary to use keyring.

What is it you're expecting to happen that doesn't?

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Thanks for getting back to me Jason.

Good to know I can create the folder and keyringrc.cfg file manually. In terms of what I expected, I thought a template keyringrc.cfg file would be installed by default, and be held in the aforementioned directory. It's not a problem that it's not, especially if it's not a requirement.

The following questions now arise out of this:
- Q1: The default folder for Windows Credentials Vault (which, as far as I understand, will be in C:\Users\tclarke\AppData\Local\Microsoft\Credentials for me) appears to be blank, even after trying to use keyring. Whilst it's possible I'm using keyring wrong, should I expect to see contents in this folder when I'm using keyring correctly? If not, where else could I look to find the encrypted password files? They don't seem to be in the folder I've run the Python interpreter from, which is the other place I've checked.
- Q2: At the moment, I've used the following code successfully (in Python interpreter)...

```
#!python


import keyring
keyring.get_keyring()
keyring.set_password('newtest','user11','pass11')
keyring.get_password('newtest','user11')
#Returns u'pass11' as expected
exit()
#Reentering Python interpreter...
import keyring
keyring.get_keyring()
keyring.get_password('newtest','user11')
#Returns u'pass11' as expected
```

Are there any other tweaks to the code above you would recommend?
- Q3: I used the Credential Manager tool built into Windows Control Panel (under User Accounts) to create a test entry. I tested to see if I could access this vault entry using keyring, but was not successful. It's not a dealbreaker for me, but just wanted to check this was expected behaviour. Also worth noting I couldn't see the entries I'd created using keychain in the Credential Manager tool. Are the entries kept separate? 

Thanks.

---

Original comment by: Tom Clarke

**Comment by jaraco** [comment]
Regarding Q1: I didn't realize the credentials were stored in the file system, but now that I look on my system, you're right. They're stored there, but they're hidden. I was able to reveal them this way:

```
> cmd /c dir /a C:\Users\jaraco\AppData\local\Microsoft\Credentials
```

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Regarding Q2: That's exactly the usage I use. One other thing you can do to confirm which backend you're using is:

```
>>> keyring.core._keyring_backend
<keyring.backends.Windows.WinVaultKeyring object at 0x0000000003A82E80>
```

That will at least confirm that you're using the WinVaultKeyring (which uses the Credential Vault).

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Regarding Q3, you're real close. You should be able to see the passwords you create in keyring, create new ones, and delete unwanted ones from the Credential Manager.

I suspect the issue is that you haven't selected the "Windows Credentials" in the "Generic Credentials" section, which is where keyring stores the passwords. I regularly use the Credential Manager for managing my passwords, so I suspect you'll find them there.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Thanks Jason, using your advice found out what's going on, looks like keyring.get_keyring() is returning a keyring.backends.Windows.RegistryKeyring object. How would I explicity state that I wished to use WinVaultKeyring? Tried the following, but got errors...

```
#!python

>>> from keyring.backends.Windows import WinVaultKeyring
>>> WinVaultKeyring()
<keyring.backends.Windows.WinVaultKeyring object at 0x01F60C70>
>>> WinVaultKeyring.set_password('newtest2','user111','pass111')
TypeError: unbound method set_password() must be called with WinVaultKeyring instance as first argument (got str instance instead)
>>> keyr = WinVaultKeyring()
>>> type(keyr)
<class 'keyring.backends.Windows.WinVaultKeyring'>
```

Seems like I haven't worked out how to create a WinVaultKeyring object properly. What would you advise?

Thanks again Jason.
Tom

---

Original comment by: Tom Clarke

**Comment by jaraco** [comment]
The fact that it's selecting RegistryKeyring suggests to me that WinVaultKeyring isn't viable in your environment. Now to figure out why.

In your example, you're on the right track, but when you called set_password, you did that on the class itself and not an instance of the class. Then, you created the instance. Just use that instance to try to set a password:

```
>>> keyr.set_password('newtest2', 'user111', 'pass111')
```

You'll probably get an error that will shine some light on the issue.

Also, do this please:

```
>>> from keyring.backends.Windows import WinVaultKeyring, RegistryKeyring
>>> WinVaultKeyring.priority
5
>>> RegistryKeyring.priority
2
```

As you can see, on my system, I get numeric priorities with WinVaultKeyring being higher. I suspect on your system, you'll get an error trying to get the priority of WinVaultKeyring. If that error is different than the one you get when you try set_password, please report that also.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Hi Jason,

As requested...

```
#!python

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\tclarke>python
Python 2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> from keyring.backends.Windows import WinVaultKeyring
>>> keyr = WinVaultKeyring()
>>> keyr.set_password('newtest2', 'user111', 'pass111')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\keyring\backends\Windows.py", line 138, in
 set_password
    existing_pw = self._get_password(service)
  File "C:\Python27\lib\site-packages\keyring\backends\Windows.py", line 130, in
 _get_password
    except pywintypes.error:
NameError: global name 'pywintypes' is not defined
>>>
```

and ...

```
#!python

C:\Users\tclarke>python
Python 2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> from keyring.backends.Windows import WinVaultKeyring, RegistryKeyring
>>> WinVaultKeyring.priority
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\keyring\util\properties.py", line 22, in _
_get__
    return self.fget.__get__(None, owner)()
  File "C:\Python27\lib\site-packages\keyring\backends\Windows.py", line 106, in
 priority
    raise RuntimeError("Requires Windows and pywin32")
RuntimeError: Requires Windows and pywin32
>>> RegistryKeyring.priority
2
>>>
```

What do these errors tell you? From my less knowledgable vantage point, looks like pywin32 is a requirement, is that correct?

---

Original comment by: Tom Clarke

**Comment by jaraco** [comment]
Indeed, that's the case, at least according to the code. I always install pywin32 as a standard step in my Python installation, so I had forgotten about that requirement. I should add that to the README docs, and maybe even file a ticket about removing that dependency.

Please try with pywin32 - I think that'll fix your issue.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
I created #130 and #131 to address the follow-on issues I identified.

---

Original comment by: Jason R. Coombs
