### ISSUE TITLE
Error with py2exe

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#129]
```
Traceback (most recent call last):
  File "APP.py", line 10, in <module>  (import keyring)
  File "keyring\__init__.pyc", line 12, in <module>
  File "keyring\core.pyc", line 15, in <module>
  File "keyring\util\platform_.pyc", line 4, in <module>
  File "keyring\util\platform.pyc", line 29, in <module>
AttributeError: 'module' object has no attribute 'system'
```

As [reported in StackOverflow](http://stackoverflow.com/questions/19852259/keyring-module-is-not-included-while-packaging-with-py2exe)

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/129
- Originally reported by: Hárísh Bárvékár
- Originally created at: 2013-11-30T19:19:54.225

**Comment by jaraco** [comment]
As reported, this bug is invalid. It's clear from the traceback that you have two versions of keyring installed (or at least remnants). In Keyring 3.0.2, the keyring.util.platform module was renamed to keyring.util.platform_ in order to address another project's usage of the library. I would first make sure you have a clean environment and not remnants of an older keyring lib.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
I posted [an answer](http://stackoverflow.com/a/20330319/70170) to the StackOverflow question.

---

Original comment by: Jason R. Coombs
