### ISSUE TITLE
OSX install broken when using virtualenvs?

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#13]
This lib seemed way interesting and got a bit of publicity a few weeks ago, so I decided to check it out the usual way: create a virtualenv, pip install the library inside it and play around.

Except I didn't get anywhere: `get_password` would always return `None` (with no keychain prompt) and `set_password` would throw `OSError: Can't store password in Keychain`, in both cases whatever the service & account are. After a few reinstallations, I tried compiling from scratch (cloning from mercurial and `python setup.py build`… success. Both tip (4a551eda6bf8) and tag 0.2 build and work perfectly.

Try to `python setup.py install` it in my virtualenv, failure again (except it now throws `keyring.backend.PasswordSetError` on `set_password`, due to being tip I guess).

Tested the same scenario in a fresh OpenSUSE image, no issue.

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/13
- Originally reported by: [masklinn](http://bitbucket.org/masklinn)
- Originally created at: 2009-12-30T17:10:27.189

**Comment by jaraco** [comment]
With some testing against tip, even a source build (`python setup.py build build_ext install`) no longer works.

---

Original comment by: Chris Adams

**Comment by jaraco** [comment]
Masklinn or someone with OS X: is this issue still valid with current trunk?

Many things has changed on the OS X side (we no longer ship C extensions, we rely on ctypes instead). I'll be glad to help, but I don't have access to any OS X machine ATM.

---

Original comment by: Jonathan Ballet

**Comment by jaraco** [comment]
This behaviour is unchanged with 0.7 for any attempt to set a password:

{{{

> > > keyring.backends.osx_keychain.password_set("foo", "bar", "baaz")
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/cadams/.virtualenvs/wdl/lib/python2.7/site-packages/keyring/backends/osx_keychain.py", line 106, in password_set
> > >     raise OSError("Can't store password in keychain")
> > > OSError: Can't store password in keychain
> > > }}}

It's not clear that this is specific to a virtualenv - if I get more time I'll compare it against my code (https://github.com/acdha/pymacadmin/blob/master/lib/PyMacAdmin/Security/Keychain.py) — if nothing else it'd be nice to report the underlying API status value rather than squashing it down to a generic failure.

---

Original comment by: Chris Adams

**Comment by jaraco** [comment]
Same issue for me with 0.7.1 on Lion under a virtualenv.

The actual status error is:

(error -67061: "code or signature modified")

Which I believe means that the Python code doesn't have rights to the keychain.

---

Original comment by: Dan Sully

**Comment by jaraco** [comment]
Here's an alternative implementation which uses /usr/bin/security to avoid being tied quite so tightly to the underlying API restrictions:

https://gist.github.com/1782978

---

Original comment by: Chris Adams

**Comment by jaraco** [comment]
Hey Chris,

could you provide a patch or branch with this method so that potentially interested users can try it?
It should fit into the existing tests, ideally!

Thanks :)

---

Original comment by: Jonathan Ballet

**Comment by jaraco** [comment]
I am running into this as well, and I've attempted a fix based on Chris' post. It works for basic situations, and passes all but the "Difficult Chars" test. 

I'm stumped for how to get it to pass. Any suggestions? My fork is available at https://bitbucket.org/jakebasile/python-keyring-lib

---

Original comment by: Jake Basile

**Comment by jaraco** [comment]
What kind of errors do you have on those difficult chars?

---

Original comment by: Jonathan Ballet

**Comment by jaraco** [comment]
And of course I forget to attach the errors. 

# {{{

## FAIL: test_difficult_chars (**main**.OSXKeychainTestCase)

Traceback (most recent call last):
  File "keyring/tests/test_backend.py", line 182, in test_difficult_chars
    self.check_set_get(service, username, password)
  File "keyring/tests/test_backend.py", line 166, in check_set_get
    self.assertEqual(keyring.get_password(service, username), password)
AssertionError: '' != "-\r@\t<_$`_; =-#>['/?\x0c"

---

Ran 31 tests in 1.033s
}}}

It's not storing or retrieving the fancy characters correctly. I tried surrounding the argument with quotes, but python is apparently already doing that, because then I'll get "'password'" back. 

I've tried escaping the usernames/passwords/realms with the following function, but it still fails that test.

{{{
def escape_chars(s):
    print s
    s = s.replace('|', '|')
    s = s.replace('&', '&')
    s = s.replace(';', '\;')
    s = s.replace('<', '<')
    s = s.replace('>', '>')
    s = s.replace('(', '(')
    s = s.replace(')', ')')
    s = s.replace('$', '\$')
    s = s.replace('`', '\`')
    s = s.replace('\', '\\')
    s = s.replace('"', '\"')
    s = s.replace('\'', '\\'')
    s = s.replace(' ', '\ ')
    s = s.replace('\t', '\\t')
    s = s.replace('\n', '\\n')
    return s
}}}

---

Original comment by: Jake Basile

**Comment by jaraco** [comment]
Actually, I think there's no need to escape anything, since you don't execute the subprocess through a shell. I don't see any mention about possibly 'wrong' characters in the manual at https://developer.apple.com/library/mac/#documentation/Darwin/Reference/Manpages/man1/security.1.html, what happens if you execute this command yourself in a terminal with one of those character?

---

Original comment by: Jonathan Ballet

**Comment by jaraco** [comment]
Also, be careful, {{{subprocess.check_output()}}} is from Python 2.7+ and I think we still support Python 2.6 (right @jaraco?)

---

Original comment by: Jonathan Ballet

**Comment by jaraco** [comment]
I fixed the failing test.

The issue is that the security command formats odd characters in a way I wasn't expecting. If and when it encounters certain chars, it also outputs the entire password as a hex encoded string as well. I was able to look for the hex string, and if it's there decode and return it instead of the oddly formed password string.

Do I need to port this back to 2.6?

---

Original comment by: Jake Basile

**Comment by jaraco** [comment]
I went ahead and ported it back. I think it completely works now, and I submitted a pull request for it: https://bitbucket.org/kang/python-keyring-lib/pull-request/11/fixed-get-set-in-os-x-under-virtualenv

---

Original comment by: Jake Basile

**Comment by jaraco** [comment]
We support Python 2.4+, including Python 3, at least according to the trove classifiers and my best understanding.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Wow, Python 2.4+ oO ...  OK, anyway, without subprocess.check_output(), it should be compatible now.

I don't have an OS X machine to test this fix though, I would like at least one other person which is affected by #13 to try Jake's branch and report here if:
- it indeed fixes the problem of #13 ;
- all the tests still pass ;

If so, I don't see any reason not to merge his work.

Thanks Jake! 

---

Original comment by: Jonathan Ballet

**Comment by jaraco** [comment]
I've gone ahead and accepted the pull request. All tests still pass from the Windows side. I'll be releasing 0.8 soon with this fix.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Issue #145 reveals a security vulnerability exposed by this patch.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Here's an example where Java developers ran into the same situation:

http://lists.apple.com/archives/apple-cdsa/2010/May/msg00014.html

I wonder if this is a bug with virtualenv where it doesn't copy the signature for the Python binary, essentially creating an untrusted copy of the Python executable in the virtualenv.

---

Original comment by: Jason R. Coombs
