### ISSUE TITLE
on import: secretstorage.exceptions.ItemNotFoundException: The '/org/freedesktop/secrets/aliases/default' object does not exist

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#133]
When importing keyring with `python -c "import keyring"` I get this:

```
#!python

ERROR:dbus.proxies:Introspect error on :1.128:/org/freedesktop/secrets/aliases/default: dbus.exceptions.DBusException: org.freedesktop.Secret.Error.NoSuchObject: The '/org/freedesktop/secrets/aliases/default' object does not exist
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/secretstorage/util.py", line 23, in function_out
    return function_in(*args, **kwargs)
  File "/usr/lib/python3.3/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.3/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.3/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.Secret.Error.NoSuchObject: The '/org/freedesktop/secrets/aliases/default' object does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.3/site-packages/keyring/__init__.py", line 12, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/lib/python3.3/site-packages/keyring/core.py", line 180, in <module>
    init_backend()
  File "/usr/lib/python3.3/site-packages/keyring/core.py", line 59, in init_backend
    set_keyring(load_config() or _get_best_keyring())
  File "/usr/lib/python3.3/site-packages/keyring/core.py", line 67, in _get_best_keyring
    keyrings = backend.get_all_keyring()
  File "/usr/lib/python3.3/site-packages/keyring/util/__init__.py", line 24, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/lib/python3.3/site-packages/keyring/backend.py", line 127, in get_all_keyring
    exceptions=TypeError))
  File "/usr/lib/python3.3/site-packages/keyring/util/__init__.py", line 35, in suppress_exceptions
    for callable in callables:
  File "/usr/lib/python3.3/site-packages/keyring/backend.py", line 119, in is_class_viable
    keyring_cls.priority
  File "/usr/lib/python3.3/site-packages/keyring/util/properties.py", line 22, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/lib/python3.3/site-packages/keyring/backends/SecretService.py", line 27, in priority
    secretstorage.Collection(bus)
  File "/usr/lib/python3.3/site-packages/secretstorage/collection.py", line 43, in __init__
    self.collection_props_iface.Get(COLLECTION_IFACE, 'Label')
  File "/usr/lib/python3.3/site-packages/secretstorage/util.py", line 28, in function_out
    raise ItemNotFoundException(e.get_dbus_message())
secretstorage.exceptions.ItemNotFoundException: The '/org/freedesktop/secrets/aliases/default' object does not exist
```

This is the same as https://bitbucket.org/kang/python-keyring-lib/issue/127/dbus-error-when-importing-keyring-library, but I don't seem to be able to reopen that issue and I didn't just want to comment on an "invalid" issue.

I'm on Arch Linux and also the maintainer of python-keyring there (Python 3 version).
Using keyring 3.3.

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/133
- Originally reported by: Johannes Dewender
- Originally created at: 2013-12-19T19:32:47.515

**Comment by jaraco** [comment]
I have pyton-secretstorage installed when this happens (it doesn't happen otherwise, working fine).

I also tested this with the current hg version of keyring.

Using
https://wiki.gnome.org/action/show/Apps/DFeet
I can see dbus seems to be working, but there is no `org.freedesktop.secrets`.

Like I said in that other ticket, when I run the tests `nosetests3` (Python 3) a dialog opens asking me to give a password for my keyring.

Is it possible that python-keyring depends on having a configured keyring when it is imported and python-secretstorage is installed?
That would explain why that problem "magically" goes away (when a keyring is configured).

EDIT:
In case it isn't clear. I alway click on abort when that dialog asks me to give a password for a new keyring.

---

Original comment by: Johannes Dewender

**Comment by jaraco** [comment]
Running the tests  also gives the error from this issue, by the way. Just not as a full stacktrace:

```
-------------------- >> begin captured logging << --------------------
dbus.proxies: ERROR: Introspect error on :1.158:/org/freedesktop/secrets/aliases/default: dbus.exceptions.DBusException: org.freedesktop.Secret.Error.NoSuchObject: The '/org/freedesktop/secrets/aliases/default' object does not exist
dbus.proxies: DEBUG: Executing introspect queue due to error
--------------------- >> end captured logging << ---------------------
```

---

Original comment by: Johannes Dewender

**Comment by jaraco** [comment]
I can setup a keyring to see if the problem goes away. That would make sure depending on a keyring being configured is the problem.

However, I don't currently don't know how I delete the keyring again and I'd rather not keep an additional keyring "somewhere I don't know".
Additionally: if I don't know how to delete the keyring, then I don't know how to reproduce the problem again.

---

Original comment by: Johannes Dewender

**Comment by jaraco** [comment]
Sorry for the late reply (holidays):

> ```
> File "/usr/lib/python3.3/site-packages/keyring/backends/SecretService.py", line 27, in priority
>   secretstorage.Collection(bus)
> ```

That line was removed in changeset b6257215041a (which became 3.2.1 release). This issue shouldn't happen in that version and newer.

---

Original comment by: Dmitry Shachnev

**Comment by jaraco** [comment]
I must have messed up while testing for that other packaging problem.

I can confirm that this issue arises with python-keyring 3.2, but not 3.3 (I never tried 3.2.1).

---

Original comment by: Johannes Dewender

**Comment by jaraco** [comment]
Closing then.

---

Original comment by: Dmitry Shachnev
