### ISSUE TITLE
ResourceNotFoundError

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#137]
I am testing a program on Travis CI and I get the following error when attempting to use. It is probably due to the fact that I don't have Gnome keyring installed?

```
#!python

keyring.set_password('myapp', 'username', value)
```

I am getting an error from PythonFS:

```
#!python

ERROR: test_bad_login (__main__.ApiConnectionTest)
Test bad user login credentials
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 208, in test_bad_login
    config.set('login-token', bad_token)
  File "/home/travis/build/travcunn/kissync-python/app/core/config.py", line 60, in set
    return keyring.set_password('myapp', 'username', value)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/keyring/core.py", line 45, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/keyring/backends/pyfs.py", line 199, in set_password
    if not self.config.has_section(service):
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/keyring/backends/pyfs.py", line 162, in config
    f = self._open()
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/keyring/backends/pyfs.py", line 137, in _open
    pyfs = fs.osfs.OSFS(url2_path)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/fs/osfs/__init__.py", line 128, in __init__
    raise ResourceNotFoundError(root_path,msg="Root directory does not exist: %(path)s")
ResourceNotFoundError: Root directory does not exist: /home/travis/.local/share/python_keyring
```

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/137
- Originally reported by: [travcunn](http://bitbucket.org/travcunn)
- Originally created at: 2014-02-04T07:25:43.327

**Comment by jaraco** [comment]
Yes, it seems that the PythonFS keyring is being selected as the optimal keyring in your environment. Depending on your purpose, you can provide a keyring config file to specify a keyring to use, or you can enable the environment such that a different keyring is auto-selected by the library.

It's not obvious to me, though, that there's not an issue with keyring here. Perhaps the PythonFS keyring should create the root directory for the keyring if it doesn't exist.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
I'm not sure what to do here.
