### ISSUE TITLE
set_password crashes on Windows

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#140]
Am I doing anything wrong?  This code works on Linux, but not Windows:

```
#!python

>>> keyring.set_password('Testing', 'Administrator', 'foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Programs\Python26\lib\site-packages\keyring\core.py", line 45, in set
_password
    _keyring_backend.set_password(service_name, username, password)
  File "C:\Programs\Python26\lib\site-packages\keyring\backends\Windows.py", lin
e 137, in set_password
    existing_pw = self._get_password(service)
  File "C:\Programs\Python26\lib\site-packages\keyring\backends\Windows.py", lin
e 131, in _get_password
    if e.winerror == 1168 and e.funcname == 'CredRead': # not found
AttributeError: 'error' object has no attribute 'winerror'
```

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/140
- Originally reported by: Gringo Suave
- Originally created at: 2014-03-18T20:52:50.623

**Comment by jaraco** [comment]
Btw, this is the latest from PyPi and run on Python 2.6 with pywin32 212 installed on Windows XP and 7.

---

Original comment by: Gringo Suave

**Comment by jaraco** [comment]
Made a pull request.

---

Original comment by: Gringo Suave

**Comment by jaraco** [comment]
If you upgrade pywin32 to the latest build, does that correct the issue? Should keyring be supporting older versions of pywin32?

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Add a compatibility layer for older versions of Pywin32. Fixes #140.

→ <<cset fee44bdc4740>>

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Thanks very much, I see it on pypi now, which simplifies things a lot for users of my script.  Unfortunately our product is tied to an old version of pywin32 for the time being.

I learned a few things from your code.  Here's an alternate take for your consideration that you may like also.  It is a bit lighter, although it complicates the line a bit:

```
#!python

if getattr(e, 'winerror', e[0]) and getattr(e, 'funcname', e[1]):
    return None  # not found

```

---

Original comment by: Gringo Suave

**Comment by jaraco** [comment]
@mixmastamyk I agree your suggestion is tighter, but it doesn't communicate to my successor or future self why that code is in place. The patch as applied, while substantially more complicated, also communicates the purpose for the code and can be readily removed when it is no longer needed.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
A comment could serve that purpose no?

Hey, I'm happy, thanks again and have a great day.  ;)

p.s. Just thought of another one, haha:

```
e.winerror, e.funcname = e[0], e[1]  # because ...
```

---

Original comment by: Gringo Suave
