### ISSUE TITLE
Check for Windows backend not necessary on OS X (and otherwise)

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#142]
Hi,
I added keyring as directory to my project, not via easy_install/pip, to make sure it is available on the target system. When I run it on OS X I get this:

```
w73mc-imac:Nagstamon hw5$ ./nagstamon.py 
Traceback (most recent call last):
  File "/Users/hw5/Desktop/Nagstamon/master/Nagstamon/Nagstamon/Config.py", line 39, in <module>
    import Nagstamon.keyring as keyring
  File "/Users/hw5/Desktop/Nagstamon/master/Nagstamon/Nagstamon/keyring/__init__.py", line 12, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/Users/hw5/Desktop/Nagstamon/master/Nagstamon/Nagstamon/keyring/core.py", line 180, in <module>
    init_backend()
  File "/Users/hw5/Desktop/Nagstamon/master/Nagstamon/Nagstamon/keyring/core.py", line 59, in init_backend
    set_keyring(load_config() or _get_best_keyring())
  File "/Users/hw5/Desktop/Nagstamon/master/Nagstamon/Nagstamon/keyring/core.py", line 67, in _get_best_keyring
    keyrings = backend.get_all_keyring()
  File "/Users/hw5/Desktop/Nagstamon/master/Nagstamon/Nagstamon/keyring/util/__init__.py", line 24, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/Users/hw5/Desktop/Nagstamon/master/Nagstamon/Nagstamon/keyring/backend.py", line 137, in get_all_keyring
    _load_backends()
  File "/Users/hw5/Desktop/Nagstamon/master/Nagstamon/Nagstamon/keyring/backend.py", line 129, in _load_backends
    list(map(_load_backend, backends))
  File "/Users/hw5/Desktop/Nagstamon/master/Nagstamon/Nagstamon/keyring/backend.py", line 114, in _load_backend
    mod = importlib.import_module('.'+name, package)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/hw5/Desktop/Nagstamon/master/Nagstamon/Nagstamon/keyring/backends/Windows.py", line 11, in <module>
    from . import _win_crypto
  File "/Users/hw5/Desktop/Nagstamon/master/Nagstamon/Nagstamon/keyring/backends/_win_crypto.py", line 4, in <module>
    from ctypes import windll, WinDLL, WINFUNCTYPE
ImportError: cannot import name windll
```

Apparently start fails because windll, WinDLL and WINFUNCTYPE cannot be imported via ctypes. They are not necessary on OS X anyways.
If I change _load_backends() from keyring/backends to:

``` python3
def _load_backends():
    "ensure that all keyring backends are loaded"
    backends = ('file', 'Gnome', 'Google', 'keyczar', 'kwallet', 'multi',
        'OS_X', 'pyfs', 'SecretService')
    list(map(_load_backend, backends))
```

omitting the 'Windows'-backend it runs. Couldn't here be a simple check which OS runs and use only the needed or possible backends? Windows itself would not need no Gnome and OS_X, for example.

Best regards and thanks for a great project
Henri

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/142
- Originally reported by: Anonymous
- Originally created at: 2014-04-07T16:08:26.726

**Comment by jaraco** [comment]
I suppose something like https://github.com/HenriWahl/Nagstamon/commit/3fbef9104f2ef44226127d60f6c60d50878c0bc0

```
#!python

def _load_backends():
    "ensure that all keyring backends are loaded that match OS"
    if platform.system() == "Linux":
        backends = ('file', 'Gnome', 'Google', 'keyczar', 'kwallet', 'multi',
                    'pyfs', 'SecretService')
    elif platform.system() == "Windows":
        backends = ('file', 'Gnome', 'Google', 'keyczar', 'kwallet', 'multi',
                    'pyfs', 'SecretService', 'Windows')
    if platform.system() == "Darwin":
        backends = ('file', 'Gnome', 'Google', 'keyczar', 'kwallet', 'multi',
                    'OS_X', 'pyfs', 'SecretService')
    else:
        backends = ('file', 'Gnome', 'Google', 'keyczar', 'kwallet', 'multi',
                    'OS_X', 'pyfs', 'SecretService', 'Windows')
    list(map(_load_backend, backends))
```

---

Original comment by: Henri Wahl

**Comment by jaraco** [comment]
yikes! Please no if/elif/if/else block. The backends are designed to only be loaded if they are suitable for a given platform. The Windows backend should protect from importing names that aren't available on all platforms.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
I believe the ImportError as reported is no longer an issue. Looking at the latest code, the import of _win_crypto is wrapped in a try/except block for ImportError. I suspect you're running an old version of keyring. Can you try again with 2.0 or later and confirm the issue is no longer present?

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
I use version 3.7 of keyring - the latest as far as I know. And there the described error appears. Which lines or part of keyring do you refer to?

---

Original comment by: Henri Wahl

**Comment by jaraco** [comment]
The error message does not appear if keyring was installed via easy_install - just if used as submodule in other code.

---

Original comment by: Henri Wahl

**Comment by jaraco** [comment]
Notice in your error trace this line:

```
File "/Users/hw5/Desktop/Nagstamon/master/Nagstamon/Nagstamon/keyring/backends/Windows.py", line 11, in <module>
    from . import _win_crypto
```

But if you look at line 11 of Windows.py, there's no such code. Furthermore, where you do find 'from . import _win_crypto' in Windows.py, it's wrapped by a try/except, so it should never raise an ImportError.

It sounds like you're confused as to how keyring is installed and you have an old version installed somewhere (namely in the path indicated in the traceback).

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
I now kicked out all keyring installed via easy_install and only have a local keyring_custom module in my applications path. Nothing changed.
Shouldn't the "import  _win_crypto" in line 11 in Windows.py also be wrapped by a try/except? Thus it could with all platforms because all non-Windows OS could then work further on.

---

Original comment by: Henri Wahl

**Comment by jaraco** [comment]
If your 'Windows.py' doesn't [look like this](https://bitbucket.org/kang/python-keyring-lib/src/ca492bc7444d7c79cc40d640458e9d3a3d52b788/keyring/backends/Windows.py?at=default), then you have an old version of keyring in your keyring_custom package.

> Shouldn't the "import _win_crypto" in line 11 in Windows.py also be wrapped by a try/except?

Yes, probably. I don't know why your copy of keyring doesn't match the latest version of keyring, but that's probably your issue.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
It looks indeed different. I got it from https://pypi.python.org/pypi/keyring. Would you advice another source for a stable version?

---

Original comment by: Henri Wahl

**Comment by jaraco** [comment]
Sorry, I must have mixed up something completely. Now I found the 3.7 version from pypi index and cannot reproduce how I got the version I used. Thanks for the patience.

---

Original comment by: Henri Wahl
