### ISSUE TITLE
Keyring 3.7 fails to import on Mac OS X 10.9.2: "AttributeError: 'module' object has no attribute 'OSXKeychain'"

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#143]
I recently upgraded my macbook pro from OS X 10.8 to 10.9.2.  I installed keyring using pip, but when attempting to run Python code which imports keyring, I get the fatal error:  "AttributeError: 'module' object has no attribute 'OSXKeychain'".  I'm using the build-in version of Python 2.7.5.

```
#!bash

$ sudo pip install keyring
Downloading/unpacking keyring
  Downloading keyring-3.7.zip (89kB): 89kB downloaded
  Running setup.py (path:/private/tmp/pip_build_root/keyring/setup.py) egg_info for package keyring

    warning: no previously-included files found matching '.hg/last-message.txt'
Installing collected packages: keyring
  Running setup.py install for keyring

    warning: no previously-included files found matching '.hg/last-message.txt'
    Installing keyring script to /usr/local/bin
Successfully installed keyring
Cleaning up...
$ python
Python 2.7.5 (default, Aug 25 2013, 00:04:04) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyring
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/keyring/__init__.py", line 12, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/Library/Python/2.7/site-packages/keyring/core.py", line 180, in <module>
    init_backend()
  File "/Library/Python/2.7/site-packages/keyring/core.py", line 59, in init_backend
    set_keyring(load_config() or _get_best_keyring())
  File "/Library/Python/2.7/site-packages/keyring/core.py", line 130, in load_config
    keyring = load_keyring(None, keyring_name)
  File "/Library/Python/2.7/site-packages/keyring/core.py", line 89, in load_keyring
    class_ = getattr(module, class_name)
AttributeError: 'module' object has no attribute 'OSXKeychain'
>>> 

```

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/143
- Originally reported by: [mrabbitt](http://bitbucket.org/mrabbitt)
- Originally created at: 2014-04-14T19:09:05.848

**Comment by jaraco** [comment]
Never mind; the error was caused my a configuration problem.  I had the following in `~/ .local/share/python_keyring/keyringrc.cfg`:

```
[backend]
default-keyring=keyring.backend.OSXKeychain
```

The keyring names must have changed since the older version of keyring I had installed previously.

---

Original comment by: [mrabbitt](http://bitbucket.org/mrabbitt)
