### ISSUE TITLE
SecretService: dbus_init() fails without main_loop=False on successive usage

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#146]
On XBMC Media center where python scripts are run as addons in their own threads in an embedded Python environment, the dbus_init() call in SecretService fails when the addon which has imported the keyring is exited and re-opened. 

Below is the Traceback:

```
#!python

Traceback (most recent call last):
  File "/home/ruuk/.xbmc/addons/script.module.password.storage/lib/passwordStorage.py", line 36, in <module>
    import keyring
  File "/home/ruuk/.xbmc/addons/script.module.password.storage/lib/keyring/__init__.py", line 12, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/home/ruuk/.xbmc/addons/script.module.password.storage/lib/keyring/core.py", line 182, in <module>
    init_backend()
  File "/home/ruuk/.xbmc/addons/script.module.password.storage/lib/keyring/core.py", line 59, in init_backend
    set_keyring(load_config() or _get_best_keyring())
  File "/home/ruuk/.xbmc/addons/script.module.password.storage/lib/keyring/core.py", line 67, in _get_best_keyring
    keyrings = backend.get_all_keyring()
  File "/home/ruuk/.xbmc/addons/script.module.password.storage/lib/keyring/util/__init__.py", line 24, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/home/ruuk/.xbmc/addons/script.module.password.storage/lib/keyring/backend.py", line 149, in get_all_keyring
    exceptions=TypeError))
  File "/home/ruuk/.xbmc/addons/script.module.password.storage/lib/keyring/util/__init__.py", line 35, in suppress_exceptions
    for callable in callables:
  File "/home/ruuk/.xbmc/addons/script.module.password.storage/lib/keyring/backend.py", line 141, in is_class_viable
    keyring_cls.priority
  File "/home/ruuk/.xbmc/addons/script.module.password.storage/lib/keyring/util/properties.py", line 22, in __get__
    return self.fget.__get__(None, owner)()
  File "/home/ruuk/.xbmc/addons/script.module.password.storage/lib/keyring/util/XDG.py", line 18, in wrapper
    return func(*args, **kwargs) * self.multiplier
  File "/home/ruuk/.xbmc/addons/script.module.password.storage/lib/keyring/backends/SecretService.py", line 31, in priority
    bus = secretstorage.dbus_init()
  File "/usr/lib/python2.7/dist-packages/secretstorage/__init__.py", line 41, in dbus_init
    DBusGMainLoop(set_as_default=True)
TypeError: 'NoneType' object is not callable
```

Calling dbus_init() with main_loop=False fixes this, but of course prevents unlocking the keyring if necessary.

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/146
- Originally reported by: Rick Phillips
- Originally created at: 2014-04-30T20:18:50.356

**Comment by jaraco** [comment]
I've seen this behavior (global variables replaced with None) whenever a module is partially garbage collected. I suspect there's something about the way the plugin architecture works that is causing the secretstorage module to get garbage collected. Or it may just be that calling dbus_init() multiple times is not allowed.

Interesting that 'main_loop=False' corrects the issue. That leads me to believe there may be a way that keyring can expose a way for your plugin to pass that parameter.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
@jaraco:

> Interesting that 'main_loop=False' corrects the issue.

As already discussed, that happens because `DBusGMainLoop` gets replaced with None. When `main_loop=False`, SecretStorage doesn't try to create an instance of `DBusGMainLoop`.

---

Original comment by: Dmitry Shachnev

**Comment by jaraco** [comment]
The relevant effect of what @mitya57 alluded to is that while this fixes the original error, it causes errors if the keyring needs to be unlocked.

Interestingly, if I replace 
`bus = dbus_init()` with the following code:

```
#!python
def getDBusSessionBus():
    mainloop = dbus.get_default_main_loop()
    if not mainloop:
        mainloop = dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
    return dbus.SessionBus()


bus = getDBusSessionBus()

```

The keyring can be unlocked once, but if it becomes locked again, trying to unlock it causes an error.

---

Original comment by: Rick Phillips

**Comment by jaraco** [comment]
I have just pushed a [SecretStorage commit](https://github.com/mitya57/secretstorage/commit/af526089f47fa8b243e605ab09303195a7eab8c7) that should make things better for you. Please test if it helps, if yes, I will release the new version.

---

Original comment by: Dmitry Shachnev

**Comment by jaraco** [comment]
Assuming this is fixed. If there's more that keyring can do, re-open or open a new ticket.
