### ISSUE TITLE
keyring can't be used in conjunction with pynotify

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#152]
Log:

```
[me@pc ~]$ python -c "import pynotify; import keyring"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/keyring/__init__.py", line 12, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/local/lib/python2.7/dist-packages/keyring/core.py", line 158, in <module>
    init_backend()
  File "/usr/local/lib/python2.7/dist-packages/keyring/core.py", line 58, in init_backend
    set_keyring(load_config() or _get_best_keyring())
  File "/usr/local/lib/python2.7/dist-packages/keyring/core.py", line 66, in _get_best_keyring
    keyrings = backend.get_all_keyring()
  File "/usr/local/lib/python2.7/dist-packages/keyring/util/__init__.py", line 24, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keyring/backend.py", line 137, in get_all_keyring
    _load_backends()
  File "/usr/local/lib/python2.7/dist-packages/keyring/backend.py", line 129, in _load_backends
    list(map(_load_backend, backends))
  File "/usr/local/lib/python2.7/dist-packages/keyring/backend.py", line 114, in _load_backend
    mod = importlib.import_module('.'+name, package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/keyring/backends/Gnome.py", line 3, in <module>
    from gi.repository import GObject
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 39, in <module>
    raise ImportError(_static_binding_error)
ImportError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
```

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/152
- Originally reported by: [GijsTimmers](http://bitbucket.org/GijsTimmers)
- Originally created at: 2014-12-03T15:04:29.225

**Comment by jaraco** [comment]
When changing the import order, I'm getting a different error message:

```
[me@pc ~]$ python -c "import keyring; import pynotify"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/gtk-2.0/pynotify/__init__.py", line 1, in <module>
    from _pynotify import *
ImportError: could not import gobject (could not find _PyGObject_API object)
```

---

Original comment by: [GijsTimmers](http://bitbucket.org/GijsTimmers)

**Comment by jaraco** [comment]
Version information:

```
[me@pc ~]$ pip show keyring
---
Name: keyring
Version: 4.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```

---

Original comment by: [GijsTimmers](http://bitbucket.org/GijsTimmers)

**Comment by jaraco** [comment]
Right, you should never use pynotify (which is deprecated for 7 (!) years now).

Use [notify2](https://pypi.python.org/pypi/notify2) instead (the easiest way), or [libnotify](https://developer.gnome.org/libnotify/) via [PyGObject](https://wiki.gnome.org/Projects/PyGObject) (if you don’t want extra dependencies).

---

Original comment by: Dmitry Shachnev

**Comment by jaraco** [comment]
I didn't know that. Thank you, everything works now.

---

Original comment by: [GijsTimmers](http://bitbucket.org/GijsTimmers)
