### ISSUE TITLE
keyring didn't function properly after compiling with PyInstaller. I found a workaround.

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#153]
`kotnetcli.py` contains `import keyring` in one of the first lines of the file.

After that, files compiled with PyInstaller don't run properly anymore. 

Log:

```
[me@pc build]$ ./pyinstaller/pyinstaller.py -v
2.1.1dev-fc060ca-mod
```

```
[me@pc build]$ ./pyinstaller/pyinstaller.py kotnetcli.py 
26 INFO: wrote /home/me/Scripts/kotnetcli/build/kotnetcli.spec
55 INFO: UPX is not available.
85 INFO: Processing hook hook-os
212 INFO: Processing hook hook-time
215 INFO: Processing hook hook-cPickle
312 INFO: Processing hook hook-_sre
458 INFO: Processing hook hook-cStringIO
565 INFO: Processing hook hook-encodings
580 INFO: Processing hook hook-codecs
1115 INFO: Extending PYTHONPATH with /home/me/Scripts/kotnetcli/build
1115 INFO: checking Analysis
1115 INFO: building Analysis because out00-Analysis.toc non existent
1115 INFO: running Analysis out00-Analysis.toc
1171 INFO: Analyzing /home/me/Scripts/kotnetcli/build/pyinstaller/PyInstaller/loader/_pyi_bootstrap.py
1187 INFO: Processing hook hook-os
1213 INFO: Processing hook hook-site
1229 INFO: Processing hook hook-encodings
1341 INFO: Processing hook hook-time
1343 INFO: Processing hook hook-cPickle
1444 INFO: Processing hook hook-_sre
1594 INFO: Processing hook hook-cStringIO
1717 INFO: Processing hook hook-codecs
2360 INFO: Processing hook hook-pydoc
2517 INFO: Processing hook hook-email
2589 INFO: Processing hook hook-httplib
2637 INFO: Processing hook hook-email.message
2715 INFO: Analyzing /home/me/Scripts/kotnetcli/build/pyinstaller/PyInstaller/loader/pyi_importers.py
2768 INFO: Analyzing /home/me/Scripts/kotnetcli/build/pyinstaller/PyInstaller/loader/pyi_archive.py
2822 INFO: Analyzing /home/me/Scripts/kotnetcli/build/pyinstaller/PyInstaller/loader/pyi_carchive.py
2876 INFO: Analyzing /home/me/Scripts/kotnetcli/build/pyinstaller/PyInstaller/loader/pyi_os_path.py
2882 INFO: Analyzing kotnetcli.py
3296 INFO: Processing hook hook-sqlite3
3518 INFO: Processing hook hook-xml
3635 INFO: Processing hook hook-xml.sax
3676 INFO: Processing hook hook-pyexpat
3782 INFO: Hidden import 'codecs' has been found otherwise
3782 INFO: Hidden import 'encodings' has been found otherwise
3782 INFO: Looking for run-time hooks
objdump: section '.dynamic' mentioned in a -j option, but not found in any input file
4363 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
4364 INFO: Adding Python library to binary dependencies
5168 INFO: Warnings written to /home/me/Scripts/kotnetcli/build/build/kotnetcli/warnkotnetcli.txt
5193 INFO: checking PYZ
5194 INFO: rebuilding out00-PYZ.toc because out00-PYZ.pyz is missing
5194 INFO: building PYZ (ZlibArchive) out00-PYZ.toc
6450 INFO: checking PKG
6451 INFO: rebuilding out00-PKG.toc because out00-PKG.pkg is missing
6451 INFO: building PKG (CArchive) out00-PKG.pkg
objdump: section '.dynamic' mentioned in a -j option, but not found in any input file
6516 INFO: checking EXE
6516 INFO: rebuilding out00-EXE.toc because kotnetcli missing
6517 INFO: building EXE from out00-EXE.toc
6518 INFO: Appending archive to EXE /home/me/Scripts/kotnetcli/build/build/kotnetcli/kotnetcli
6523 INFO: checking COLLECT
6524 INFO: building COLLECT out00-COLLECT.toc
```

```
[me@pc build]$ dist/kotnetcli/kotnetcli                                  
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/home/me/Scripts/kotnetcli/build/pyinstaller/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/home/me/Scripts/kotnetcli/build/build/kotnetcli/out00-PYZ.pyz/keyring", line 12, in <module>
  File "/home/me/Scripts/kotnetcli/build/pyinstaller/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/home/me/Scripts/kotnetcli/build/build/kotnetcli/out00-PYZ.pyz/keyring.core", line 158, in <module>
  File "/home/me/Scripts/kotnetcli/build/build/kotnetcli/out00-PYZ.pyz/keyring.core", line 58, in init_backend
  File "/home/me/Scripts/kotnetcli/build/build/kotnetcli/out00-PYZ.pyz/keyring.core", line 66, in _get_best_keyring
  File "/home/me/Scripts/kotnetcli/build/build/kotnetcli/out00-PYZ.pyz/keyring.util", line 24, in wrapper
  File "/home/me/Scripts/kotnetcli/build/build/kotnetcli/out00-PYZ.pyz/keyring.backend", line 137, in get_all_keyring
  File "/home/me/Scripts/kotnetcli/build/build/kotnetcli/out00-PYZ.pyz/keyring.backend", line 129, in _load_backends
  File "/home/me/Scripts/kotnetcli/build/build/kotnetcli/out00-PYZ.pyz/keyring.backend", line 114, in _load_backend
  File "/home/me/Scripts/kotnetcli/build/build/kotnetcli/out00-PYZ.pyz/importlib", line 37, in import_module
ImportError: No module named file
[me@pc build]$ 
```

Solution:

First, edit the .spec file: the hiddenimport should look like this:

```
hiddenimports = ['keyring.backends.file',
                 'keyring.backends.Gnome',
                 'keyring.backends.Google',
                 'keyring.backends.keyczar',
                 'keyring.backends.kwallet',
                 'keyring.backends.multi',
                 'keyring.backends.OS_X',
                 'keyring.backends.pyfs',
                 'keyring.backends.SecretService',
                 'keyring.backends.Windows']
```

If you compile right now, the compiled binary will use `keyring.backends.file` as the keyring manager. You might want to use the Gnome keyring manager, like I did. But even when you force the keyring to do so (using `keyring.set_keyring(keyring.backends.Gnome.Keyring())`), it will not work, because there's something wrong with `Gnome.py`. To solve this problem: edit and put this at the top of `/usr/local/lib/python2.7/dist-packages/keyring/backends/Gnome.py` :

```
import datetime
from gi.repository import GnomeKeyring
```

Save and try to compile again. It should work now.

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/153
- Originally reported by: [GijsTimmers](http://bitbucket.org/GijsTimmers)
- Originally created at: 2014-12-03T15:06:14.294

**Comment by jaraco** [comment]
Thanks for your report.

> First, edit the .spec file: the hiddenimport should look like this:

The “.spec file” is `hook-keyring.backend.py`, right? Do you mean that we should unroll `[… for … in …]` expression there?

> To solve this problem: edit and put this at the top of `keyring/backends/Gnome.py`:
> 
> ```
> import datetime
> from gi.repository import GnomeKeyring
> ```
- Why is `datetime` needed? That file does not use that.
- We cannot import `GnomeKeyring` before checking for its existence.

---

Original comment by: Dmitry Shachnev

**Comment by jaraco** [comment]
> The “.spec file” is hook-keyring.backend.py, right?

No, the .spec file is a file used by [`pyinstaller`](https://github.com/pyinstaller/pyinstaller/wiki) to create a standalone executable from a python script. It contains instructions that are usually right, but sometimes, you have to change a few. In the case of `keyring`, you have to manually import some `keyring` modules to get everything working. This is probably more of a pyinstaller thing, and I think that [it will be resolved in future releases](https://github.com/pyinstaller/pyinstaller/issues/1101).

> Why is `datetime` needed? That file does not use that.

If you don't do that, `pyinstaller` will compile just fine, but if you try to execute the binary, you'll get an `ImportError`:

```
[me@pc dist]$ ./kotnetcli-lin 
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "/home/me/Scripts/kotnetcli/pyinstaller/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/home/me/Scripts/kotnetcli/build/compile-lin/out00-PYZ.pyz/credentials", line 18, in <module>
  File "/home/me/Scripts/kotnetcli/pyinstaller/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/home/me/Scripts/kotnetcli/build/compile-lin/out00-PYZ.pyz/keyring", line 12, in <module>
  File "/home/me/Scripts/kotnetcli/pyinstaller/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/home/me/Scripts/kotnetcli/build/compile-lin/out00-PYZ.pyz/keyring.core", line 158, in <module>
  File "/home/me/Scripts/kotnetcli/build/compile-lin/out00-PYZ.pyz/keyring.core", line 58, in init_backend
  File "/home/me/Scripts/kotnetcli/build/compile-lin/out00-PYZ.pyz/keyring.core", line 66, in _get_best_keyring
  File "/home/me/Scripts/kotnetcli/build/compile-lin/out00-PYZ.pyz/keyring.util", line 24, in wrapper
  File "/home/me/Scripts/kotnetcli/build/compile-lin/out00-PYZ.pyz/keyring.backend", line 137, in get_all_keyring
  File "/home/me/Scripts/kotnetcli/build/compile-lin/out00-PYZ.pyz/keyring.backend", line 129, in _load_backends
  File "/home/me/Scripts/kotnetcli/build/compile-lin/out00-PYZ.pyz/keyring.backend", line 114, in _load_backend
  File "/home/me/Scripts/kotnetcli/build/compile-lin/out00-PYZ.pyz/importlib", line 37, in import_module
  File "/home/me/Scripts/kotnetcli/pyinstaller/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/keyring/backends/Gnome.py", line 3, in <module>
    from gi.repository import GObject
  File "/home/me/Scripts/kotnetcli/pyinstaller/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/home/me/Scripts/kotnetcli/build/compile-lin/out00-PYZ.pyz/gi", line 42, in <module>
  File "/home/me/Scripts/kotnetcli/pyinstaller/PyInstaller/loader/pyi_importers.py", line 420, in load_module
    module = imp.load_module(fullname, fp, filename, self._c_ext_tuple)
ImportError: PyCapsule_Import could not import module "datetime"
```

If you import `datetime` in `Gnome.py`, the compiled file will run just fine.

> We cannot import `GnomeKeyring` before checking for its existence.

I understand what you mean. I don't know why, but for some reason, `pyinstaller` doesn't work with the way GnomeKeyring is imported here. Probably more of a `pyinstaller` thing, but it would be nice if it would be fixed.

---

Original comment by: [GijsTimmers](http://bitbucket.org/GijsTimmers)

**Comment by jaraco** [comment]
Yes, I think all of this is PyInstaller bug.

---

Original comment by: Dmitry Shachnev

**Comment by jaraco** [comment]
I agree with Dmitry. It appears as if even with a proper spec file, PyInstaller is failing to detect the need for 'datetime' in gi.repository, which causes keyring to detect that GnomeKeyring isn't viable, so falls back to a less preferred keyring.

What happens if you add 'gi.repository' to the spec file?

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
I've just removed `import datetime` and `from gi.repository import GnomeKeyring` from `Gnome.py`.

After that, I added 'gi.repository' to the hidden imports in the spec file.

When running `pyinstaller`, it will say:

```
6009 INFO: Hidden import 'gi.repository' has been found otherwise
```

Pyinstaller does not crash, it just builds the binary and exits. When I run the binary, I get:

```
Please enter password for encrypted keyring: 
```

So, pyinstaller is falling back to a less preferred keyring here.

---

Original comment by: [GijsTimmers](http://bitbucket.org/GijsTimmers)

**Comment by jaraco** [comment]
Hmm. What if you add 'datetime' also to hidden imports?

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
```
6037 INFO: Hidden import 'gi.repository' has been found otherwise
6038 INFO: Hidden import 'datetime' has been found otherwise
```

No difference elsewhere.

---

Original comment by: [GijsTimmers](http://bitbucket.org/GijsTimmers)

**Comment by jaraco** [comment]
It appears there's nothing keyring can do here. If there is, please present a proposal or otherwise revive the discussion.
