### ISSUE TITLE
Install fails into anaconda virtual environment

### ISSUE THREAD

**Issue by danpilch** [jaraco/keyring#157]
latest v5.2 fails to install into an anacona python virtual environment:

pip install -U keyring==5.2
Collecting keyring==5.2
  Using cached keyring-5.2.zip
    /opt/anaconda/envs/analyse/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'use_scm_version'
      warnings.warn(msg)
    zip_safe flag not set; analyzing archive contents...
    Installed /tmp/pip-build-AAWdMV/keyring/setuptools_scm-0.0.0-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-AAWdMV/keyring/setup.py", line 102, in <module>
        setuptools.setup(**setup_params)
      File "/opt/anaconda/envs/analyse/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/anaconda/envs/analyse/lib/python2.7/site-packages/setuptools/dist.py", line 225, in __init__
        _Distribution.__init__(self,attrs)
      File "/opt/anaconda/envs/analyse/lib/python2.7/distutils/dist.py", line 287, in **init**
        self.finalize_options()
      File "/opt/anaconda/envs/analyse/lib/python2.7/site-packages/setuptools/dist.py", line 258, in finalize_options
        ep.load()(self, ep.name, value)
      File "/opt/anaconda/envs/analyse/lib/python2.7/site-packages/pkg_resources.py", line 2060, in load
        entry = **import**(self.module_name, globals(),globals(), ['**name**'])
      File "/tmp/pip-build-AAWdMV/keyring/setuptools_scm-0.0.0-py2.7.egg/setuptools_scm/**init**.py", line 10, in <module>
        from .version import format_version
      File "/tmp/pip-build-AAWdMV/keyring/setuptools_scm-0.0.0-py2.7.egg/setuptools_scm/version.py", line 5, in <module>
        from pkg_resources import parse_version, SetuptoolsVersion, iter_entry_points
    ImportError: cannot import name SetuptoolsVersion
    Complete output from command python setup.py egg_info:
    /opt/anaconda/envs/analyse/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'use_scm_version'

```
  warnings.warn(msg)

zip_safe flag not set; analyzing archive contents...



Installed /tmp/pip-build-AAWdMV/keyring/setuptools_scm-0.0.0-py2.7.egg

Traceback (most recent call last):

  File "<string>", line 20, in <module>

  File "/tmp/pip-build-AAWdMV/keyring/setup.py", line 102, in <module>

    setuptools.setup(**setup_params)

  File "/opt/anaconda/envs/analyse/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/opt/anaconda/envs/analyse/lib/python2.7/site-packages/setuptools/dist.py", line 225, in __init__

    _Distribution.__init__(self,attrs)

  File "/opt/anaconda/envs/analyse/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "/opt/anaconda/envs/analyse/lib/python2.7/site-packages/setuptools/dist.py", line 258, in finalize_options

    ep.load()(self, ep.name, value)

  File "/opt/anaconda/envs/analyse/lib/python2.7/site-packages/pkg_resources.py", line 2060, in load

    entry = __import__(self.module_name, globals(),globals(), ['__name__'])

  File "/tmp/pip-build-AAWdMV/keyring/setuptools_scm-0.0.0-py2.7.egg/setuptools_scm/__init__.py", line 10, in <module>

    from .version import format_version

  File "/tmp/pip-build-AAWdMV/keyring/setuptools_scm-0.0.0-py2.7.egg/setuptools_scm/version.py", line 5, in <module>

    from pkg_resources import parse_version, SetuptoolsVersion, iter_entry_points

ImportError: cannot import name SetuptoolsVersion

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-AAWdMV/keyring
```

**Comment by jaraco** [comment]
That's a known issue with setuptools_scm and setuptools < 12. I'm going to switch back to hgtools for now.
