### ISSUE TITLE
Import of keyring takes 25s - or DBusException

### ISSUE THREAD

**Issue by arthurzenika** [jaraco/keyring#162]
```
# time python -m keyring
/usr/bin/python: No module named keyring.__main__; 'keyring' is a package and cannot be directly executed

real    0m25.235s
user    0m0.176s
sys     0m0.033s
```

or 

I sometimes bump into : 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 928, in load_modules
    ), fn_, path, desc
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/nova.py", line 100, in <module>
    from salt.utils.openstack import nova
  File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/nova.py", line 11, in <module>
    from novaclient.shell import OpenStackComputeShell
  File "/usr/lib/python2.7/dist-packages/novaclient/shell.py", line 38, in <module>
    import keyring
  File "/usr/lib/python2.7/dist-packages/keyring/__init__.py", line 12, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 180, in <module>
    init_backend()
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 59, in init_backend
    set_keyring(load_config() or _get_best_keyring())
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 67, in _get_best_keyring
    keyrings = backend.get_all_keyring()
  File "/usr/lib/python2.7/dist-packages/keyring/util/__init__.py", line 24, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 127, in get_all_keyring
    exceptions=TypeError))
  File "/usr/lib/python2.7/dist-packages/keyring/util/__init__.py", line 35, in suppress_exceptions
    for callable in callables:
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 119, in is_class_viable
    keyring_cls.priority
  File "/usr/lib/python2.7/dist-packages/keyring/util/properties.py", line 22, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/lib/python2.7/dist-packages/keyring/util/XDG.py", line 18, in wrapper
    return func(*args, **kwargs) * self.multiplier
  File "/usr/lib/python2.7/dist-packages/keyring/backends/SecretService.py", line 32, in priority
    list(secretstorage.get_all_collections(bus))
  File "/usr/lib/python2.7/dist-packages/secretstorage/collection.py", line 158, in get_all_collections
    service_obj = bus_get_object(bus, SECRETS, SS_PATH)
  File "/usr/lib/python2.7/dist-packages/secretstorage/util.py", line 50, in bus_get_object
    return bus.get_object(name, object_path, introspect=False)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.TimedOut: Activation of org.freedesktop.secrets timed out
```

Are the two problems linked ? Is the 25 seconds linked to a timeout ? Is there a way to disable trying dbus ?

**Comment by arthurzenika** [comment]
Sorry, am on ubuntu trusty with the following version : 

ii  python-keyring                    3.5-1                 all                   store and access your passwords safely

seems old judging by the changelog https://github.com/jaraco/keyring/blob/master/CHANGES.rst

only 4.0 in the next versions of ubuntu : http://packages.ubuntu.com/search?keywords=python-keyring

**Comment by mitya57** [comment]
Do you have gnome-keyring installed? Is it started automatically? Did you get this error once, or do you get it every time?

**Comment by arthurzenika** [comment]
gnome-keyring is installed. I believe it is started automatically.

```
~$ ps xaf | grep gnome
 4322 ?        Sl     0:00 /usr/bin/gnome-keyring-daemon --daemonize --login
 4635 ?        Sl     0:00 /usr/lib/at-spi2-core/at-spi2-registryd --use-gnome-session
 5726 ?        S      0:00 /usr/bin/gnome-keyring-daemon --start --foreground --components=secrets

```

I'm running awesome window manager http://awesome.naquadah.org/ and not a gnome session so there might be some stuff that doesn't communicate correctly. I don't get this error every time, but sufficiently frequently to report it as a bug.

**Comment by mitya57** [comment]
Looking again at this bug:
- The timeout error looks like an issue in GNOME Keyring, we cannot do anything about this.
- The only thing I can do is redirect `DBusException` to `SecretServiceNotAvialableException`, which will mean keyring will try another backend after the timeout error occurs. However this is not optimal, because you will still have to wait those 15 seconds.
- Probably the easiest solution for you will be selecting a different backend via a configuration file. See [here](https://github.com/jaraco/keyring/blob/master/README.rst#customize-your-keyring-by-config-file) how to do this.

**Comment by arthurzenika** [comment]
@mitya57 thanks for taking a look at this. 

`python -c "import keyring.util.platform_; print(keyring.util.platform_.config_root())"` works but shows a path where I have no file. Is there a way to get the default configuration and then comment out the keyrings I don't want to use ?

**Comment by mitya57** [comment]
That file doesn't exist by default, you need to create it.

**Comment by jaraco** [comment]
As described, I don't think there's anything keyring can do to help here. If there is - for example, a check to fail faster or an environment variable to avoid detecting Gnome in blacklisted environments, feel free to provide a suggestion and revive the discussion.

**Comment by jnpkrn** [comment]
I think `keyring` should definitely _not_ block at all when configured
with particular backend, i.e. no other probing or what not should occur.
This looks overboard to me (on Linux without `gnome-keyring` or any
other DBus attached service like that, I simply don't want it, and
the package I want to use imports `keyring` unconditionally even if
it's not used in my workflow, either):

`time env PYTHON_KEYRING_BACKEND=keyring.backends.fail.Keyring python3 -m keyring --list-backends`

```
keyring.backends.SecretService.Keyring (priority: 5)
keyring.backends.chainer.ChainerBackend (priority: 0)
keyring.backends.fail.Keyring (priority: 0)

real	0m50.160s
user	0m0.162s
sys	0m0.038s
```

Ditto with `null` backend.

**Comment by mitya57** [comment]
@jnpkrn `--list-backends` calculates the priority of each backend, and for that it needs to know whether they are available.

Does the same issue happen when you use the Python API?

**Comment by jnpkrn** [comment]
@mitya57 Figured out that using `--list-backends` may not prove
anything, since best-effort search is intuitively sensed with that
(you can at least see what the resolution was at system in question).

Alas, comparable slowdown happens just upon module import.

The package using it that I have in mind here is jrnl:
https://github.com/maebert/jrnl/blob/1.9.8/jrnl/util.py#L6

Would be nice and handy if having in the environment something
like that `PYTHON_KEYRING_BACKEND=keyring.backends.fail.Keyring`
intentionally to suppress lengthy lookup would do exactly that.
