### ISSUE TITLE
Keyring breaks apps bundled with py2app

### ISSUE THREAD

**Issue by deltaraven** [jaraco/keyring#175]
By my initial investigation, it looks like keyring is doing some "import magic" when it is imported. This causes problems when it has been bundled up with a tool like py2app.

I have a very simple example app which explicitly imports the `OS_X` backend:

``` python
#keyring_issues.py

from keyring.backends.OS_X import Keyring

def main():
    keyring = Keyring()
    keyring.set_password("keyring_issues", "someone", "secret")
    print("success")

if __name__ == "__main__":
    main()

```

Running the script from source works fine:

```
$ python ./keyring_issues.py
success
```

Next, I build an app bundle (`python setup.py py2app`) which will run the exact same script. Attempting to execute the app results in a crash. Below is the output when I attempt to execute the app from the command line:

```
$ ./dist/keyring_issues.app/Contents/MacOS/keyring_issues
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>: Traceback (most recent call last):
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>:   File "/Users/joel/Code/misc/keyring_issues/dist/keyring_issues.app/Contents/Resources/__boot__.py", line 351, in <module>
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>:     _run()
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>:   File "/Users/joel/Code/misc/keyring_issues/dist/keyring_issues.app/Contents/Resources/__boot__.py", line 336, in _run
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>:     exec(compile(source, path, 'exec'), globals(), globals())
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>:   File "/Users/joel/Code/misc/keyring_issues/dist/keyring_issues.app/Contents/Resources/keyring_issues.py", line 3, in <module>
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>:     from keyring.backends.OS_X import Keyring
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>:   File "keyring/__init__.pyc", line 12, in <module>
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>:   File "keyring/core.pyc", line 158, in <module>
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>:   File "keyring/core.pyc", line 58, in init_backend
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>:   File "keyring/core.pyc", line 66, in _get_best_keyring
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>:   File "keyring/util/__init__.pyc", line 24, in wrapper
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>:   File "keyring/backend.pyc", line 179, in get_all_keyring
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>:   File "keyring/backend.pyc", line 139, in _load_backends
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>:   File "keyring/backend.pyc", line 124, in _load_backend
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>:   File "importlib/__init__.pyc", line 37, in import_module
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>: ImportError: No module named file
Sep 29 02:50:40 mac.local keyring_issues[23324] <Notice>: 2015-09-29 02:50:40.074 keyring_issues[23324:25500651] keyring_issues Error
```

FWIW, here is the setup.py I use to generate the app (via `python setup.py py2app`):

``` python
#setup.py

from setuptools import setup, find_packages

setup(
    name='keyring_issues',
    version="0.1",
    description="python py2app example application",
    packages=find_packages(),
    app = ["keyring_issues.py"],
    entry_points = {
        "console_scripts": ["keyring_issues = keyring_issues:main"],
    }
)
```

**Comment by jaraco** [comment]
That's right. Keyring does import magic for loading the backends (both native and third-party).

There have previously been issues with this, either with py2app or with other wrapping products. There is a file in the project repo, "hook-keyring.backend.py" which is used by pyinstaller to indicate which modules are programmatically imported. Perhaps py2app has a similar hook?

**Comment by artoonie** [comment]
For those stumbling upon this from a Google search: see http://stackoverflow.com/questions/19858161/error-while-packing-keyring-module-with-py2app-on-mac-osx

Manually importing everything in `keyring.backend` before importing `keyring` worked for me.
