### ISSUE TITLE
Tests won't run in Python3

### ISSUE THREAD

**Issue by DamienCassou** [jaraco/keyring#214]
With Python2, everything works fine. But with Python3, I get the trace below. All errors but the first one are `ImportError: cannot import name 'backend'`.

```
running test
running egg_info
writing top-level names to keyring.egg-info/top_level.txt
writing entry points to keyring.egg-info/entry_points.txt
writing requirements to keyring.egg-info/requires.txt
writing keyring.egg-info/PKG-INFO
writing dependency_links to keyring.egg-info/dependency_links.txt
reading manifest file 'keyring.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '.hg/last-message.txt'
writing manifest file 'keyring.egg-info/SOURCES.txt'
running build_ext
keyring.tests.backends.test_Gnome (unittest.loader._FailedTest) ... ERROR
keyring.tests.backends.test_Google (unittest.loader._FailedTest) ... ERROR
keyring.tests.backends.test_OS_X (unittest.loader._FailedTest) ... ERROR
keyring.tests.backends.test_SecretService (unittest.loader._FailedTest) ... ERROR
keyring.tests.backends.test_Windows (unittest.loader._FailedTest) ... ERROR
keyring.tests.backends.test_crypto (unittest.loader._FailedTest) ... ERROR
keyring.tests.backends.test_file (unittest.loader._FailedTest) ... ERROR
keyring.tests.backends.test_keyczar (unittest.loader._FailedTest) ... ERROR
keyring.tests.backends.test_kwallet (unittest.loader._FailedTest) ... ERROR
keyring.tests.backends.test_multi (unittest.loader._FailedTest) ... ERROR
keyring.tests.backends.test_pyfs (unittest.loader._FailedTest) ... ERROR
keyring.tests.test_backend (unittest.loader._FailedTest) ... ERROR
keyring.tests.test_cli (unittest.loader._FailedTest) ... ERROR
keyring.tests.test_core (unittest.loader._FailedTest) ... ERROR
keyring.tests.test_util (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: keyring.tests.backends.test_Gnome (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: keyring.tests.backends.test_Gnome
Traceback (most recent call last):
  File "/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/tmp/nix-build-python3.4-keyring-3.3.drv-0/keyring-3.3/keyring/__init__.py", line 12, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/tmp/nix-build-python3.4-keyring-3.3.drv-0/keyring-3.3/keyring/core.py", line 180, in <module>
    init_backend()
  File "/tmp/nix-build-python3.4-keyring-3.3.drv-0/keyring-3.3/keyring/core.py", line 59, in init_backend
    set_keyring(load_config() or _get_best_keyring())
  File "/tmp/nix-build-python3.4-keyring-3.3.drv-0/keyring-3.3/keyring/core.py", line 67, in _get_best_keyring
    keyrings = backend.get_all_keyring()
  File "/tmp/nix-build-python3.4-keyring-3.3.drv-0/keyring-3.3/keyring/util/__init__.py", line 24, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/tmp/nix-build-python3.4-keyring-3.3.drv-0/keyring-3.3/keyring/backend.py", line 115, in get_all_keyring
    __import__('keyring.backends.'+mod_name, fromlist=('__name__',))
  File "/tmp/nix-build-python3.4-keyring-3.3.drv-0/keyring-3.3/keyring/backends/Google.py", line 11, in <module>
    import gdata.docs.service
  File "/nix/store/pf2c14yg7m8s1079z17mbbmiw5bvxkp3-python3.4-gdata-2.0.18/lib/python3.4/site-packages/gdata/__init__.py", line 27, in <module>
    import atom
  File "/nix/store/pf2c14yg7m8s1079z17mbbmiw5bvxkp3-python3.4-gdata-2.0.18/lib/python3.4/site-packages/atom/__init__.py", line 133, in <module>
    CreateClassFromXMLString)
  File "/nix/store/pf2c14yg7m8s1079z17mbbmiw5bvxkp3-python3.4-gdata-2.0.18/lib/python3.4/site-packages/atom/__init__.py", line 97, in mark_deprecated
    optional_warn_function.func_name = f.func_name
AttributeError: 'function' object has no attribute 'func_name'


======================================================================
ERROR: keyring.tests.backends.test_Google (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/unittest/case.py", line 580, in run
    testMethod()
  File "/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: keyring.tests.backends.test_Google
Traceback (most recent call last):
  File "/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/tmp/nix-build-python3.4-keyring-3.3.drv-0/keyring-3.3/keyring/__init__.py", line 12, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/tmp/nix-build-python3.4-keyring-3.3.drv-0/keyring-3.3/keyring/core.py", line 14, in <module>
    from keyring import backend
ImportError: cannot import name 'backend'
```

**Comment by mitya57** [comment]
You shouldn't put gdata on your Python 3's sys.path because gdata isn't compatible with Python 3.

**Comment by DamienCassou** [comment]
thank you very much. Here is a new trace.

```
test_escape_unescape (keyring.tests.test_util.EscapeTestCase) ... ok
test_low_byte (keyring.tests.test_util.EscapeTestCase) ... ok

======================================================================
ERROR: test_difficult_chars (keyring.tests.backends.test_pyfs.EncryptedLocalPyfilesystemKeyringNoSubDirTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/base64.py", line 519, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: str object does not have the buffer interface

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/nix-build-python3.4-keyring-3.3.drv-0/keyring-3.3/keyring/tests/test_backend.py", line 73, in test_difficult_chars
    self.check_set_get(service, username, password)
  File "/tmp/nix-build-python3.4-keyring-3.3.drv-0/keyring-3.3/keyring/tests/test_backend.py", line 60, in check_set_get
    self.set_password(service, username, "")
  File "/tmp/nix-build-python3.4-keyring-3.3.drv-0/keyring-3.3/keyring/tests/test_backend.py", line 46, in set_password
    self.keyring.set_password(service, username, password)
  File "/tmp/nix-build-python3.4-keyring-3.3.drv-0/keyring-3.3/keyring/backends/pyfs.py", line 197, in set_password
    password_base64 = base64.encodestring(password_encrypted).decode()
  File "/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/base64.py", line 548, in encodestring
    return encodebytes(s)
  File "/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/base64.py", line 536, in encodebytes
    _input_type_check(s)
  File "/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/base64.py", line 522, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
```

**Comment by jaraco** [comment]
The tests pass on https://travis-ci.org/jaraco/keyring. Can you ascertain what's different about your environment that they fail? Based on the path in the trace, you have keyring 3.3. Why not use the latest ver?
