### ISSUE TITLE
keyring.util omitted from install

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#25]
I'm using Python 2.7 and distribute 0.6.14 on Windows 64-bit. When I install keyring from source (or from the distribution), it doesn't include sub-packages (keyring.util in particular).

For example,

```
#!shell

PS C:\Users\jaraco\projects\public\keyring> ./setup install
running install
running build
running build_py
copying keyring\backend.py -> build\lib.win-amd64-2.7\keyring
copying keyring\core.py -> build\lib.win-amd64-2.7\keyring
copying keyring\getpassbackend.py -> build\lib.win-amd64-2.7\keyring
copying keyring\__init__.py -> build\lib.win-amd64-2.7\keyring
running build_ext
running install_lib
copying build\lib.win-amd64-2.7\win32_crypto.pyd -> C:\Python\Lib\site-packages
running install_egg_info
Removing C:\Python\Lib\site-packages\keyring-0.3-py2.7.egg-info
Writing C:\Python\Lib\site-packages\keyring-0.3-py2.7.egg-info
```

Thereafter, trying to import keyring results in the following ImportError:

```
C:\> python -c 'import keyring'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python\lib\site-packages\keyring-0.3-py2.7-win-amd64.egg\keyring\__init__.py", line 9, in <module>
    from core import set_keyring, get_keyring, set_password, get_password
  File "c:\python\lib\site-packages\keyring-0.3-py2.7-win-amd64.egg\keyring\core.py", line 12, in <module>
    from keyring import backend
  File "c:\python\lib\site-packages\keyring-0.3-py2.7-win-amd64.egg\keyring\backend.py", line 11, in <module>
    from keyring.util.escape import escape as escape_for_ini
ImportError: No module named util.escape
```

Explicitly include 'keyring.util' in the packages parameter to setup seems to resolve the issue.

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/25
- Originally reported by: Jason R. Coombs
- Originally created at: 2010-08-15T18:52:58.041

**Comment by jaraco** [comment]
Including patch.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
I use the mercurial_keyring extension for Mercurial.
Using keyring 0.3 causes "abort: No module named util.escape!" if I do "hg outgoing" (MacOS X 10.6.4, Python 2.7).
Switching back to keyring v0.2 works fine for me.

---

Original comment by: Markus Banfi

**Comment by jaraco** [comment]
There is a new release of keyring (0.4) which should fix the problem.
http://pypi.python.org/pypi/keyring/0.4#id1

---

Original comment by: Markus Banfi

**Comment by jaraco** [comment]
Thanks for fixing this, Tarek

---

Original comment by: Jason R. Coombs
