### ISSUE TITLE
set password give run time error 

### ISSUE THREAD

**Issue by piyushgohel** [jaraco/keyring#257]
Hello,

When i try to set user name and password in keyring then it through following runtime error.

Traceback (most recent call last):
  File "/home/vrs/Piyush/Projects/monitor_task/bin/keyring", line 9, in <module>
    load_entry_point('keyring==10.1', 'console_scripts', 'keyring')()
  File "build/bdist.linux-x86_64/egg/keyring/cli.py", line 101, in main
  File "build/bdist.linux-x86_64/egg/keyring/cli.py", line 64, in run
  File "build/bdist.linux-x86_64/egg/keyring/core.py", line 48, in set_password
  File "build/bdist.linux-x86_64/egg/keyring/backends/fail.py", line 23, in get_password
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details

**Comment by jaraco** [comment]
Did you read the README as indicated? There are extra steps required for Linux.
