### ISSUE TITLE
pywin32-ctypes==0.1.1 breaks keyring on Windows

### ISSUE THREAD

**Issue by kbarnes3** [jaraco/keyring#278]
I installed keyring in a fresh virtualenv and it didn't work for me (Windows 10 15063, Python 3.6.1 amd64). Trying to access my keyring would give "RuntimeError: No recommended backend was available.". Comparing it to a working venv, I noticed I now had pywin32-ctypes==0.1.1. Running `pip install pywin32-ctypes==0.0.1` fixed my problems.

I've got no clue if this is a problem that pywin32-ctypes or keyring should fix. I'm raising it here because `pip install keyring` or `pip install something_that_depends_on_keyring` are broken on Windows right now.

Full output:
```
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kevin\Documents\Code\MiscHomely\venv\Scripts\auth.exe\__main__.py", line 9, in <module>
  File "c:\users\kevin\documents\code\mischomely\venv\lib\site-packages\plush\console.py", line 25, in auth_entry
    command()
  File "c:\users\kevin\documents\code\mischomely\venv\lib\site-packages\plush\oauth_flow.py", line 23, in run_oauth_flow
    cred = run_flow(flow, storage)
  File "c:\users\kevin\documents\code\mischomely\venv\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "c:\users\kevin\documents\code\mischomely\venv\lib\site-packages\oauth2client\tools.py", line 247, in run_flow
    storage.put(credential)
  File "c:\users\kevin\documents\code\mischomely\venv\lib\site-packages\oauth2client\client.py", line 421, in put
    self.locked_put(credentials)
  File "c:\users\kevin\documents\code\mischomely\venv\lib\site-packages\oauth2client\contrib\keyring_storage.py", line 87, in locked_put
    credentials.to_json())
  File "c:\users\kevin\documents\code\mischomely\venv\lib\site-packages\keyring\core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "c:\users\kevin\documents\code\mischomely\venv\lib\site-packages\keyring\backends\fail.py", line 23, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```

**Comment by jaraco** [comment]
I just [re-ran the Windows tests](https://ci.appveyor.com/project/jaraco/keyring/build/1.0.39), and although they still pass, I can see the tests are being skipped, probably due to the issue reported herein.

**Comment by jaraco** [comment]
This new commit adds a test that should ensure that the Windows backend remains viable (and [is currently failing](https://ci.appveyor.com/project/jaraco/keyring/build/1.0.40/job/50dkf0evgwqxg3yx)).

**Comment by jaraco** [comment]
Looking at the [comparison of 0.0.1 to 0.1.1](https://github.com/enthought/pywin32-ctypes/compare/v0.0.1...v0.1.1), it looks like a lot has changed and the package has been restructured. The next step is for someone to figure out what changes are needed to maintain compatibility (as it's not described in the changelog). For now, the best bet is probably to pin to the old version.

**Comment by jaraco** [comment]
Late builds in appveyor are passing. Problem is solved.
