### ISSUE TITLE
keyring.errors.InitError: Failed to unlock the collection!

### ISSUE THREAD

**Issue by little-dude** [jaraco/keyring#286]
I have been using `keyring` for about two years with no issue, but this morning, after a reboot, I'm unable to access existing passwords or set new ones because of this error: `keyring.errors.InitError: Failed to unlock the collection!`

OS: Archlinux
Keyring version: 10.4.0-1 (updated on june 26th)
Seeing the issue with both python 2 and python 3

```
~ ❯❯❯ python                                                                                                      
Python 3.6.2 (default, Jul 20 2017, 03:52:27)
[GCC 7.1.1 20170630] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import keyring

>>> keyring.get_password('my-account', 'little-dude')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/keyring/core.py", line 41, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python3.6/site-packages/keyring/backends/SecretService.py", line 58, in get_password
    collection = self.get_preferred_collection()
  File "/usr/lib/python3.6/site-packages/keyring/backends/SecretService.py", line 52, in get_preferred_collection
    raise InitError("Failed to unlock the collection!")
keyring.errors.InitError: Failed to unlock the collection!

>>> keyring.set_password('dummy', 'little-dude', 'password')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/keyring/core.py", line 47, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/lib/python3.6/site-packages/keyring/backends/SecretService.py", line 70, in set_password
    collection = self.get_preferred_collection()
  File "/usr/lib/python3.6/site-packages/keyring/backends/SecretService.py", line 52, in get_preferred_collection
    raise InitError("Failed to unlock the collection!")
keyring.errors.InitError: Failed to unlock the collection!
```

**Comment by mitya57** [comment]
Are you able to unlock the collection in Seahorse?

**Comment by little-dude** [comment]
I'm a little embarassed, because a reboot actually fixed the issue =/
I did not even try with Seahorse before rebooting, sorry.
I think this can be closed, I'll come back with more info if that re-happens.

**Comment by boltbeard** [comment]
> Are you able to unlock the collection in Seahorse?

I have the same error, but seahorse can't be used as the use case is on a server (no display, only command line), and restarting the computer would be difficult as its a company server which gets restarted every say once in a month maybe!

Would really appreciate it if there was another way, I hope this is a valid case for re-opening the issue.

**Comment by ghost** [comment]
thanx
