### ISSUE TITLE
While loading/testing backends should keyring be overzealous with exceptions catching?

### ISSUE THREAD

**Issue by yarikoptic** [jaraco/keyring#316]
ATM https://github.com/jaraco/keyring/blob/master/keyring/backends/SecretService.py#L39 catches only exceptions.SecretServiceNotAvailableException exception assuming that none other could be thrown. Here is my usecase:
```shell
$> python -c "import keyring.util.platform_; print(keyring.util.platform_.config_root())"                                 
No handlers could be found for logger "keyring.backend"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/keyring/__init__.py", line 3, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/keyring/core.py", line 154, in <module>
    init_backend()
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/keyring/core.py", line 67, in init_backend
    keyrings = filter(limit, backend.get_all_keyring())
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/keyring/util/__init__.py", line 21, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/keyring/backend.py", line 173, in get_all_keyring
    exceptions=TypeError))
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/keyring/util/__init__.py", line 31, in suppress_exceptions
    for callable in callables:
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/keyring/backend.py", line 165, in is_class_viable
    keyring_cls.priority
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/keyring/util/properties.py", line 24, in __get__
    return self.fget.__get__(None, owner)()
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/keyring/backends/SecretService.py", line 38, in priority
    list(secretstorage.get_all_collections(bus))
  File "/usr/lib/python2.7/dist-packages/secretstorage/collection.py", line 149, in get_all_collections
    yield Collection(bus, collection_path)
  File "/usr/lib/python2.7/dist-packages/secretstorage/collection.py", line 43, in __init__
    signature='ss')
  File "/usr/lib/python2.7/dist-packages/secretstorage/util.py", line 34, in function_out
    raise ItemNotFoundException('Item does not exist!')
secretstorage.exceptions.ItemNotFoundException: Item does not exist!
```
IMHO it would be better if it would have caught all exceptions I guess while checking if any given backend is available (keyring is 12.0.1)

**Comment by yarikoptic** [comment]
note that pretty much I cannot use keyring at all because 'import keyring' leads to this exception before I could do anything (e.g. set to a different backend) in my program

**Comment by mitya57** [comment]
This error most likely means that you have gnome-keyring installed and running, but it does not have any actual keyring created.

Create one and the error would be gone (though I agree that keyring should handle such errors properly).

**Comment by yarikoptic** [comment]
Thanks! I definitely had a keyring, but I might have removed it if it was stored under ~/.local/shared

**Comment by jaraco** [comment]
If keyring were more aggressive about catching exceptions when loading keyrings, that would also help with #319.

**Comment by yarikoptic** [comment]
Note also that this issue is happening merely on import of keyring module, which imho shouldn't happen until I invoke keyring's API, and also should not fail since may be it is not the backend I am interested to use (e.g. as setup in the .cfg file to use plaintext one)
```
$> python -c 'import keyring'
Traceback (most recent call last):
...
  File "/usr/lib/python2.7/dist-packages/secretstorage/util.py", line 34, in function_out
    raise ItemNotFoundException('Item does not exist!')
secretstorage.exceptions.ItemNotFoundException: Item does not exist!
```

~~and it was not behaving like that before (running in another venv with dated keyring)~~ (edit: scrape it -- I think it didn't, probably that was my patched version)
```
$> python -c 'import pkg_resources; print(pkg_resources.get_distribution("keyring").version)'
12.0.2.dev4+g564019f

$> python -c 'import keyring'                                                                
No handlers could be found for logger "keyring.backend"
```

so I would appreciate if there was a bug fix release to address this issue since hinders usability of keyring greatly

**Comment by yarikoptic** [comment]
thanks @mitya57 !  I still think that keyring should be more aggressive about catching exceptions from backends upon import, but let's see first how this one helps ;)

**Comment by mitya57** [comment]
Yes, I started with this and will leave further improvements to @jaraco.

Also I see you get this error printed:

    No handlers could be found for logger "keyring.backend"

I think it is coming from this line:

https://github.com/jaraco/keyring/blob/3261e31b36461ce8dc9803d49a824dfb035c3206/keyring/backend.py#L152

If you call `logging.basicConfig()` before importing keyring, you will probably see the real error.

Or maybe Keyring should use the warnings mechanism instead of logging for showing such errors?
