### ISSUE TITLE
Broken Windows keyring is loaded on linux platform ubuntu 16.04

### ISSUE THREAD

**Issue by hayesgb** [jaraco/keyring#319]
I'm seeing something similar to #307 on Ubuntu 16.04, Python 3.5.2 using keyring 12.0.1

```
Error initializing plugin EntryPoint('windows', 'keyring.backends.Windows', None, Distribution('keyring', '12.0.1')).
Traceback (most recent call last):
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/cffi/cparser.py", line 276, in _parse
    ast = _get_parser().parse(fullcsource)
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/pycparser/c_parser.py", line 1761, in p_error
    column=self.clex.find_tok_column(p)))
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/pycparser/plyparser.py", line 66, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: <cdef source string>:4:70: before: LPTSTR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/keyring/backend.py", line 148, in _load_plugins
    init_func = ep.load()
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/keyring/backends/Windows.py", line 12, in <module>
    from win32ctypes.pywin32 import pywintypes
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/win32ctypes/pywin32/__init__.py", line 11, in <module>
    from win32ctypes.pywin32 import win32api
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/win32ctypes/pywin32/win32api.py", line 12, in <module>
    from win32ctypes.core import _common, _kernel32, _backend
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/win32ctypes/core/__init__.py", line 20, in <module>
    from .cffi import _advapi32, _common, _kernel32
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/win32ctypes/core/cffi/_advapi32.py", line 14, in <module>
    from ._kernel32 import _GetACP
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/win32ctypes/core/cffi/_kernel32.py", line 50, in <module>
    """)
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/cffi/api.py", line 107, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/cffi/api.py", line 121, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/cffi/cparser.py", line 315, in parse
    self._internal_parse(csource)
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/cffi/cparser.py", line 320, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/cffi/cparser.py", line 278, in _parse
    self.convert_pycparser_error(e, csource)
  File "/home/gregory.hayes/myenv/lib/python3.5/site-packages/cffi/cparser.py", line 307, in convert_pycparser_error
    raise CDefError(msg)
cffi.error.CDefError: cannot parse "typedef WINBOOL  volatile volatile const( *ENUMRESTYPEPROC) (HANDLE, LPTSTR, LONG_PTR);"
<cdef source string>:4:70: before: LPTSTR
```

**Comment by jaraco** [comment]
pywin32-ctypes is only a declared dependency on Windows. Do you know why that package was installed on Linux?

**Comment by hayesgb** [comment]
Development was done in Python on a Windows machine.  The environment was replicated on Linux for deployment.

**Comment by jaraco** [comment]
I see. I suggest that's a bad model for deployment. You'll find that you run into other issues if you do that, especially as projects become increasingly reliant on environment markers to give specific dependencies for specific platforms. I would just uninstall pywin32-ctypes before doing the deployment (or otherwise exclude it from the Linux deployment).

I do have the intention to move each of these platform-specific backends to their own package, such that if you were to install on Windows, you'd get the Windows backend, and if you were to install on Linux, you'd get the Linux default backends... and not the others.

In your deployment model, you would end up on Linux without the Linux backends but with the Windows backend, in which case having the Windows backend robust to being installed on Linux with the Windows dependencies wouldn't help (you'd not have any viable backend).

Can you explore removing or not installing pywin32-ctypes to the Linux env and report back how viable that is as a more robust, permanent solution?

**Comment by jaraco** [comment]
I suspect you can work around the issue by stubbing out the Windows backend module (before importing keyring):

```
import sys
import types
sys.modules['keyring.backends.Windows'] = types.ModuleType('keyring.backends.Windows')
```

Maybe it would make sense to catch errors other than `ImportError` when attempting to import the dependency modules. The OS_X module does just that. Kwallet and SecretService trap an additional AttributeError exception due to #296, but not any Exception.
