### ISSUE TITLE
RPM package build failure

### ISSUE THREAD

**Issue by frispete** [jaraco/keyring#325]
Hi Jaraco,

in an attempt to upgrade the openSUSE distribution package of keyring from 10.5.0 to 12.2.0, I stumbled across this issue:
```
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    setuptools.setup(**params)
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 363, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 519, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/hp/src/obs/home:frispete:python/python-keyring/keyring-12.2.0/.eggs/setuptools_scm-2.0.0-py2.7.egg/setuptools_scm/integration.py", line 22, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/home/hp/src/obs/home:frispete:python/python-keyring/keyring-12.2.0/.eggs/setuptools_scm-2.0.0-py2.7.egg/setuptools_scm/__init__.py", line 119, in get_version
    parsed_version = _do_parse(root, parse)
  File "/home/hp/src/obs/home:frispete:python/python-keyring/keyring-12.2.0/.eggs/setuptools_scm-2.0.0-py2.7.egg/setuptools_scm/__init__.py", line 97, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % root)
LookupError: setuptools-scm was unable to detect version for '/home/hp/src/obs/home:frispete:python/python-keyring/keyring-12.2.0'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

Since the PyPI and the github tarball of keyring-12.2.0.tar.gz are identical, something else must be wrong, but I failed to follow the way, how keyring is supposed to determine its version.

We're using:
`setuptools-39.1.0`
`setuptools_scm-2.0.0`
`entrypoints-0.2.3`

Any idea, what's wrong here, anybody?

**Comment by jaraco** [comment]
Hmm. At first blush, it's not an issue for me:

```
~ $ pip install --no-binary keyring keyring
Collecting keyring
  Downloading https://files.pythonhosted.org/packages/a9/67/b2b53b157abf5973f795d6859f892a1dc2ac4ab1a232f57b34547be558eb/keyring-12.2.0.tar.gz (42kB)
    100% |████████████████████████████████| 51kB 18kB/s
Requirement already satisfied: entrypoints in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from keyring) (0.2.3)
Installing collected packages: keyring
  Running setup.py install for keyring ... done
Successfully installed keyring-12.2.0
```

**Comment by jaraco** [comment]
I am able to replicate it with the tarball from git:

```
~ $ pip install https://github.com/jaraco/keyring/archive/12.2.0.tar.gz
Collecting https://github.com/jaraco/keyring/archive/12.2.0.tar.gz
  Downloading https://github.com/jaraco/keyring/archive/12.2.0.tar.gz
     / 40kB 7.1kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-zis7h78t/setup.py", line 99, in <module>
        setuptools.setup(**params)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 333, in __init__
        _Distribution.__init__(self, attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/dist.py", line 476, in finalize_options
        ep.load()(self, ep.name, value)
      File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-zis7h78t/.eggs/setuptools_scm-2.0.0-py3.6.egg/setuptools_scm/integration.py", line 22, in version_keyword
        dist.metadata.version = get_version(**value)
      File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-zis7h78t/.eggs/setuptools_scm-2.0.0-py3.6.egg/setuptools_scm/__init__.py", line 119, in get_version
        parsed_version = _do_parse(root, parse)
      File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-zis7h78t/.eggs/setuptools_scm-2.0.0-py3.6.egg/setuptools_scm/__init__.py", line 97, in _do_parse
        "use git+https://github.com/user/proj.git#egg=proj" % root)
    LookupError: setuptools-scm was unable to detect version for '/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-zis7h78t'.

    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessarymetadata and will not work.

    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-zis7h78t/
```

Again, this is expected, and what the reported error indicates.

**Comment by jaraco** [comment]
> Since the PyPI and the github tarball of keyring-12.2.0.tar.gz are identical...

The tarballs aren't the same when I download them:

```
$ curl -sL https://files.pythonhosted.org/packages/a9/67/b2b53b157abf5973f795d6859f892a1dc2ac4ab1a232f57b34547be558eb/keyring-12.2.0.tar.gz -o - | tar xz
$ grep Version keyring-12.2.0/PKG-INFO
Metadata-Version: 2.1
Version: 12.2.0
$ rm -rf keyring-12.2.0
$ curl -s -L https://github.com/jaraco/keyring/archive/12.2.0.tar.gz -o - | tar xz
$ grep Version keyring-12.2.0/PKG-INFO
grep: keyring-12.2.0/PKG-INFO: No such file or directory
```

Solution: Install from PyPI.
