### ISSUE TITLE
Crash on 13.2.0: TypeError: pass_from_pipe() missing 1 required positional argument: 'cls'

### ISSUE THREAD

**Issue by r4vi** [jaraco/keyring#335]
## stacktrace 

```bash
(twine) ravi@ ~/code/ $ keyring set hello r4vi
Traceback (most recent call last):
  File "/home/ravi/.local/venvs/twine/bin/keyring", line 11, in <module>
    sys.exit(main())
  File "/home/ravi/.local/venvs/twine/lib/python3.6/site-packages/keyring/cli.py", line 120, in main
    return cli.run(argv)
  File "/home/ravi/.local/venvs/twine/lib/python3.6/site-packages/keyring/cli.py", line 71, in run
    (username, service))
  File "/home/ravi/.local/venvs/twine/lib/python3.6/site-packages/keyring/cli.py", line 90, in input_password
    return self.pass_from_pipe() or getpass.getpass(prompt)
TypeError: pass_from_pipe() missing 1 required positional argument: 'cls'
```
downgrading to 13.1.0 fixes it

## environment
OS: Ubuntu 18.04
installed in a virtualenv with python 3.6.4 and alongside twine. 
System package python3-dbus is installed

**Comment by jachin** [comment]
I'm seeing much the same issue on macOS. Downgrading also fixed the issue.

# environment
macOS 10.13.5
Python 3.7.0 (installed via home brew)
keyring is installed "system wide".

**Comment by jaraco** [comment]
Oh that sounds bad. I’ll work out or approve a fix this evening.

**Comment by r4vi** [comment]
thanks for the quick fix @jaraco
