### ISSUE TITLE
Getting an AttributeError: module 'entrypoints' has no attribute 'get_group_all'

### ISSUE THREAD

**Issue by ignisf** [jaraco/keyring#337]
Hello,

I am trying to run `keyring` on Archlinux (with Gnome) but am getting the error mentioned in the subject. Here is the stack trace:

```
Traceback (most recent call last):
  File "/usr/bin/keyring", line 11, in <module>
    load_entry_point('keyring==13.2.1', 'console_scripts', 'keyring')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/keyring/__init__.py", line 3, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/lib/python3.6/site-packages/keyring/core.py", line 154, in <module>
    init_backend()
  File "/usr/lib/python3.6/site-packages/keyring/core.py", line 67, in init_backend
    keyrings = filter(limit, backend.get_all_keyring())
  File "/usr/lib/python3.6/site-packages/keyring/util/__init__.py", line 21, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/keyring/backend.py", line 167, in get_all_keyring
    _load_plugins()
  File "/usr/lib/python3.6/site-packages/keyring/backend.py", line 150, in _load_plugins
    entry_points = entrypoints.get_group_all(group=group)
AttributeError: module 'entrypoints' has no attribute 'get_group_all'
```

Relevant downstream issue: https://bugs.archlinux.org/index.php?do=details&task_id=59368

Last known working version: 11.0.0

**Comment by jaraco** [comment]
What version of entry points do you have installed?

**Comment by ignisf** [comment]
0.2.3

**Comment by ignisf** [comment]
Huh... It seems that I have inconsistencies in my site-packages directory. Will investigate.

**Comment by ignisf** [comment]
It seems that the reason was an incomplete update of the entrypoints package. Thank you for the tip!
