### ISSUE TITLE
Keyring error on Windows 10

### ISSUE THREAD

**Issue by oyvinrog** [jaraco/keyring#339]
I have never experienced issues using keyring on Windows before. 

However, on my new Windows 10 machine (Python 3.7.0), I get the following message when executing
"import keyring"

Should I install keyrings.alt instead? If so, how do I use it?

`RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.`

**Comment by jaraco** [comment]
That is odd and unexpected. We do run the tests against Windows on every PR and release, and it's been working on Windows 10 without fail.

You definitely don't want `keyrings.alt`. We should try to figure out what it is about your environment that is preventing the Windows backend from loading.

It could be that the `entry_points` aren't present, so none of the preferred backends are loaded. Or it might be that something is going wrong when loading the Windows backend.

First, can you try this and show what it emits:

```
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> import keyring
```

**Comment by oyvinrog** [comment]
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> import keyring
INFO:keyring.backend:Loading SecretService
INFO:keyring.backend:Loading kwallet
INFO:keyring.backend:Loading macOS
INFO:keyring.backend:Loading windows
ERROR:keyring.backend:Error initializing plugin EntryPoint('windows', 'keyring.backends.Windows', None, Distribution('keyring', '13.2.1')).
Traceback (most recent call last):
  File "C:\Users\Øyvind\AppData\Local\Programs\Python\Python37\lib\site-packages\keyring\backend.py", line 154, in _load_plugins
    init_func = ep.load()
  File "C:\Users\Øyvind\AppData\Local\Programs\Python\Python37\lib\site-packages\entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "C:\Users\Øyvind\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Øyvind\AppData\Local\Programs\Python\Python37\lib\site-packages\keyring\backends\Windows.py", line 12, in <module>
    from win32ctypes.pywin32 import pywintypes
  File "C:\Users\Øyvind\AppData\Local\Programs\Python\Python37\lib\site-packages\win32ctypes\pywin32\__init__.py", line 21, in <module>
    from win32ctypes.pywin32 import win32api
  File "C:\Users\Øyvind\AppData\Local\Programs\Python\Python37\lib\site-packages\win32ctypes\pywin32\win32api.py", line 23, in <module>
    from win32ctypes.core import _common, _kernel32, _backend
  File "C:\Users\Øyvind\AppData\Local\Programs\Python\Python37\lib\site-packages\win32ctypes\core\__init__.py", line 39, in <module>
    from .cffi import _advapi32, _common, _kernel32
  File "C:\Users\Øyvind\AppData\Local\Programs\Python\Python37\lib\site-packages\win32ctypes\core\cffi\_advapi32.py", line 198
    
    ^
SyntaxError: invalid syntax

**Comment by oyvinrog** [comment]
hmm.. note that this is a different error message than the one I got earlier

**Comment by oyvinrog** [comment]
tried to uninstall cffi and keyring and install all over again. Then I got this message:

>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> import keyring
>>> keyring.get_password("a","b")
Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    keyring.get_password("a","b")
  File "C:\Users\Øyvind\AppData\Local\Programs\Python\Python37\lib\site-packages\keyring\core.py", line 41, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "C:\Users\Øyvind\AppData\Local\Programs\Python\Python37\lib\site-packages\keyring\backends\fail.py", line 23, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.

**Comment by oyvinrog** [comment]
hi, I found a workaround for the issue. After rebooting my computer, I got the syntax error again. Then I stumble over this thread:

https://github.com/pyinstaller/pyinstaller/issues/3634

By editing _advapi32.py manually, and removing the blank spaces on line 134, I was able to execute keyring.get_password without any problems

**Comment by jaraco** [comment]
So the issue stems from https://github.com/enthought/pywin32-ctypes/issues/81 and is fixed in the master of that project. Easiest workaround is to `pip install git+https://github.com/enthought/pywin32-ctypes.git@f27d6a0` or to patch the 2to3 script as described in the upstream Python ticket and reinstall pywin32-ctypes. Nothing for keyring to do here.
