### ISSUE TITLE
importing keyring leads to ModuleNotFoundError

### ISSUE THREAD

**Issue by senarclens** [jaraco/keyring#341]
https://github.com/jaraco/keyring/commit/aefc2f63091244a7240564077b950c3825f1bbcd causes keyring to display a series of errors when imported

**reproduce (in python 3 venv)**
sudo pip install keyring
python
import keyring

**expected**
keyring imports, no errors displayed

**actual**
Error initializing plugin EntryPoint('Windows (alt)', 'keyrings.alt.Windows', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/keyring/backend.py", line 163, in _load_plugins
    init_func = ep.load()
  File "/usr/local/lib/python3.6/dist-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('file', 'keyrings.alt.file', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/keyring/backend.py", line 163, in _load_plugins
    init_func = ep.load()
  File "/usr/local/lib/python3.6/dist-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/file.py", line 11, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('pyfs', 'keyrings.alt.pyfs', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/keyring/backend.py", line 163, in _load_plugins
    init_func = ep.load()
  File "/usr/local/lib/python3.6/dist-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'

**note**
Maybe some old plugins needs to be adjusted
$ /usr/lib/python3/dist-packages/keyrings/alt$ grep escape *
file_base.py:from keyring.util.escape import escape as escape_for_ini
file_base.py:        service = escape_for_ini(service)
file_base.py:        username = escape_for_ini(username)
file_base.py:        return (escape_for_ini(service) + '\0' +
file_base.py:                escape_for_ini(username)).encode()
file_base.py:        service = escape_for_ini(service)
file_base.py:        key = escape_for_ini(key)
file_base.py:        service = escape_for_ini(service)
file_base.py:        username = escape_for_ini(username)
file.py:from keyring.util.escape import escape as escape_for_ini
file.py:                escape_for_ini('keyring-setting'),
file.py:                escape_for_ini('password reference'),
file.py:                escape_for_ini('keyring-setting'),
file.py:                escape_for_ini('scheme'),
file.py:                escape_for_ini('keyring-setting'),
file.py:                escape_for_ini('version'),
Google.py:                    file_contents.decode('string-escape')))
grep: __pycache__: Is a directory
pyfs.py:from keyring.util.escape import escape as escape_for_ini
pyfs.py:        service = escape_for_ini(service)
pyfs.py:        username = escape_for_ini(username)
pyfs.py:        service = escape_for_ini(service)
pyfs.py:        username = escape_for_ini(username)
pyfs.py:        service = escape_for_ini(service)
pyfs.py:        username = escape_for_ini(username)
_win_crypto.py:from keyring.util.escape import u

**Comment by mitya57** [comment]
It looks like you installed the latest version of keyring using pip, but also you have installed an older version of keyrings.alt using your distro's package manager. That old keyrings.alt is incompatible with new keyring.

My advice is using a virtualenv and *not* running pip using `sudo`.

**Comment by senarclens** [comment]
Thanks for the hint. Was working on a new vm w/ Xubuntu 18.04. I suppose they have python3-keyring installed by default.

**Comment by yarikoptic** [comment]
Since afaik there is no way to declare in setup.py that new version of keyring breaks older versions of keyrings.alt, such changes cause notable troubles ( https://bugs.launchpad.net/usd-importer/+bug/1794041, https://github.com/conda-forge/datalad-feedstock/pull/8#issuecomment-432494044) and it would be appreciated if such removals had longer deprecation cycle to guarantee that .alts packages catch up.
