### ISSUE TITLE
MacOS: "RuntimeError: No recommended backend was available." in executable

### ISSUE THREAD

**Issue by yanone** [jaraco/keyring#359]
Hi. I run my app from within Sublime Text, and password setting and retrieval with `keyring` works fine.
As soon as I bake the code into a Mac executable, I receive the following error:

```Traceback (most recent call last):
  File "wx/core.pyc", line 3240, in <lambda>
  File "/Users/yanone/Code/TypeWorldApp/dist/Type.World.app/Contents/Resources/app.py", line 711, in addSubscription_consumer
    success, message, publisher = delayedResult.get()
  File "wx/lib/delayedresult.pyc", line 232, in get
  File "wx/lib/delayedresult.pyc", line 267, in wrapper
  File "/Users/yanone/Code/TypeWorldApp/dist/Type.World.app/Contents/Resources/app.py", line 705, in addSubscription_worker
    success, message, publisher = self.client.addSubscription(url, username, password)
  File "typeWorldClient/__init__.pyc", line 379, in addSubscription
  File "typeWorldClient/__init__.pyc", line 620, in addJSONSubscription
  File "typeWorldClient/__init__.pyc", line 1366, in setSecretKey
  File "keyring/core.pyc", line 47, in set_password
  File "keyring/backends/fail.pyc", line 23, in get_password
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```

As per an older issue, I installed `secretstorage` and made sure that it's included in the app package.

The command `python3 -c "import keyring.backends.SecretService as SS; SS.Keyring.priority"` produces the following output:
```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/secretstorage/__init__.py", line 37, in dbus_init
    connection = connect_and_authenticate()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jeepney/integrate/blocking.py", line 70, in connect_and_authenticate
    bus_addr = get_bus(bus)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jeepney/bus.py", line 53, in get_bus
    return find_session_bus()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jeepney/bus.py", line 42, in find_session_bus
    addr = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'DBUS_SESSION_BUS_ADDRESS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keyring/backends/SecretService.py", line 37, in priority
    bus = secretstorage.dbus_init()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/secretstorage/__init__.py", line 43, in dbus_init
    raise SecretServiceNotAvailableException(reason) from ex
secretstorage.exceptions.SecretServiceNotAvailableException: Environment variable DBUS_SESSION_BUS_ADDRESS is unset

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keyring/util/properties.py", line 24, in __get__
    return self.fget.__get__(None, owner)()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keyring/backends/SecretService.py", line 41, in priority
    "Unable to initialize SecretService: %s" % e)
RuntimeError: Unable to initialize SecretService: Environment variable DBUS_SESSION_BUS_ADDRESS is unset
```

When I try to install `python-dbus` using `sudo pip3 install dbus-python`, I get the following error (which is not related to you, just mentioning it):
```
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-dvkv10_d/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-p0bh395k/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-dvkv10_d/dbus-python/
```

What to do?
Many thanks.

**Comment by jaraco** [comment]
Hi @yanone . 

On mac, you don't want to be working with secretstorage or dbus. Those are there to support Linux.

The issue you're having is with the backend discovery mechanism. Keyring uses [entrypoints](https://pypi.org/project/entrypoints) to discover backends advertised by itself and by third-party plugins.

Ideally, the tool you're using to embed keyring in an executable would work with entrypoints to ensure that entrypoints would work when keyring was embedded. Can you provide a little bit more information about the tools you're using to do that?

Since proper support for entrypoints in your bundler is unlikely to arrive quickly, a workaround would be to invoke this command somewhere in your program startup:

```
keyring.core.set_keyring(keyring.core.load_keyring('keyring.backends.OS_X.Keyring'))
```

Good luck.

**Comment by yanone** [comment]
Well, that worked, also for Windows using WinVaultKeyring (the app is cross-platform).
So thank you.
