### ISSUE TITLE
Cannot "import keyring" on Python 3.4 since version 16.1.0

### ISSUE THREAD

**Issue by dbaty** [jaraco/keyring#362]
Since the latest version (16.1.0), I cannot `import keyring` under Python 3.4. In a brand new virtual environment (and after an upgrade to the latest `setuptools` 40.6.2):

```bash
(venv) $ pip freeze | grep keyring
keyring==16.1.0
(venv) $ python
Python 3.4.2 (default, Sep 25 2018, 22:02:39) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyring
Error initializing plugin EntryPoint('chainer', 'keyring.backends.chainer', None, Distribution('keyring', '16.1.0')).
Traceback (most recent call last):
  File "/home/polyconseil/dbaty/venv/lib/python3.4/site-packages/keyring/backend.py", line 190, in _load_plugins
    init_func = ep.load()
  File "/home/polyconseil/dbaty/venv/lib/python3.4/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/polyconseil/dbaty/venv/lib/python3.4/site-packages/keyring/backends/chainer.py", line 9, in <module>
    from .. import core
ImportError: cannot import name 'core'
```

Funnily enough, if I try to import again in the same session, it works:

```pycon
>>> import keyring
>>> import keyring.backends.chainer
>>> keyring.backends.chainer.ChainerBackend()
<keyring.backends.chainer.ChainerBackend object at 0x7f09e4805390>
```

I am not sure I'll try to dig the root cause of the `ImportError`. In the meantime, here is a simple change that fixes the `ImportError`:

```diff
--- chainer.py.orig	2018-11-19 10:45:27.880273271 +0100
+++ chainer.py	2018-11-19 10:45:14.996936767 +0100
@@ -6,7 +6,7 @@
 from __future__ import absolute_import
 
 from .. import backend
-from .. import core
+from ..core import by_priority
 from ..util import properties
 
 
@@ -40,7 +40,7 @@
             if not isinstance(keyring, ChainerBackend)
             and keyring.priority > 0
         )
-        return sorted(allowed, key=core.by_priority, reverse=True)
+        return sorted(allowed, key=by_priority, reverse=True)
 
     def get_password(self, service, username):
         for keyring in self.backends:
```

**Comment by dbaty** [comment]
Well, actually, the root cause seems to be an import loop: when importing the `keyring` package, the `keyring.core` subpackage is imported and it runs `init_backend()`, which indirectly tries to import `keyring.backends.chainer` (because it's an entry point), which in turn tries to import `keyring.core`. We're back to step 1, looks like a loop. The partial import `from ..core import by_priority` seems to fix that (although I'm surprised it does) but that fix seems fragile.

**Comment by jaraco** [comment]
Confirmed - I see the same thing, but only on Python 3.4, not on Python 3.5.

```
~ $ python3.4 -m pip-run keyring -- -c 'import keyring'
Collecting keyring
  Using cached https://files.pythonhosted.org/packages/15/43/d97fe201586beca0a4bb24541f71036a16a7fc1d712e8eab850a7ede818f/keyring-16.1.0-py2.py3-none-any.whl
Collecting entrypoints (from keyring)
  Using cached https://files.pythonhosted.org/packages/cc/8b/4eefa9b47f1910b3d2081da67726b066e379b04ca897acfe9f92bac56147/entrypoints-0.2.3-py2.py3-none-any.whl
Installing collected packages: entrypoints, keyring
Successfully installed entrypoints-0.2.3 keyring-16.1.0
Error initializing plugin EntryPoint('chainer', 'keyring.backends.chainer', None, Distribution('keyring', '16.1.0')).
Traceback (most recent call last):
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-oafxxho9/keyring/backend.py", line 190, in _load_plugins
    init_func = ep.load()
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-oafxxho9/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-oafxxho9/keyring/backends/chainer.py", line 9, in <module>
    from .. import core
ImportError: cannot import name 'core'
```

**Comment by jaraco** [comment]
Should be fixed in 16.1.1, releasing now. Please re-open if not.

**Comment by teeberg** [comment]
Could you also release this to PyPI?

**Comment by jaraco** [comment]
Weird - I pushed the latest tag, but Travis never got it. I deleted and re-pushed the tag to remote and [it's building now](https://travis-ci.org/jaraco/keyring/builds/459556352). Thanks for letting me know the release was missing. It should show up shortly now.
