### ISSUE TITLE
TypeError bytes-like object is required when getting a passphrase

### ISSUE THREAD

**Issue by sloretz** [jaraco/keyring#377]
On Ubuntu bionic I get `TypeError: a bytes-like object is required, not 'list'` when trying to retrieve a passphrase.

Steps to reproduce

1. `python3 -m venv env`
1. `. env/bin/activate`
1. `pip install keyring`
1. `keyring set foo bar`
    * type `foobar` as the passphrase
1. `keyring get foo bar`

<details><summary>Output when I ran the above steps</summary>

```
sloretz@nxt:/tmp/keyring_bug$ python3 -m venv env
sloretz@nxt:/tmp/keyring_bug$ . env/bin/activate
(env) sloretz@nxt:/tmp/keyring_bug$ pip install keyring
Collecting keyring
  Using cached https://files.pythonhosted.org/packages/28/01/06f2e55264994a89d543ee37f2cfc4af85800824a8ca5c6532f715ff41a9/keyring-17.1.1-py2.py3-none-any.whl
Collecting entrypoints (from keyring)
  Using cached https://files.pythonhosted.org/packages/ac/c6/44694103f8c221443ee6b0041f69e2740d89a25641e62fb4f2ee568f2f9c/entrypoints-0.3-py2.py3-none-any.whl
Collecting secretstorage; sys_platform == "linux" and python_version >= "3.5" (from keyring)
  Using cached https://files.pythonhosted.org/packages/d8/e8/80975fd281764c80b2eb581a7f25d2109786e273b8925e8161bd2d06d10a/SecretStorage-3.1.0-py3-none-any.whl
Collecting jeepney (from secretstorage; sys_platform == "linux" and python_version >= "3.5"->keyring)
  Using cached https://files.pythonhosted.org/packages/2b/f7/ff23b9b59534f501d47c327576aadda59da5b83d76ff837e6075bc325b9f/jeepney-0.4-py3-none-any.whl
Collecting cryptography (from secretstorage; sys_platform == "linux" and python_version >= "3.5"->keyring)
  Using cached https://files.pythonhosted.org/packages/98/71/e632e222f34632e0527dd41799f7847305e701f38f512d81bdf96009bca4/cryptography-2.5-cp34-abi3-manylinux1_x86_64.whl
Collecting six>=1.4.1 (from cryptography->secretstorage; sys_platform == "linux" and python_version >= "3.5"->keyring)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography->secretstorage; sys_platform == "linux" and python_version >= "3.5"->keyring)
  Using cached https://files.pythonhosted.org/packages/6d/c0/47db8f624f3e4e2f3f27be03a93379d1ba16a1450a7b1aacfa0366e2c0dd/cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting asn1crypto>=0.21.0 (from cryptography->secretstorage; sys_platform == "linux" and python_version >= "3.5"->keyring)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography->secretstorage; sys_platform == "linux" and python_version >= "3.5"->keyring)
  Using cached https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz
Building wheels for collected packages: pycparser
  Running setup.py bdist_wheel for pycparser ... error
  Complete output from command /tmp/keyring_bug/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ko168_l4/pycparser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmptvrzx90apip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pycparser
  Running setup.py clean for pycparser
Failed to build pycparser
Installing collected packages: entrypoints, jeepney, six, pycparser, cffi, asn1crypto, cryptography, secretstorage, keyring
  Running setup.py install for pycparser ... done
Successfully installed asn1crypto-0.24.0 cffi-1.11.5 cryptography-2.5 entrypoints-0.3 jeepney-0.4 keyring-17.1.1 pycparser-2.19 secretstorage-3.1.0 six-1.12.0
(env) sloretz@nxt:/tmp/keyring_bug$ keyring set foo bar
Password for 'bar' in 'foo': 
(env) sloretz@nxt:/tmp/keyring_bug$ keyring get foo bar
Traceback (most recent call last):
  File "/tmp/keyring_bug/env/bin/keyring", line 11, in <module>
    sys.exit(main())
  File "/tmp/keyring_bug/env/lib/python3.6/site-packages/keyring/cli.py", line 130, in main
    return cli.run(argv)
  File "/tmp/keyring_bug/env/lib/python3.6/site-packages/keyring/cli.py", line 72, in run
    password = get_password(service, username)
  File "/tmp/keyring_bug/env/lib/python3.6/site-packages/keyring/core.py", line 57, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/tmp/keyring_bug/env/lib/python3.6/site-packages/keyring/backends/SecretService.py", line 72, in get_password
    return item.get_secret().decode('utf-8')
  File "/tmp/keyring_bug/env/lib/python3.6/site-packages/secretstorage/item.py", line 106, in get_secret
    padded_secret = decryptor.update(encrypted_secret) + decryptor.finalize()
  File "/tmp/keyring_bug/env/lib/python3.6/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/tmp/keyring_bug/env/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 124, in update
    n = self.update_into(data, buf)
  File "/tmp/keyring_bug/env/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 140, in update_into
    self._backend._ffi.from_buffer(data), len(data)
TypeError: a bytes-like object is required, not 'list'
```
</details>

<br/>
Backends

```
(env) sloretz@nxt:/tmp/keyring_bug$ keyring --list-backends
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.SecretService.Keyring (priority: 5)
keyring.backends.chainer.ChainerBackend (priority: 0)
```

**Comment by sloretz** [comment]
Duplicate of upstream issue mitya57/secretstorage#16

For anyone else facing the same issue, a workaround is to downgrade `cryptography`.

```
# Uninstall lastest version of cryptography
pip uinstall cryptography
# Install a version less than 2.5
pip install "cryptography<2.5"
# reinstall keyring
pip install keyring
```
