### ISSUE TITLE
Multiprocessing tests failing on Python 3.8 for Linux

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#410]
Following #281, in #409, I've started adding tests for multiprocessing, but [they're failing in Travis for Linux on Python 3.8](https://travis-ci.org/jaraco/keyring/jobs/619024100).

**Comment by jaraco** [comment]
I can see [from this build](https://travis-ci.org/jaraco/keyring/jobs/619023926) that sometimes the test fails on older Pythons too, and only intermittently.

**Comment by jaraco** [comment]
Following up on this, I notice the tests are [still xfailing in GHA](https://github.com/jaraco/keyring/runs/1596075736?check_suite_focus=true#step:5:47).

**Comment by jaraco** [comment]
The errors for easy reference:

```
root@944e35bc889f:/src# tox -- -k multiprocess --runxfail -p no:cov
WARNING: The wheel package is not available.
python develop-inst-noop: /src
python installed: appdirs==1.4.4,attrs==20.3.0,black==20.8b1,cffi==1.14.4,click==7.1.2,coverage==5.3.1,cryptography==3.3.1,docutils==0.16,filelock==3.0.12,flake8==3.8.4,iniconfig==1.1.1,jaraco.apt==2.0,jaraco.classes==3.1.0,jaraco.collections==3.0.0,jaraco.context==3.0.0,jaraco.functools==3.0.1,jaraco.test==4.0.1,jaraco.text==3.2.0,jeepney==0.6.0,-e git+gh://jaraco/keyring@892582e74fe245026305b2562735a4c7dddcece1#egg=keyring,mccabe==0.6.1,more-itertools==8.6.0,mypy==0.790,mypy-extensions==0.4.3,packaging==20.8,pathspec==0.8.1,pluggy==0.13.1,py==1.10.0,pycodestyle==2.6.0,pycparser==2.20,pyflakes==2.2.0,pyparsing==2.4.7,pytest==6.2.1,pytest-black==0.3.12,pytest-checkdocs==2.1.1,pytest-cov==2.10.1,pytest-flake8==1.0.7,pytest-mypy==0.8.0,pytz==2020.4,regex==2020.11.13,SecretStorage==3.3.0,six==1.15.0,tempora==4.0.1,toml==0.10.2,typed-ast==1.4.1,typing-extensions==3.7.4.3,yg.lockfile==2.3,zc.lockfile==2.0
python run-test-pre: PYTHONHASHSEED='1832835907'
python run-test: commands[0] | pytest -k multiprocess --runxfail -p no:cov
========================================================== test session starts ==========================================================
platform linux -- Python 3.9.0+, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
cachedir: .tox/python/.pytest_cache
rootdir: /src, configfile: pytest.ini
plugins: jaraco.test-4.0.1, black-0.3.12, checkdocs-2.1.1, flake8-1.0.7, mypy-0.8.0
collected 183 items / 178 deselected / 5 selected                                                                                       

tests/test_multiprocess.py .ssFF                                                                                                  [100%]

=============================================================== FAILURES ================================================================
_________________________________________________________ test_multiprocess_get _________________________________________________________

    def test_multiprocess_get():
        proc1 = multiprocessing.Process(target=subprocess_get)
        proc1.start()
        proc1.join()
>       assert proc1.exitcode == 0
E       AssertionError: assert 1 == 0
E        +  where 1 = <Process name='Process-1' pid=131 parent=130 stopped exitcode=1>.exitcode

tests/test_multiprocess.py:30: AssertionError
--------------------------------------------------------- Captured stderr call ----------------------------------------------------------
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/src/tests/test_multiprocess.py", line 11, in subprocess_get
    keyring.get_password('test_app', 'test_user')
  File "/src/keyring/core.py", line 55, in get_password
    return get_keyring().get_password(service_name, username)
  File "/src/keyring/backends/fail.py", line 25, in get_password
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
________________________________________________ test_multiprocess_get_after_native_get _________________________________________________

    @pytest.mark.skipif(
        # always skip as it crashes the interpreter
        sys.version_info < (3, 8) and platform.system() == 'Darwin',
        reason="#281: Prior to 3.8, multiprocess invocation fails",
    )
    def test_multiprocess_get_after_native_get():
>       keyring.get_password('test_app', 'test_user')

tests/test_multiprocess.py:39: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
keyring/core.py:55: in get_password
    return get_keyring().get_password(service_name, username)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <keyring.backends.fail.Keyring object at 0x7ffb8d06fc40>, service = 'test_app', username = 'test_user', password = None

    def get_password(self, service, username, password=None):
        msg = (
            "No recommended backend was available. Install a recommended 3rd "
            "party backend package; or, install the keyrings.alt package if "
            "you want to use the non-recommended backends. See "
            "https://pypi.org/project/keyring for details."
        )
>       raise NoKeyringError(msg)
E       keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.

keyring/backends/fail.py:25: NoKeyringError
================================================================= mypy ==================================================================
Success: no issues found in 1 source file
======================================================== short test summary info ========================================================
FAILED tests/test_multiprocess.py::test_multiprocess_get - AssertionError: assert 1 == 0
FAILED tests/test_multiprocess.py::test_multiprocess_get_after_native_get - keyring.errors.NoKeyringError: No recommended backend was ...
======================================== 2 failed, 1 passed, 2 skipped, 178 deselected in 14.40s ========================================
ERROR: InvocationError for command /src/.tox/python/bin/pytest -k multiprocess --runxfail -p no:cov (exited with code 1)
________________________________________________________________ summary ________________________________________________________________
ERROR:   python: commands failed
```

**Comment by jaraco** [comment]
Aha. The problem seems to be that the tests aren't doing anything special to enable any viable backends, so the tests just fail.
