### ISSUE TITLE
Error initializing plugin chainer = keyring.backends.chainer. after launch of opencobolide.

### ISSUE THREAD

**Issue by PaulGWolfson** [jaraco/keyring#433]
**Issue** 
Error initializing plugin chainer = keyring.backends.chainer. after launch of opencobolide.

**To Reproduce**
See error:

```
cat opencobolide.txt
Script started on 2020-04-22 16:59:04-04:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="96" LINES="32"]
which opencobolide
/usr/local/bin/opencobolide
python3 -m pip install --user --upgrade keyrings.alt
Requirement already up-to-date: keyrings.alt in /home/paul/.local/lib/python3.7/site-packages (3.4.0)
python3 -m pip list | grep keyring
keyring                21.2.0         
keyrings.alt            3.4.0          
keyring --list-backends
keyring.backends.kwallet.DBusKeyring (priority: 4.9)
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.chainer.ChainerBackend (priority: 10)
keyrings.alt.file.PlaintextKeyring (priority: 0.5)
keyring.backends.SecretService.Keyring (priority: 5)
keyrings.alt.file.EncryptedKeyring (priority: 0.6)
opencobolide
Error initializing plugin chainer = keyring.backends.chainer.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/extlibs/keyring/backend.py", line 155, in _load_plugins
    init_func = ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'keyring.backends.chainer'
17:01:05:354::INFO::3249::open_cobol_ide::version: 4.7.6
17:01:05:354::INFO::3249::open_cobol_ide.app::files to open: []
17:01:05:431::CRITICAL::3249::qcrash._hooks::unhandled exception:
  File "/usr/local/bin/opencobolide", line 11, in <module>
    load_entry_point('OpenCobolIDE==4.7.6', 'gui_scripts', 'opencobolide')()
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/main.py", line 33, in main
    app = Application()
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/app.py", line 82, in __init__
    self.win = MainWindow()
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/view/main_window.py", line 26, in __init__
    self.ui.setupUi(self)
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/view/forms/ide_ui.py", line 206, in setupUi
    self.consoleOutput = MyOutputWindow(self.tabProgramOutput)
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/view/widgets.py", line 200, in __init__
    super(MyOutputWindow, self).__init__(parent=parent, backend=backend_path)
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/extlibs/pyqode/core/widgets/output_window.py", line 131, in __init__
    self._init_code_edit(backend)
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/extlibs/pyqode/core/widgets/output_window.py", line 345, in _init_code_edit
    search_panel = panels.SearchAndReplacePanel()
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/extlibs/pyqode/core/panels/search_and_replace.py", line 133, in __init__
    self.setupUi(self)
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/extlibs/pyqode/core/_forms/search_panel_ui.py", line 152, in setupUi
    QtCore.QMetaObject.connectSlotsByName(SearchPanel)
Script started on 2020-04-22 16:59:04-04:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="96" >
which opencobolide
/usr/local/bin/opencobolide
pyt
SystemError: <built-in function connectSlotsByName> returned a result with an error set
17:01:05:431::CRITICAL::3249::open_cobol_ide.app::unhandled exception:
  File "/usr/local/bin/opencobolide", line 11, in <module>
    load_entry_point('OpenCobolIDE==4.7.6', 'gui_scripts', 'opencobolide')()
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/main.py", line 33, in main
    app = Application()
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/app.py", line 82, in __init__
    self.win = MainWindow()
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/view/main_window.py", line 26, in __init__
    self.ui.setupUi(self)
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/view/forms/ide_ui.py", line 206, in setupUi
    self.consoleOutput = MyOutputWindow(self.tabProgramOutput)
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/view/widgets.py", line 200, in __init__
    super(MyOutputWindow, self).__init__(parent=parent, backend=backend_path)
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/extlibs/pyqode/core/widgets/output_window.py", line 131, in __init__
    self._init_code_edit(backend)
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/extlibs/pyqode/core/widgets/output_window.py", line 345, in _init_code_edit
    search_panel = panels.SearchAndReplacePanel()
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/extlibs/pyqode/core/panels/search_and_replace.py", line 133, in __init__
    self.setupUi(self)
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/extlibs/pyqode/core/_forms/search_panel_ui.py", line 152, in setupUi
    QtCore.QMetaObject.connectSlotsByName(SearchPanel)

SystemError: <built-in function connectSlotsByName> returned a result with an error set
17:01:05:431::ERROR::3249::open_cobol_ide.app::exception in excepthook
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/open_cobol_ide/app.py", line 287, in _report_exception
    self.win, title, description,
AttributeError: 'Application' object has no attribute 'win'
exit

Script done on 2020-04-22 17:02:28-04:00 [COMMAND_EXIT_CODE="1"]
```

**Expected behavior**
OpenCobolIDE launches properly, e.g. works on Windows 10

**Environment**
python3

- OS: Linux 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
Error similar to github  "Cannot "import keyring" on Python 3.4 since version 16.1.0 #362"
	dbaty opened this issue on Nov 19, 2018 · 5 comments

**Comment by jaraco** [comment]
It seems the main error you have is `ModuleNotFoundError: No module named 'keyring.backends.chainer'`.

That means that your Python environment is corrupted. You somehow ended up with metadata for a version of Keyring since chainer was introduced (`16.0+`), but the code/implementation from an earlier version of keyring (`<16.0`)... either that or the relevant modules were omitted/deleted by some other process.

As you can see, if you `pip install` keyring, it has the `keyring.backends.chainer` module:

```
draft $ pip install -t out keyring
Collecting keyring
  Using cached keyring-21.2.0-py3-none-any.whl (30 kB)
Collecting importlib-metadata; python_version < "3.8"
  Using cached importlib_metadata-1.6.0-py2.py3-none-any.whl (30 kB)
Collecting zipp>=0.5
  Using cached zipp-3.1.0-py3-none-any.whl (4.9 kB)
Installing collected packages: zipp, importlib-metadata, keyring
Successfully installed importlib-metadata-1.6.0 keyring-21.2.0 zipp-3.1.0
draft $ ls out/keyring/backends
OS_X.py          Windows.py       __init__.py      chainer.py       kwallet.py
SecretService.py _OS_X_API.py     __pycache__      fail.py          null.py
```

Probably, you'll need to inspect the environment that's being created or break into the function and inspect the runtime environment when it crashes.

Probably you should reach out to your opencobolide user's group for support. Presumably you're not the only one with this issue. If they can identify something wrong with keyring, then raise _that_ issue with this project. As reported, there's not much I can do because the package works as intended.
