### ISSUE TITLE
Error accessing Windows Credential Manager in script compiled to exe by PyInstaller

### ISSUE THREAD

**Issue by oryandunn** [jaraco/keyring#439]
I created a simple demo script, which just prints out the username and password of a credential.  This works fine when run via python, but errors out when run after being compiled with PyInstaller.

Here's my test script, print_credential.py
```python
#!/usr/bin/env python

import sys
import keyring


def printCred(credName):
    #keyring.set_keyring(keyring.backends.Windows.WinVaultKeyring())
    cred = keyring.get_credential(credName, "")
    print(f"Username: {cred.username}")
    print(f"Password: {cred.password}")


if __name__ == '__main__':
    printCred(sys.argv[1])
```

When a test run:
```
~\Projects\python_class> py.exe .\print_credential.py "MyNewTestSystem"
Username: MyTestUser
Password: MyTestPassword
```

Compiled with PyInstaller:
```
~\Projects\python_class> pyinstaller --onefile print_credential.py
```
This creates the exe without error.

And run:
```
~\Projects\python_class> .\dist\print_credential.exe "MyNewTestSystem"
Traceback (most recent call last):
  File "print_credential.py", line 15, in <module>
    printCred(sys.argv[1])
  File "print_credential.py", line 9, in printCred
    cred = keyring.get_credential(credName, "")
  File "site-packages\keyring\core.py", line 74, in get_credential
  File "site-packages\keyring\backend.py", line 135, in get_credential
  File "site-packages\keyring\backends\fail.py", line 25, in get_password
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or
, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring
 for details.
[32620] Failed to execute script print_credential
```

I've tried running with the --hidden-import option, with win32ctypes, pywintypes, and win32cred, but nothing I tried got it working.  I tried forcefully setting the backend to windows, as can be seen in the commented out line in the script, but that didn't change anything.  Are there other includes or other options needed to make this work?

Edit: versions
```
~\Projects\python_class> python --version
Python 3.6.8

~\Projects\python_class> pip show keyring pyinstaller
Name: keyring
Version: 21.2.1
---
Name: PyInstaller
Version: 3.6
```

**Comment by oryandunn** [comment]
My google-fu was severely lacking when I opened this issue, as I've found these related items:
https://github.com/jaraco/keyring/issues/324
https://github.com/jaraco/keyring/pull/416
