### ISSUE TITLE
Keyring backend secretstorage not used on Ubuntu 16.04 with docker.

### ISSUE THREAD

**Issue by flenniken** [jaraco/keyring#441]
I followed the readme section "Using Keyring on Ubuntu 16.04" as best I could using docker.  The step "keyring.get_keyring()" returns the fail keyring not the secretstorage backend that I expect.  

I list the steps below.  Do you know why secretstorage backend does not show with get_keyring?

```
docker run -it ubuntu:16.04
apt update; apt install -y python3-venv libdbus-glib-1-dev python3-dev
cd /tmp
pyvenv py3
source py3/bin/activate
pip install -U pip
pip install dbus-python
pip install secretstorage
pip install keyring

(py3) root@206c8797e397:/tmp# python

Python 3.5.2 (default, Apr 16 2020, 17:47:17) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import keyring
>>> keyring.get_keyring()

<keyring.backends.fail.Keyring object at 0x7f1bcda67780>

>>> keyring.set_password("system", "username", "password")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/py3/lib/python3.5/site-packages/keyring/core.py", line 62, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/tmp/py3/lib/python3.5/site-packages/keyring/backends/fail.py", line 24, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
>>> 

(py3) root@206c8797e397:/tmp# pip freeze

cffi==1.14.0
cryptography==2.9.2
dbus-python==1.2.16
importlib-metadata==1.6.0
jeepney==0.4.3
keyring==20.0.1
pkg-resources==0.0.0
pycparser==2.20
SecretStorage==3.1.2
six==1.15.0
zipp==1.2.0
```

**Comment by mitya57** [comment]
Just having the SecretStorage client module installed is not enough, you also need a server process e.g. gnome-keyring.

Our README file has a [section](https://github.com/jaraco/keyring#using-keyring-on-headless-linux-systems) that can help you with this.

**Comment by jaraco** [comment]
Let us know if that doesn't solve the issue for you.
