### ISSUE TITLE
No module named 'keyring.backends.chainer'

### ISSUE THREAD

**Issue by patricegaofei** [jaraco/keyring#451]
**Describe the bug**
```
Error initializing plugin EntryPoint('chainer', 'keyring.backends.chainer', None, Distribution('~%yring', '18.0.0')).
Traceback (most recent call last):
  File "C:\Users\Patrice Gaofei\AppData\Roaming\Python\Python37\site-packages\keyring\backend.py", line 148, in _load_plugins
    init_func = ep.load()
  File "C:\ProgramData\Anaconda3\lib\site-packages\entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.chainer'
Error initializing plugin EntryPoint('chainer', 'keyring.backends.chainer', None, Distribution('~', 'yring-18.0.0')).
Traceback (most recent call last):
  File "C:\Users\Patrice Gaofei\AppData\Roaming\Python\Python37\site-packages\keyring\backend.py", line 148, in _load_plugins
    init_func = ep.load()
  File "C:\ProgramData\Anaconda3\lib\site-packages\entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.chainer'
Error initializing plugin EntryPoint('chainer', 'keyring.backends.chainer', None, Distribution('~.yring', '18.0.0')).
Traceback (most recent call last):
  File "C:\Users\Patrice Gaofei\AppData\Roaming\Python\Python37\site-packages\keyring\backend.py", line 148, in _load_plugins
    init_func = ep.load()
  File "C:\ProgramData\Anaconda3\lib\site-packages\entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.chainer'
Error initializing plugin EntryPoint('chainer', 'keyring.backends.chainer', None, Distribution('~0yring', '18.0.0')).
Traceback (most recent call last):
  File "C:\Users\Patrice Gaofei\AppData\Roaming\Python\Python37\site-packages\keyring\backend.py", line 148, in _load_plugins
    init_func = ep.load()
  File "C:\ProgramData\Anaconda3\lib\site-packages\entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.chainer'
Error initializing plugin EntryPoint('chainer', 'keyring.backends.chainer', None, Distribution('~=yring', '18.0.0')).
Traceback (most recent call last):
  File "C:\Users\Patrice Gaofei\AppData\Roaming\Python\Python37\site-packages\keyring\backend.py", line 148, in _load_plugins
    init_func = ep.load()
  File "C:\ProgramData\Anaconda3\lib\site-packages\entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.chainer'
Error initializing plugin EntryPoint('chainer', 'keyring.backends.chainer', None, Distribution('~eyring', '18.0.0')).
Traceback (most recent call last):
  File "C:\Users\Patrice Gaofei\AppData\Roaming\Python\Python37\site-packages\keyring\backend.py", line 148, in _load_plugins
    init_func = ep.load()
  File "C:\ProgramData\Anaconda3\lib\site-packages\entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.chainer'
Error initializing plugin EntryPoint('chainer', 'keyring.backends.chainer', None, Distribution('~~yring', '18.0.0')).
Traceback (most recent call last):
  File "C:\Users\Patrice Gaofei\AppData\Roaming\Python\Python37\site-packages\keyring\backend.py", line 148, in _load_plugins
    init_func = ep.load()
  File "C:\ProgramData\Anaconda3\lib\site-packages\entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.chainer'
```
**To Reproduce**
I am running a script based on synapseclient that aims at downloading the dataset for the MICCAI17_Endovis challenge. 
**Expected behavior**
I have successfully installed keyring on my computer. However, when I run my script, it gives me this error. I have searched online, but still could not find any solution to it. 

**Environment**

- OS: Windows 10

```
$ pip list | grep keyring
... keyring 12.0.2  because I have installed synapseclient 2.1.1
$ keyring --list-backends
...
```

**Additional context**
I cannot import keyring.backends.chainer

**Comment by jaraco** [comment]
It seems that something about your environment is corrupted. Notice the entry point that's been found:

`EntryPoint('chainer', 'keyring.backends.chainer', None, Distribution('~%yring', '18.0.0'))`

That tells me that something has taken an installation of `keyring==18.0.0` and mangled its metadata, renaming `keyring.dist-info` to `~%yring.dist-info`, but still `importlib.metadata` is detecting that as valid metadata and attempting to load plugins for it.

Later versions of keyring fail more gracefully (emitting a warning, but otherwise lenient to failing plugins).

Can you investigate and determine how one ends up with that mangled metadata directory?
