### ISSUE TITLE
Errors initializing plugin EntryPoints

### ISSUE THREAD

**Issue by dubiousjim** [jaraco/keyring#470]
**Describe the bug**
Importing keyring in Python 3.6.12 gives many "Error initializing plugin EntryPoint" messages.

**To Reproduce**
1. Install keyring using pip-3.6 into --user directory on Mac OS 10.15.6. (Python 3.6.12 and py36-pip @20.2.3 from MacPorts.)
2. Start python3.6 session.
3. `import keyring`
4. See error below.

**Expected behavior**
Import would succeed without error.

**Environment**

- OS: MacOS 10.15.6
- Python: 3.6.12

```
$ pip3.6 list --user | grep keyring
# many Errors, then...
keyring            21.4.0
keyrings.alt       3.5.2

$ ~/Library/Python/3.6/bin/keyring --list-backends
# Many Errors, then...
keyrings.alt.file.PlaintextKeyring (priority: 0.5)
keyring.backends.chainer.ChainerBackend (priority: 10)
keyring.backends.OS_X.Keyring (priority: 5)
keyring.backends.fail.Keyring (priority: 0)
keyrings.alt.file.EncryptedKeyring (priority: 0.6)
```

**Additional context**
Here are the Errors I get:

```
Error initializing plugin EntryPoint(name='kwallet', value='keyring.backends.kwallet', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='secretservice', value='keyring.backends.SecretService', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='windows', value='keyring.backends.Windows', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='chainer', value='keyring.backends.chainer', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='macos', value='keyring.backends.OS_X', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='gnome', value='keyrings.alt.Gnome', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='google', value='keyrings.alt.Google', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='windows (alt)', value='keyrings.alt.Windows', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='file', value='keyrings.alt.file', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='keyczar', value='keyrings.alt.keyczar', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='multi', value='keyrings.alt.multi', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
Error initializing plugin EntryPoint(name='pyfs', value='keyrings.alt.pyfs', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Users/jim/Library/Python/3.6/lib/python/site-packages/importlib_metadata/api.py", line 67, in load
    attrs = filter(None, match.group('attr').split('.'))
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by jaraco** [comment]
It looks to me like you're somehow getting `keyrings.alt`, perhaps in system site-packages or user site-packages. 

Unfortunately, I don't get the same error or experience as you do:

```
draft $ python3.6 -m pip install --user keyring
Collecting keyring
  Using cached keyring-21.4.0-py3-none-any.whl (31 kB)
Collecting importlib-metadata
  Using cached importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting zipp>=0.5
  Using cached zipp-3.4.0-py3-none-any.whl (5.2 kB)
Installing collected packages: zipp, importlib-metadata, keyring
Successfully installed importlib-metadata-2.0.0 keyring-21.4.0 zipp-3.4.0
draft $ python3.6 -m keyring --list-backends
keyring.backends.chainer.ChainerBackend (priority: -1)
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.OS_X.Keyring (priority: 5)
```

My guess is there's a bug elsewhere in your environment. I'd make sure you have the latest `importlib_metadata` installed and also uninstall `keyrings.alt`.
