### ISSUE TITLE
ModuleNotFoundError: No module named 'keyrings' at import

### ISSUE THREAD

**Issue by azmeuk** [jaraco/keyring#475]
**Describe the bug**
A simple import of `keyring` raises the following exception.
Just everything based on keyring seems to be broken. 
I cannot remember doing anything special that could corrupt my system. Apart of this, everything pythonic goes fine.

```python
python
Python 3.8.6 (default, Sep 30 2020, 04:00:38)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyring
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/keyring/__init__.py", line 1, in <module>
    from .core import (
  File "/usr/lib/python3.8/site-packages/keyring/core.py", line 186, in <module>
    init_backend()
  File "/usr/lib/python3.8/site-packages/keyring/core.py", line 87, in init_backend
    or load_config()
  File "/usr/lib/python3.8/site-packages/keyring/core.py", line 173, in load_config
    return load_keyring(keyring_name)
  File "/usr/lib/python3.8/site-packages/keyring/core.py", line 130, in load_keyring
    class_ = _load_keyring_class(keyring_name)
  File "/usr/lib/python3.8/site-packages/keyring/core.py", line 120, in _load_keyring_class
    __import__(module_name)
ModuleNotFoundError: No module named 'keyrings'
```

**To Reproduce**
```import keyring```

**Expected behavior**
A silent and successful import :)

**Environment**

- OS: Archlinux

```
$ pip list | grep keyring
keyring                       21.5.0

$ keyring --list-backends
Traceback (most recent call last):
  File "/usr/bin/keyring", line 33, in <module>
    sys.exit(load_entry_point('keyring==21.5.0', 'console_scripts', 'keyring')())
  File "/usr/bin/keyring", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/keyring/__init__.py", line 1, in <module>
    from .core import (
  File "/usr/lib/python3.8/site-packages/keyring/core.py", line 186, in <module>
    init_backend()
  File "/usr/lib/python3.8/site-packages/keyring/core.py", line 87, in init_backend
    or load_config()
  File "/usr/lib/python3.8/site-packages/keyring/core.py", line 173, in load_config
    return load_keyring(keyring_name)
  File "/usr/lib/python3.8/site-packages/keyring/core.py", line 130, in load_keyring
    class_ = _load_keyring_class(keyring_name)
  File "/usr/lib/python3.8/site-packages/keyring/core.py", line 120, in _load_keyring_class
    __import__(module_name)
ModuleNotFoundError: No module named 'keyrings'

$ pacman -Ss keyring
core/archlinux-keyring 20201028-1 [installed]
    Arch Linux PGP keyring
extra/gnome-keyring 1:3.36.0-1 (gnome) [installed]
    Stores passwords and encryption keys
extra/libgnome-keyring 3.12.0+13+g4f8ab73-3 [installed]
    GNOME keyring client library (deprecated)
community/debian-archive-keyring 2019.1-2
    GnuPG archive keys of the Debian archive
community/deepin-polkit-agent-ext-gnomekeyring 0.1.0-2 (deepin)
    GNOME keyring extension for dde-polkit-agent
community/jetring 0.27-2
    gpg keyring maintenance using changesets
community/python-keyring 21.5.0-1 [installed]
    Store and access your passwords safely
community/python-keyrings-alt 1:4.0.1-1
    Alternate keyring implementations
community/ubuntu-keyring 2020.06.17.1-1
    GnuPG keys of the Ubuntu archive
```

**Comment by mitya57** [comment]
Hi! The error happens in `load_config` function. This indicates that you probably have a [configuration file] and it specifies a backend that comes from [keyrings.alt] module. Can you check if that is the case?

[configuration file]: https://github.com/jaraco/keyring/blob/master/README.rst#configuring
[keyrings.alt]: https://github.com/jaraco/keyrings.alt

**Comment by azmeuk** [comment]
Yep. I had this in my configuration file:

```
[backend]
default-keyring=keyrings.alt.Gnome.Keyring
```

Deleting this configuration file solves the issue.
