### ISSUE TITLE
Not working on Raspberry Pi OS without `keyrings.alt` package

### ISSUE THREAD

**Issue by xilopaint** [jaraco/keyring#506]
**Describe the bug**
I've installed keyring in a virtualenv using pipenv but it doesn't work on Raspberry Pi OS through SSH unless I install the `keyrings.alt` package. Isn't there a default/built-in backend on RasPiOS?

**To Reproduce**
```
$ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyring
>>> keyring.set_password("system", "username", "password")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/share/virtualenvs/info2000-5dqwVeM-/lib/python3.7/site-packages/keyring/core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/home/pi/.local/share/virtualenvs/info2000-5dqwVeM-/lib/python3.7/site-packages/keyring/backends/fail.py", line 25, in get_password
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
>>>
```
**Expected behavior**
Password should be set.

**Environment**
```
$ uname -a
Linux raspberrypi 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux
$ pip list | grep keyring
keyring                       23.0.1
$ keyring --list-backends
keyring.backends.chainer.ChainerBackend (priority: -1)
keyring.backends.fail.Keyring (priority: 0)
```

**Comment by xilopaint** [comment]
Btw, where does `keyrings.alt` save the passwords?

**Comment by xilopaint** [comment]
Well, it works by installing gnome-keyring, but still needs a GUI for unlocking the keyring which is not ideal while accessing the server via SSH. I'm closing the issue and will look for an alternative to keyring.
