### ISSUE TITLE
ModuleNotFoundError: No module named 'keyring.backends.macOS

### ISSUE THREAD

**Issue by kapilt** [jaraco/keyring#511]
**Describe the bug**

try to use any app that uses keyring on a non osx machine and get greeted by import errors 

**To Reproduce**

i happen to be using poetry, which use kerying.. doing any poetry command results in

```
$ poetry install
Error initializing plugin EntryPoint(name='macOS', value='keyring.backends.macOS', group='keyring.backends').
Traceback (most recent call last):
  File "/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backend.py", line 202, in _load_plugins
    init_func = ep.load()
  File "/home/kapilt/.pyenv/versions/3.9.4/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/kapilt/.pyenv/versions/3.9.4/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.macOS'
```

behavior is the same with either stdlib or pypi importlib.

poetry is vendoring keyring in this context

afaics keyring should be catching on missing modules when loading entrypoints

**Expected behavior**

don't throw errors for backend modules that aren't importable

**Environment**

- linux

```
❯ python -m keyring.cli --list-backends
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.SecretService.Keyring (priority: 5)
keyring.backends.chainer.ChainerBackend (priority: -1)

```

**Comment by kapilt** [comment]
more users with the same issue https://github.com/python-poetry/poetry/issues/3662  and a quick google shows its not specific to poetry

**Comment by selesnow** [comment]
I have same issue

ModuleNotFoundError: No module named 'keyring.backends.macOS' on Windows

**Comment by selesnow** [comment]
I solved this over system variables:
`PYTHON_KEYRING_BACKEND=keyring.backends.Windows.WinVaultKeyring`

**Comment by jaraco** [comment]
Hey Kapil!

Keyring packages `keyrings.backends.macOS` unconditionally. I suspect poetry by vendoring keyring is somehow breaking that assumption. Taking poetry out of the equation, the project works fine on Linux and Windows, so I'd expect it to work under poetry too.

Indeed, I'm not even able to replicate the issue:

```
keyring main $ docker run -it jaraco/multipy-tox pip-run -q poetry -- -m poetry install

  RuntimeError

  Poetry could not find a pyproject.toml file in / or its parents

  at /tmp/pip-run-tzj36a6p/poetry/core/factory.py:369 in locate
      365│             if poetry_file.exists():
      366│                 return poetry_file
      367│ 
      368│         else:
    → 369│             raise RuntimeError(
      370│                 "Poetry could not find a pyproject.toml file in {} or its parents".format(
      371│                     cwd
      372│                 )
      373│             )
```

Of course, there may be other factors needed to replicate the issue (such as a working directory with a project in it).

**Comment by kapilt** [comment]
the poetry vendoring (note this is using their installer not pip install poetry) is preserving the plugin, its just taking the dist, and it is adding it to pythonpath (no import name changes). its a little unclear to me why it would be importable but not find entrypoints.

```
❯ find ~/.poetry/lib/poetry/_vendor/py3.9/keyring
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/devpi_client.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/core.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/cli.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/errors.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/http.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/testing
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/testing/util.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/testing/backend.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/testing/__init__.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backend.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/__pycache__
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/__pycache__/core.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/__pycache__/backend.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/__pycache__/credentials.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/__pycache__/errors.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/__pycache__/__init__.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/py.typed
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/null.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/kwallet.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/__pycache__
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/__pycache__/_OS_X_API.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/__pycache__/Windows.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/__pycache__/fail.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/__pycache__/kwallet.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/__pycache__/__init__.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/__pycache__/SecretService.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/__pycache__/OS_X.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/__pycache__/chainer.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/Windows.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/_OS_X_API.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/chainer.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/SecretService.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/fail.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/OS_X.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/backends/__init__.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/util
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/util/properties.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/util/__pycache__
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/util/__pycache__/properties.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/util/__pycache__/platform_.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/util/__pycache__/__init__.cpython-39.pyc
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/util/platform_.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/util/__init__.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/__main__.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/credentials.py
/home/kapilt/.poetry/lib/poetry/_vendor/py3.9/keyring/__init__.py
```

**Comment by jaraco** [comment]
Can you provide steps that would help me replicate the error?

**Comment by kapilt** [comment]
i think this is closable, i think poetry was doing a non standard setup at the time which i think caused issue with the plugin lookup error in keyring, that's since resolved since they moved to a virtualenv for installs on their default recommended installation path.
