### ISSUE TITLE
breaks gtk3 applications

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#52]
keyring imports the gnomekeyring module, which uses gtk2. 

This breaks any Gtk3 applications in which it is loaded. 

```
#!python

Python 2.7.2+ (default, Oct  4 2011, 20:06:09) 
[GCC 4.6.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyring
>>> from gi.repository import GOBject
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 23, in <module>
    from ._gi import _API, Repository
ImportError: could not import gobject (error was: ImportError('When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject".',))
```

I'm not sure what the best solution is to work around this - it seems pretty hard to determine if the current application is a gtk2 or gtk3 app, especially if keyring is imported before Gtk. It would be nice if there was at least some way of disabling the GNOME backend for keyring, so applications that are aware of this issue can work around it.

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/52
- Originally reported by: Jelmer Vernooij
- Originally created at: 2011-11-03T16:26:03.189

**Comment by jaraco** [comment]
It would probably make sense for keyring to check for the "SecretService" D-Bus interface first, which is provided by newer versions of GNOME and KDE (http://standards.freedesktop.org/secret-service/index.html)

---

Original comment by: Jelmer Vernooij

**Comment by jaraco** [comment]
The problem currently, is that keyring initializes all the backends when first imported, and select the best supported one. This is nice since the module is then straightforward to use, but can be a pain when you explicitly don't want default behaviors.

One could think that the SecretService interface is "more" supported than gomekeyring, but that's non-trivial to implement in the current code, and I fear it's going to import gnomekeyring anyway.

We can provide a GIR-based backend which superseeds the Gnomekeyring backend if it's available, but so, what about Gtk2 applications?

---

Original comment by: Jonathan Ballet

**Comment by jaraco** [comment]
If the secret service interface is present, it should always work - regardless of if it's used in a Gtk2, Gtk3 or KDE application. It doesn't use GIR - just plain dbus - so it can be loaded together with pygtk2.

It indeed looks like the selection mechanism will have to become a bit more complicated. :-( Perhaps the simplest thing to do would be to check the backends in a particular order (SecretServiceKeyring before GNOMEKeyring/KDEWallet) and stop when one of them returns 1. If none does it can still use the current mechanism. Would that be reasonable enough?

---

Original comment by: Jelmer Vernooij

**Comment by jaraco** [comment]
I guess it would work, but that's quite ad-hoc while things are currently generic enough.
If you would like to propose a patch to implement your proposition, we can discuss around it, others feedbacks would be welcome as well.

---

Original comment by: Jonathan Ballet

**Comment by jaraco** [comment]
Fixed in [[https://bitbucket.org/kang/python-keyring-lib/changeset/0959e8cd607c|0959e8cd607c]]

---

Original comment by: Jason R. Coombs
