### ISSUE TITLE
Weird behavior from get_password on Windows with the username None and cffi installed

### ISSUE THREAD

**Issue by BenjaminHamon** [jaraco/keyring#524]
When using keyring on Windows, with the default backend (the credential manager), if you try to retrieve a password with get_password and use the username value None, the result is normally the stored password. If cffi is installed, the function returns None instead. And trying to use set_password then raises an exception.

While testing further, I noticed even weirder stuff: uninstalling cffi, setting a password again, installing cffi back, then get_password returns the _old_ password. This seems to result from several calls to set_password creating several entries (one with the username and @, one without) and None being used as the string "None".

The issue happens specifically with the username value None, not with a normal string. Maybe this value should simply be forbidden? I don't believe it is possible to pass None with the keyring program, and the Windows credential manager GUI requires a non-empty username. But it is at least possible to set one with keyring set_password as well as through Ansible win_credential module. None is also not supported by at least the file backend, as far as I know.

I am unaware of what cffi does exactly, in my experience it comes as a dependency to cryptography.

### To reproduce:

Install keyring
```
> python -m pip install keyring
Successfully installed importlib-metadata-4.6.4 keyring-23.1.0 pywin32-ctypes-0.2.0 zipp-3.5.0
```

Set a password with the username value None and check it is set correctly (this creates an entry `KeyringTest` in the credential manager)
```
> python -c "import keyring; keyring.set_password('KeyringTest', None, 'password')"
> python -c "import keyring; print(keyring.get_password('KeyringTest', None))"
password
```

Install cffi
```
> python -m pip install cffi
Successfully installed cffi-1.14.6 pycparser-2.20
```

Try to get the password again and notice it returns None
```
> python -c "import keyring; print(keyring.get_password('KeyringTest', None))"
None
```

Try to set the password and notice it raises an exception (this creates an entry `@KeyringTest` in the credential manager anyway)
```
> python -c "import keyring; keyring.set_password('KeyringTest', None, 'password')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Temporary\KeyringTest\.venv\lib\site-packages\keyring\core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "D:\Temporary\KeyringTest\.venv\lib\site-packages\keyring\backends\Windows.py", line 131, in set_password
    self._set_password(service, username, str(password))
  File "D:\Temporary\KeyringTest\.venv\lib\site-packages\keyring\backends\Windows.py", line 142, in _set_password
    win32cred.CredWrite(credential, 0)
  File "D:\Temporary\KeyringTest\.venv\lib\site-packages\win32ctypes\pywin32\win32cred.py", line 34, in CredWrite
    c_creds = _authentication.CREDENTIAL.fromdict(Credential, Flags)
  File "D:\Temporary\KeyringTest\.venv\lib\site-packages\win32ctypes\core\cffi\_authentication.py", line 105, in fromdict
    blob = make_unicode(credential[key])
  File "D:\Temporary\KeyringTest\.venv\lib\site-packages\win32ctypes\core\cffi\_authentication.py", line 72, in make_unicode
    return password.decode(encoding=str(code_page), errors='strict')
AttributeError: 'NoneType' object has no attribute 'decode'
```

Uninstall cffi
```
> python -m pip uninstall cffi
Successfully uninstalled cffi-1.14.6
```

Try to get the password again and notice it returns the expected value
```
> python -c "import keyring; print(keyring.get_password('KeyringTest', None))"
password
```

Set a new password (there are now two three entries in the credential manager: `KeyringTest`, `@KeyringTest`, `None@KeyringTest`).
```
> python -c "import keyring; keyring.set_password('KeyringTest', None, 'newpassword')"
> python -c "import keyring; print(keyring.get_password('KeyringTest', 'None'))"
password
> python -c "import keyring; print(keyring.get_password('KeyringTest', None))"
newpassword
```

Install cffi again
```
> python -m pip install cffi
Successfully installed cffi-1.14.6
```

Try to get the password again and notice it returns the old value
```
> python -c "import keyring; print(keyring.get_password('KeyringTest', None))"
password
> python -c "import keyring; print(keyring.get_password('KeyringTest', 'None'))"
password
```

**Comment by jaraco** [comment]
Thanks for the report.

The fact that the behavior varies based on the presence of CFFI is likely an upstream issue with [enthought/pywin32-ctypes](https://github.com/enthought/pywin32-ctypes), which [prefers the cffi implementation if available](https://github.com/enthought/pywin32-ctypes/blob/28364ce0ac0d52dda3e4b46d568cd7fab3697074/win32ctypes/core/__init__.py#L15-L21).

Ideally, that project would provide consistent results irrespective of the backend implementation.

Would you be interested in distilling a repro using only win32cred that captures the divergent behavior and report it to that project?

> Maybe this value should simply be forbidden?

Yes, perhaps. A quick scan of the tests indicates that accepting `None` values isn't tested. So if it happens to work, that's not intentionally supported.

But I'd like to reflect. It may make sense for keyring to support null usernames, especially if backends support it.

Your findings above are complicated by the fact that the Windows backend attempts to [resave previous credentials for a different username](https://github.com/jaraco/keyring/blob/17ea87992227d6ffd29e837773073ae2819536b4/keyring/backends/Windows.py#L123-L130) when there's a collision on service name. It's a shame the Credential Vault requires the user to come up with unique TargetNames for each credential.

----

My preference would be to focus on fixing the upstream issue first and then see if any follow-up work would be required in keyring.

**Comment by jaraco** [comment]
This issue appears to have been fixed upstream.
