### ISSUE TITLE
WSL2+Debian: keyring.errors.NoKeyringError: No recommended backend was available.

### ISSUE THREAD

**Issue by topout** [jaraco/keyring#566]
**Describe the bug**
I get the below error:
```
Traceback (most recent call last):
  File "/usr/bin/keyring", line 11, in <module>
    load_entry_point('keyring==18.0.1', 'console_scripts', 'keyring')()
  File "/usr/lib/python3/dist-packages/keyring/cli.py", line 130, in main
    return cli.run(argv)
  File "/usr/lib/python3/dist-packages/keyring/cli.py", line 82, in run
    set_password(service, username, password)
  File "/usr/lib/python3/dist-packages/keyring/core.py", line 63, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/lib/python3/dist-packages/keyring/backends/fail.py", line 25, in get_password
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
```

**To Reproduce**

Installed Keyring on WSL2
Installed dbus-python on WSL2

I then ran the following code to type password. After I try to set the password, I get the above error.

```
keyring set system username
Password for 'username' in 'system': 
```

**Environment**
Windows 10 WSL2
Ubuntu 20.04.3 LTS 

**Additional context**
I have tried the a couple of the 3rd party backends including keyrings.alt but this does not fix the problem.

**Comment by michjnich** [comment]
I'm having a similar issue. 

What is the recommended procedure for getting this working under WSL2? I can't find anything specific in the docs. Getting keychains set up seems to be problematic. I got funtoo working (I think), but it doesn't seem like it's compatible with keyring.

**Comment by zpeng01** [comment]
I use the command solve the issue: pip install keyring.alt

**Comment by jaraco** [comment]
The reported error indicates that none of the recommended backends were discovered or accessible to keyring.

The problem with accessing a credential store on WSL is that you're using Linux on a Windows device, so the usual platform assumptions don't apply. It doesn't help that Linux doesn't have a built-in credential store, so also has some somewhat onerous prerequisites to get a usable credential store configured.

I'm unfamiliar with WSL, but if I assume that WSL doesn't provide any access to the Windows APIs, then the only way to access a credential store using WSL will be through Linux interfaces. For those, there are two recommended interfaces, one using secretstorage and another using dbus.

What I'd recommend is to research answers to the following:

- Are Windows APIs (such as CredentialVault) available on WSL?
- Does secretstorage work on WSL, and if so how does one configure it to work under WSL?
- Is it possible to install and configure dbus for WSL? The [headless linux guidance](https://github.com/jaraco/keyring#using-keyring-on-headless-linux-systems) may provide some hints here.

I hope that helps.

**Comment by marcandrevigneault** [comment]
+1
happens for me on my mac with M1. It seems he doesn't find the backend, but it exists.
The fix was to use `pip install keyrings.alt` so it installs an alternative backend, but I can't see the entered password on the keychain, it seems independent from the system keychain, which is annoying.

**Comment by chesucr** [comment]
I am on this issue as well. I tried to follow the guidance that @jaraco points out in his comment, without any result. I [asked on SO](https://stackoverflow.com/questions/72528100/how-to-unlock-gnome-keyring-on-debian-headless-wsl-2-and-make-it-work-in-pytho) with all the details if you want to take a look, trying to get more attention. What I don't know is if this will work directly on a Debian distro, not under WSL2. Has anybody tried it?

**Edit**: Well, I can confirm that in a virtual machine on Debian 11.3 works fine. So it must be something to do with WSL 2

**Edit 2**: Some login processes are missing on WSL 2, might that be the problem?

**Comment by chesucr** [comment]
Oh, I got an answer in my Stackoverflow question. It seems that I have added the password with echo and by default adds a newline to the password. I needed to restart the keyring and add the `-n` flag to `echo`

    echo -n 'db' | gnome-keyring-daemon --unlock

It works now

So the complete script to make it work in Debian and WSL2 would be something like this:

	sudo apt install gnome-keyring

    dbus-run-session -- bash --noprofile --norc
    # remove previous keyrings
    rm -rf ~/.local/share/keyrings
    echo -n 'db' | gnome-keyring-daemon --unlock

    python3 -m venv env
    . env/bin/activate
    pip install keyring
    python3 -m keyring set system username
    # Will prompt for the secret
    python3 -m keyring get system username
    # Should return the secret

**Comment by jaraco** [comment]
Would someone consider putting together a PR to the README that would help address this issue for future WSL2 users?

**Comment by AndreyNikiforov** [comment]
[solved](https://github.com/AndreyNikiforov/keyring_test) same/similar issue by using `pyinstaller --collect-all keyrings.alt --hidden-import pkgutil`

**Comment by sbor23** [comment]
Just letting you know, as of now with WSL2 and a recent Windows 10 with last Feature update that enables `systemd`, the following "just works" when using the Ubuntu-22.04 distro:

```
# install gnome-keyring
sudo apt update && sudo apt install gnome-keyring

# add lines to .bashrc
echo '# wait for systemd --user dbus session and unlock keyring' >> ~/.bashrc
echo 'sleep 1' >> ~/.bashrc
echo 'eval $(echo -n db | gnome-keyring-daemon --unlock --replace 2> /dev/null)' >> ~/.bashrc

# reboot
```

**Comment by ilpianista** [comment]
FYI I was looking for a method to store poetry secrets, running in WSL, on Windows Credential Service and I ended up with [this](https://github.com/ilpianista/keyring_wincred).
