### ISSUE TITLE
No recommended backend was available.

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#568]
+1
happens for me on my mac with M1. It seems he doesn't find the backend, but it exists.
The fix was to use `pip install keyrings.alt` so it installs an alternative backend, but I can't see the entered password on the keychain, it seems independent from the system keychain, which is annoying.

_Originally posted by @PyMarc2 in https://github.com/jaraco/keyring/issues/566#issuecomment-1087915367_

**Comment by jaraco** [comment]
@PyMarc2 Although you encountered the same error message, that message can happen any time you don't have a viable backend. The issue reported in the other issue is due to issues on Windows Subsystem for Linux (WSL), so probably not relevant to your ARM-based mac, so I've opened up a separate issue.

**Comment by jaraco** [comment]
I also have an M1 mac, but everything works correctly. What version of Python are you running? Proper support for ARM-based macs wasn't added until Python 3.8.10 or so, and the underlying backend will be broken and thus unavailable. See #525 and #529.



> The fix was to use `pip install keyrings.alt` so it installs an alternative backend, but I can't see the entered password on the keychain, it seems independent from the system keychain, which is annoying.

Although installing `keyrings.alt` will stop the error message from happening, it's not doing what you want. Since the default keychain-backed backend isn't available, installing `keyrings.alt` enables another backend, a plain text file system backend that will store your passwords in plain text on your hard drive. That's why you don't see the passwords in the keychain and why it's probably not what you want.

**Comment by marcandrevigneault** [comment]
I'm using `python 3.9.5` with 
When I try to add a password with the command `keyring set "system" "username"`
it returns the following error come:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/keyring", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keyring/cli.py", line 132, in main
    return cli.run(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keyring/cli.py", line 68, in run
    return method()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keyring/cli.py", line 85, in do_set
    set_password(self.service, self.username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keyring/core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/keyring/backends/fail.py", line 25, in get_password
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
```

**Comment by jaraco** [comment]
Unfortunately, the error message "No recommended backend was available" only tells us that when it tried to detect the macOS backend, it failed to do so.

Can you troubleshoot in your environment by inputting these into a Python interpreter?

```
>>> from keyring.backends.macOS import Keyring
>>> Keyring.priority
5
>>> from keyring.backends.macOS import api
```

I suspect you'll get different output than I did on my M1 mac.

**Comment by hsperr** [comment]
I encountered a similar issue when installing keyring on the system of a friend. (On my M1 Pro it works, on his M1 macbook, I am not sure right now which one it is it doesn't)

I got the same error as PyMarc2 mentioned. After digging around I found in a related stackoverflow post that we should explicitly set the backend. After adding

```
keyring.core.set_keyring(keyring.core.load_keyring('keyring.backends.OS_X.Keyring'))
```

to the code I receive this error:

```
  File "/opt/miniconda3/lib/python3.9/site-packages/keyring/backends/macOS/init.py", line 32, in priority
    raise RuntimeError("Security API unavailable")
RuntimeError: Security API unavailable
```

Unfortunately I think the relevant error is suppressed here:
https://github.com/jaraco/keyring/blob/977ed03677bb0602b91f005461ef3dddf01a49f6/keyring/backends/macOS/__init__.py#L14

I will try to print the error on my friends install and see what I can get

**Comment by jaraco** [comment]
> Unfortunately I think the relevant error is suppressed here:

The error is intentionally suppressed because that import is known to fail on other platforms. On macOS, however, that import should succeed.

You'll want to do as recommended above and run the troubleshooting steps to help elicit the underlying failure.


> ```
> >>> from keyring.backends.macOS import Keyring
> >>> Keyring.priority
> 5
> >>> from keyring.backends.macOS import api
> ```

**Comment by hsperr** [comment]
As I mentioned the whole thing is remote, and he is currently traveling but I had him execute this line:

```
from keyring.backends.macOS import api
```

Trace:
```
Traceback (most recent call last):
  File "/Users/------/Documents/nannuoshan/Codes/nannoushan/src/keyring_inserter.py", line 4, in <module>
    from keyring.backends.macOS import api
  File "/opt/miniconda3/lib/python3.9/site-packages/keyring/backends/macOS/api.py", line 45, in <module>
    SecItemAdd = _sec.SecItemAdd
  File "/opt/miniconda3/lib/python3.9/ctypes/init.py", line 395, in getattr
    func = self.getitem(name)
  File "/opt/miniconda3/lib/python3.9/ctypes/init.py", line 400, in getitem
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, SecItemAdd): symbol not found
```

**Comment by jaraco** [comment]
That's interesting. That error indicates that `_sec.SecItemAdd` doesn't exist... like the framework libraries are missing core interfaces supplied by Apple. The error appears after at least some functions are loaded from 'Foundation', but it's the first attempt to address something from `_sec` (aka `ctypes.CDLL(find_library('Security'))`). I suspect that library is either defective or masked by some other library.

Next thing I would inspect is to see if the [`security` command](https://ss64.com/osx/security.html) works and if the Keychain app works. I'm hopeful one of those is also broken, which will give some indication as to what is wrong with the user's machine, independent of keyring. If both of those are working, then we'll need to do some more experimentation with the user's environment.

**Comment by hsperr** [comment]
So it took a while since he is travelling a lot but to me it seems that both the security command and the keychain app look unsuspicious.

```
> security list-keychains
    "/Users/<username>/Library/Keychains/login.keychain-db"
    "/Library/Keychains/System.keychain"
```
I have the same output on my system. And opening the keychain app doesn't seem a problem and passwords seem to be stored like normal. I am not quite sure what exactly to test.


Running keyring I can find the difference that his system doesn't list the OSX keyring.
Are there any libraries that get installed with the dev tools or something that we could try reinstalling?

```
keyring --list-backends
```

his system:
```
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.chainer.ChainerBackend (priority: -1)
```

my system:
```
keyring.backends.macOS.Keyring (priority: 5)
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.chainer.ChainerBackend (priority: -1)
```

**Comment by jaraco** [comment]
So it seems the issue is isolated to this Python environment (not an issue in the system as `security` and `Keychain App` are working).

I'm now wondering if there's something odd about how the `miniconda3` environment is created. Can you confirm that your friend is also using an M1 mac? Can they try installing Python 3.9.x from the [Python.org installer](https://www.python.org/downloads/release/python-3913/) and use it to install keyring and see if the issue occurs there also?

**Comment by KengoSawa2** [comment]
Hello
Thanks for the great library:)

I have encountered this problem.
The problem seems to occur with Python installed in the signed Framework format distributed by Python official distribution.
https://www.python.org/downloads/

My environment:

Python 3.12.10 (v3.12.10:0cc81280367, Apr 8 2025, 08:46:59) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
macOS:15.4.1
CPU:M4

I wanted to avoid having to redo the environment build with pyenv,

'Keyring.backends.macOS.Keyring' in the ‘PYTHON_KEYRING_BACKEND’ environment variable.
The library worked fine:)

Please refer to this if you are having trouble.

**Comment by jaraco** [comment]
> Python 3.12.10 (v3.12.10:0cc81280367, Apr 8 2025, 08:46:59) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
> macOS:15.4.1
> CPU:M4

That's weird and surprising. I'd expect the macOS keyring to get picked up automatically in your environment (without any environment variable). Maybe inspect your environment following this comment: https://github.com/jaraco/keyring/issues/568#issuecomment-1311782837 . I'm also surprised that setting the backend explicitly works around the issue, as I'd expect the backend to be broken if it can't initialize properly.
