### ISSUE TITLE
dbus-python not recognised

### ISSUE THREAD

**Issue by mrx23dot** [jaraco/keyring#651]
on headless debian with python3.9.2

```
sudo apt-get install libdbus-1-dev libdbus-glib-1-dev
sudo pip3 install autokey dbus-python keyring autokey

...
Successfully built dbus-python
Installing collected packages: dbus-python
Successfully installed dbus-python-1.3.2
```

but fails to run
```
 keyring set xxx username
Password for 'username' in 'test':
Traceback (most recent call last):
  File "/usr/local/bin/keyring", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/keyring/cli.py", line 148, in main
    return cli.run(argv)
  File "/usr/local/lib/python3.9/dist-packages/keyring/cli.py", line 76, in run
    return method()
  File "/usr/local/lib/python3.9/dist-packages/keyring/cli.py", line 93, in do_set
    set_password(self.service, self.username, password)
  File "/usr/local/lib/python3.9/dist-packages/keyring/core.py", line 61, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/usr/local/lib/python3.9/dist-packages/keyring/backends/fail.py", line 28, in get_password
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.

```
some complete tutorial would be nice what's required.

**Comment by mrx23dot** [comment]
Any help? I have installed everything I could, still fails.

**Comment by mitya57** [comment]
Did you read the README section about headless environments?
https://github.com/jaraco/keyring#using-keyring-on-headless-linux-systems

**Comment by mrx23dot** [comment]
Thank you
