### ISSUE TITLE
Anonymous credential has no username

### ISSUE THREAD

**Issue by Freed-Wu** [jaraco/keyring#701]
**Describe the bug**
```
Traceback (most recent call last):
  File "/nix/store/ycp9b1sllqhkj4rlcmrhppw8919hf9h5-python3.12-keyring-25.4.0/bin/.keyring-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/ycp9b1sllqhkj4rlcmrhppw8919hf9h5-python3.12-keyring-25.4.0/lib/python3.12/site-packages/keyring/cli.py", line 219, in main
    return cli.run(argv)
           ^^^^^^^^^^^^^
  File "/nix/store/ycp9b1sllqhkj4rlcmrhppw8919hf9h5-python3.12-keyring-25.4.0/lib/python3.12/site-packages/keyring/cli.py", line 120, in run
    return method()
           ^^^^^^^^
  File "/nix/store/ycp9b1sllqhkj4rlcmrhppw8919hf9h5-python3.12-keyring-25.4.0/lib/python3.12/site-packages/keyring/cli.py", line 132, in do_get
    getattr(self, f'_emit_{self.output_format}')(credential)
  File "/nix/store/ycp9b1sllqhkj4rlcmrhppw8919hf9h5-python3.12-keyring-25.4.0/lib/python3.12/site-packages/keyring/cli.py", line 140, in _emit_plain
    if credential.username:
       ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ycp9b1sllqhkj4rlcmrhppw8919hf9h5-python3.12-keyring-25.4.0/lib/python3.12/site-packages/keyring/credentials.py", line 39, in username
    raise ValueError("Anonymous credential has no username")
ValueError: Anonymous credential has no username
```

**To Reproduce**
1. Install this package

**Expected behavior**
Build will fail. https://github.com/NixOS/nixpkgs/issues/352426

**Environment**

- OS: NixOS

**Additional context**
What does `Anonymous credential has no username` mean?

**Comment by nazarewk** [comment]
cross-posting: https://github.com/NixOS/nixpkgs/issues/352426#issuecomment-2449281386
seems to be a bug introduced in `25.4.0` and fixed in `25.4.1`
