### ISSUE TITLE
Python 3 incompatibility in Google backend

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#84]
Python 2 _raw_input_ keyword used in the Google backend:

```
#!python

Traceback (most recent call last):
  File "/Users/brett/env/djset3/lib/python3.3/site-packages/nose2/plugins/loader/discovery.py", line 188, in _find_tests_in_file
    module = util.module_from_name(name)
  File "/Users/brett/env/djset3/lib/python3.3/site-packages/nose2/util.py", line 79, in module_from_name
    __import__(name)
  File "/Users/brett/dev/djset/tests/tests.py", line 8, in <module>
    import keyring
  File "/Users/brett/env/djset3/lib/python3.3/site-packages/keyring/__init__.py", line 9, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/Users/brett/env/djset3/lib/python3.3/site-packages/keyring/core.py", line 13, in <module>
    from keyring import backend
  File "/Users/brett/env/djset3/lib/python3.3/site-packages/keyring/backend.py", line 155, in <module>
    from keyring.backends.Google import DocsKeyring as GoogleDocsKeyring
  File "/Users/brett/env/djset3/lib/python3.3/site-packages/keyring/backends/Google.py", line 24, in <module>
    class DocsKeyring(KeyringBackend):
  File "/Users/brett/env/djset3/lib/python3.3/site-packages/keyring/backends/Google.py", line 39, in DocsKeyring
    can_create=True, input_getter=raw_input
NameError: name 'raw_input' is not defined
```

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/84
- Originally reported by: Brett Haydon
- Originally created at: 2013-02-03T10:30:43.558

**Comment by jaraco** [comment]
I've pushed a fix for this to branch issue_84. Unfortunately, I don't have python 3.3 installed on this laptop to test with. Can you test this branch and let me know the result? Thanks.

---

Original comment by: Robert Leftwich

**Comment by jaraco** [comment]
Yes, thats the first bit but you left off the 2nd bit.

https://bitbucket.org/hedgeddown/python-keyring-lib/commits/66ec591a2610905ffe2abec942670b464929f67a

Also a bonus my project test suite caught another bug in the OSX backend for py3. The re.search raises a TypeError which is consumed by the catchall 'exception', so get_password always returns None.

Here's the fix for that.

https://bitbucket.org/hedgeddown/python-keyring-lib/commits/7fb305d7eec2e81394f15fb90931ed9472c5deb7

A more verbose way would be to get the default encoding from locale but I'm not sure that's any better than assuming utf-8 output from the osx process.

---

Original comment by: Brett Haydon

**Comment by jaraco** [comment]
It's actually a Python 3.0 incompatibility issue since `raw_input` as been renamed in Python 3.0: http://docs.python.org/3.0/whatsnew/3.0.html#builtins

---

Original comment by: Jonathan Ballet

**Comment by jaraco** [comment]
Select 'input' function based on Python version. Fixes #84

→ <<cset fa82ba9095d8>>

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
@rl_0x0 - I decided to take a stab at this while I was offline, so didn't have the history of the issue. I wasn't trying to re-do your work. I noticed on pulling your patch that it didn't actually change the broken usage, so I've decided to exclude it. I hope there are no hard feelings.

@hedgeddown I'll pull in your other fix. Thanks for that.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
@jaraco - not at all, glad its fixed.

@hedgeddown - apologies for the half fix - no more late night fixes w/o a test env! I had switched machines and only copied the first part of the fix, sigh. For some reason bitbucket saw fit to not send me any of the followup emails on this thread, so I missed your comment.

---

Original comment by: Robert Leftwich
