### ISSUE TITLE
ImportError: No module named configparser

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#89]
I use keyring-1.2, mercurial-2.4.2 (at 2.5 get same), when do `hg out` or another — get:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 87, in _runcatch
    try:
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 741, in _dispatch
    cmdpats, cmdoptions)
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 514, in runcommand
    ret = _runcommand(ui, options, cmd, d)
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 831, in _runcommand
    return checkargs()
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 802, in checkargs
    return cmdfunc()
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 738, in <lambda>
    d = lambda: util.checksignature(func)(ui, *args, **cmdoptions)
  File "/usr/lib/python2.7/site-packages/mercurial/util.py", line 472, in check
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mercurial/extensions.py", line 144, in wrap
    util.checksignature(origfn), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mercurial/util.py", line 472, in check
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/hgext/mq.py", line 3546, in mqcommand
    return orig(ui, repo, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mercurial/util.py", line 472, in check
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mercurial/commands.py", line 4407, in outgoing
    return hg.outgoing(ui, repo, dest, opts)
  File "/usr/lib/python2.7/site-packages/mercurial/hg.py", line 587, in outgoing
    o = _outgoing(ui, repo, dest, opts)
  File "/usr/lib/python2.7/site-packages/mercurial/hg.py", line 567, in _outgoing
    other = peer(repo, opts, dest)
  File "/usr/lib/python2.7/site-packages/mercurial/hg.py", line 121, in peer
    return _peerorrepo(rui, path, create).peer()
  File "/usr/lib/python2.7/site-packages/mercurial/hg.py", line 101, in _peerorrepo
    obj = _peerlookup(path).instance(ui, path, create)
  File "/usr/lib/python2.7/site-packages/mercurial/httppeer.py", line 237, in instance
    inst._fetchcaps()
  File "/usr/lib/python2.7/site-packages/mercurial/httppeer.py", line 57, in _fetchcaps
    self.caps = set(self._call('capabilities').split())
  File "/usr/lib/python2.7/site-packages/mercurial/httppeer.py", line 170, in _call
    fp = self._callstream(cmd, **args)
  File "/usr/lib/python2.7/site-packages/mercurial/httppeer.py", line 118, in _callstream
    resp = self.urlopener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 438, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 890, in http_error_401
    url, req, headers)
  File "/usr/lib/python2.7/site-packages/mercurial/url.py", line 431, in http_error_auth_reqed
    self, auth_header, host, req, headers)
  File "/usr/lib/python2.7/site-packages/mercurial_keyring.py", line 339, in basic_http_error_auth_reqed
    return basic_http_error_auth_reqed.orig(self, authreq, host, req, headers)
  File "/usr/lib/python2.7/urllib2.py", line 865, in http_error_auth_reqed
    response = self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib/python2.7/urllib2.py", line 871, in retry_http_basic_auth
    user, pw = self.passwd.find_user_password(realm, host)
  File "/usr/lib/python2.7/site-packages/mercurial_keyring.py", line 333, in find_user_password
    return self._pwd_handler.find_auth(self, realm, authuri, req)
  File "/usr/lib/python2.7/site-packages/mercurial_keyring.py", line 184, in find_auth
    pwd = password_store.get_http_password(keyring_url, user)
  File "/usr/lib/python2.7/site-packages/mercurial_keyring.py", line 67, in get_http_password
    self._format_http_key(url, username))
  File "/usr/lib/python2.7/site-packages/keyring/core.py", line 36, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python2.7/site-packages/keyring/backends/file.py", line 61, in get_password
    config = configparser.RawConfigParser()
  File "/usr/lib/python2.7/site-packages/mercurial/demandimport.py", line 86, in __getattribute__
    self._load()
  File "/usr/lib/python2.7/site-packages/mercurial/demandimport.py", line 58, in _load
    mod = _origimport(head, globals, locals)
ImportError: No module named configparser
```

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/89
- Originally reported by: Vladislav Polukhin
- Originally created at: 2013-02-12T05:01:02.193

**Comment by jaraco** [comment]
I've seen this same issue in distribute (I think). The underlying issue is that the mercurial demandimport causes the selective import to not detect the correct Python-specific module name. I'll try to track down how this was addressed in other libraries.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Here is [the upstream issue](/Mekk/mercurial_keyring/issue/22) (with a workaround).

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
keyring's behavior here is normal and expected. I believe the issue needs to be fixed upstream. If there is something that keyring can do to alleviate the issue, please feel free to re-open or post another comment.

---

Original comment by: Jason R. Coombs
