### ISSUE TITLE
No module named hgtools.plugins when installing keyring 1.2.2 via pip on python 2.6

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#90]
When trying to install keyring via pip on RHEL 6.3 x86_64 with python 2.6 I get this failure:

Downloading/unpacking keyring (from -r ./tools/pip-requires (line 14))
  Downloading keyring-1.2.2.zip (79Kb): 79Kb downloaded
  Running setup.py egg_info for package keyring
    zip_safe flag not set; analyzing archive contents...

```
Installed /tmp/easy_install-cTbiWo/pytest-runner-1.2/hgtools-2.0.2-py2.6.egg

Installed /tmp/tempest/tempest/build/keyring/pytest_runner-1.2-py2.6.egg
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/tmp/tempest/tempest/build/keyring/setup.py", line 114, in <module>
    setup_mod.setup(**setup_params)
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "<string>", line 12, in replacement_run
  File "/usr/lib/python2.6/site-packages/setuptools/command/egg_info.py", line 254, in find_sources
    mm.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/egg_info.py", line 308, in run
    self.add_defaults()
  File "/usr/lib/python2.6/site-packages/setuptools/command/egg_info.py", line 335, in add_defaults
    rcfiles = list(walk_revctrl())
  File "/usr/lib/python2.6/site-packages/setuptools/command/sdist.py", line 46, in walk_revctrl
    for item in ep.load()(dirname):
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named hgtools.plugins
Complete output from command python setup.py egg_info:
zip_safe flag not set; analyzing archive contents...
```

The keyring doesn't list a requirement on hgtools in the egg, should it?

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/90
- Originally reported by: Anonymous
- Originally created at: 2013-02-12T16:47:58.345

**Comment by jaraco** [comment]
I believe this error is a result of a bug in distribute/setuptools prior to Distribute 0.6.24 (or maybe 0.6.26). I forget specifically what the issue is, but I'm pretty sure the fix is to upgrade Distribute to a late, stable version.

The underlying cause is not that keyring requires hgtools (it doesn't), but that it does require pytest-runner during setup, which in turn requires hgtools during setup, and that chain of setup_requires triggers errors in older versions of setuptools/distribute.

Unfortunately, the only thing keyring can do to fix the issue is to not have the setup requires dependency (which also means it can't have setuptools resolve its test dependencies when setup.py is invoked).

I apologize for the long time in addressing the bug report. Please let me know if you find that updating Distribute doesn't resolve the issue.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
The issue is with Distribute and is fixed upstream.

---

Original comment by: Jason R. Coombs
