### ISSUE TITLE
probs in opensuse 12.1

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#91]
Hi, I've been using Mercurial+python's kerying+python's mercurial-keyring together in the past on my opensuse 11.4 pc to "hg push" my local repositories to the server without having to type in my password repeatedly. It worked fine there.

However, I've experienced a problem when now running in opensuse 12.1. Initially I reported this on the issue-tracker for mercurial-keyring, at:

https://bitbucket.org/Mekk/mercurial_keyring/issue/23/probs-in-opensuse-121

But the author said the trace indicates that the issue is at the keyring level and that I should report it here.

Ok then, here's the trace:

```
searching for changes
http authorization required
realm: Mecurial Repo
user: gurcei (fixed in .hg/hgrc)
password: 
ERROR:dbus.proxies:Introspect error on :1.222:/org/freedesktop/secrets/aliases/default: dbus.exceptions.DBusException: org.freedesktop.Secret.Error.NoSuchObject: The '/org/freedesktop/secrets/aliases/default' object does not exist
ERROR:dbus.connection:Unable to set arguments ({'org.freedesktop.Secret.Item.Label': u'gurcei@@http://rapiddev/hg @ Mercurial', 'org.freedesktop.Secret.Item.Attributes': {'username': u'gurcei@@http://rapiddev/hg', 'service': u'Mercurial'}}, dbus.Struct((dbus.ObjectPath('/org/freedesktop/secrets/session/s11'), '', dbus.ByteArray('xxxxx'), 'application/octet-stream'), signature=None), True) according to signature None: <type 'exceptions.TypeError'>: Expected a string or unicode object
** Unknown exception encountered with possibly-broken third-party extension mercurial_keyring
** which supports versions unknown of Mercurial.
** Please disable mercurial_keyring and try your action again.
** If that fixes the bug please report it to the extension author.
** Python 2.7.2 (default, Aug 19 2011, 20:41:43) [GCC]
** Mercurial Distributed SCM (version 2.4.1)
** Extensions loaded: hgk, mercurial_keyring
Traceback (most recent call last):
  File "/usr/bin/hg", line 38, in <module>
    mercurial.dispatch.run()
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 28, in run
    sys.exit((dispatch(request(sys.argv[1:])) or 0) & 255)
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 65, in dispatch
    return _runcatch(req)
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 88, in _runcatch
    return _dispatch(req)
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 741, in _dispatch
    cmdpats, cmdoptions)
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 514, in runcommand
    ret = _runcommand(ui, options, cmd, d)
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 831, in _runcommand
    return checkargs()
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 802, in checkargs
    return cmdfunc()
  File "/usr/lib/python2.7/site-packages/mercurial/dispatch.py", line 738, in <lambda>
    d = lambda: util.checksignature(func)(ui, *args, **cmdoptions)
  File "/usr/lib/python2.7/site-packages/mercurial/util.py", line 472, in check
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mercurial/commands.py", line 4751, in push
    newbranch=opts.get('new_branch'))
  File "/usr/lib/python2.7/site-packages/mercurial/localrepo.py", line 1910, in push
    ret = remote.unbundle(cg, remoteheads, 'push')
  File "/usr/lib/python2.7/site-packages/mercurial/wireproto.py", line 307, in unbundle
    ret, output = self._callpush("unbundle", cg, heads=heads)
  File "/usr/lib/python2.7/site-packages/mercurial/httppeer.py", line 200, in _callpush
    r = self._call(cmd, data=fp, headers=headers, **args)
  File "/usr/lib/python2.7/site-packages/mercurial/httppeer.py", line 170, in _call
    fp = self._callstream(cmd, **args)
  File "/usr/lib/python2.7/site-packages/mercurial/httppeer.py", line 118, in _callstream
    resp = self.urlopener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 513, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 432, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 884, in http_error_401
    url, req, headers)
  File "/usr/lib/python2.7/site-packages/mercurial/url.py", line 431, in http_error_auth_reqed
    self, auth_header, host, req, headers)
  File "/usr/local/lib/python2.7/site-packages/mercurial_keyring-0.5.4-py2.7.egg/mercurial_keyring.py", line 363, in basic_http_error_auth_reqed
    return basic_http_error_auth_reqed.orig(self, authreq, host, req, headers)
  File "/usr/lib/python2.7/urllib2.py", line 859, in http_error_auth_reqed
    response = self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib/python2.7/urllib2.py", line 865, in retry_http_basic_auth
    user, pw = self.passwd.find_user_password(realm, host)
  File "/usr/local/lib/python2.7/site-packages/mercurial_keyring-0.5.4-py2.7.egg/mercurial_keyring.py", line 357, in find_user_password
    return self._pwd_handler.find_auth(self, realm, authuri, req)
  File "/usr/local/lib/python2.7/site-packages/mercurial_keyring-0.5.4-py2.7.egg/mercurial_keyring.py", line 242, in find_auth
    password_store.set_http_password(keyring_url, user, pwd)
  File "/usr/local/lib/python2.7/site-packages/mercurial_keyring-0.5.4-py2.7.egg/mercurial_keyring.py", line 95, in set_http_password
    password)
  File "/usr/local/lib/python2.7/site-packages/keyring-1.2.2-py2.7.egg/keyring/core.py", line 42, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/local/lib/python2.7/site-packages/keyring-1.2.2-py2.7.egg/keyring/backends/SecretService.py", line 107, in set_password
    item, prompt = self.collection.CreateItem(properties, secret, True)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 68, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 140, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 620, in call_blocking
    message.append(signature=signature, *args)
TypeError: Expected a string or unicode object
```

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/91
- Originally reported by: Gurce Isikyildiz
- Originally created at: 2013-02-17T22:00:07.233

**Comment by jaraco** [comment]
What version of dbus is OpenSuse 12.1 running?

python -c "import dbus;print dbus.__version__"

Do all the keyring tests run on that platform, esp. test_SecretService.py?
In the python-keying-lib directory, run:

python setup.py ptr 

Everything looks ok on Ubuntu 12.04 which uses v1.0.0 of dbus python.

fwiw I've just pushed a branch with a workaround for test failures in the SecretService implementation, see secret_service_workaround. You may want to try using that branch, although it doesn't directly impact the normal functionality, unless you are using empty passwords. 

---

Original comment by: Robert Leftwich

**Comment by jaraco** [comment]
output of tests with v1.2.2

---

Original comment by: Gurce Isikyildiz

**Comment by jaraco** [comment]
output of tests from the secret_service_workaround branch

---

Original comment by: Gurce Isikyildiz

**Comment by jaraco** [comment]
Hi Robert,

I'll try answer your queries to the best of my abilities (don't know a great deal about dbus or python though):

### Version of DBus on OpenSuse 12.1

I typed "**rpm -qa | grep dbus**" and got:

```
dbus-1-x11-1.5.8-2.1.3.i586
dbus-1-glib-0.98-2.1.2.i586
dbus-1-devel-1.5.8-2.1.2.i586
dbus-1-python-0.83.2-7.1.3.i586
libdbusmenu-qt2-0.9.0-2.1.2.i586
dbus-1-1.5.8-2.1.2.i586
dbus-1-glib-devel-0.98-2.1.2.i586
```

I see above that the dbus-1 package is v1.5.8-2.1.2.

If I type: **python -c "import dbus;print dbus.**version**"**

the output is: **0.83.2**

### Keyring tests
- I cloned the hg repo, checked out **1.2.2** and ran "**python setup.py ptr**"
- I captured the output to "**out_1.2.2.txt**" (attached above)
- I checked out the "**secret_service_workaround**" branch and ran "**python setup.py ptr**" again
- I captured the output to "**out_secret_service_workaround.txt**" (attached above)

Both seemed to have problems, don't know how to decipher these, so I'm hoping they're more meaningful for you.

### Other

I noticed you mentioned: Everything looks ok on Ubuntu 12.04 which uses v1.0.0 of dbus python.

So my version is fairly old in comparison, I tried grabbing the source for the latest version from http://dbus.freedesktop.org/releases/dbus-python/ (1.1.1), and tried a ./configure, make and sudo make install.

I think this made things worse for me, now when I type: **python -c "import dbus;print dbus.**version**"**

I see:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "dbus/__init__.py", line 82, in <module>
    import dbus.types as types
  File "dbus/types.py", line 6, in <module>
    from _dbus_bindings import (
ImportError: cannot import name UnixFd
```

Also when you mentioned, "...unless you are using empty passwords.", that reminded me, a colleague suggested to me to make my kwallet password blank, to spare me from typing in yet another password (which I did). Is this related to what I'm experiencing?

---

Original comment by: Gurce Isikyildiz

**Comment by jaraco** [comment]
Hmm, the "ImportError: cannot import name UnixFd" mentioned above only seems to occur if I run that "**python -c**" command within the path where I cloned 'python-keyring-lib'.

If I change to a different directory, the command works: **python -c "import dbus;print dbus.**version**"**

But it still reports as being version: **0.83.2**

However I noticed that if I go to: "**cd /usr/local/lib/python2.7/site-packages**" and run it within there, it finally reports **1.1.1**

I'm guessing its due to the newer _dbus_*.so files residing in here?

---

Original comment by: Gurce Isikyildiz

**Comment by jaraco** [comment]
Ok, I've managed to get the dbus-python 1.1.1 installed properly. It required me to un-install the older 0.83.2 first.

After doing so, the **python -c "import dbus;print dbus.**version**"** command is always reporting **1.1.1**

I then tried running the test scripts again. This tme, regardless of whether I hg checkout the **1.2.2** tag or the **secret_service_workaround** branch, the test scripts seem to end prematurely on "**test_SecretService.py**" as follows:

```
============================= test session starts ==============================
platform linux2 -- Python 2.7.2 -- pytest-2.3.4
collected 175 items 

keyring/tests/test_cli.py .......
keyring/tests/test_core.py .......
keyring/tests/test_util.py ...
keyring/tests/backends/test_Gnome.py ssssssssssss
keyring/tests/backends/test_Google.py ........................
keyring/tests/backends/test_OS_X.py sssssss
keyring/tests/backends/test_SecretService.py xxAborted
```

---

Original comment by: Gurce Isikyildiz

**Comment by jaraco** [comment]
Another experience I thought I'd better share. I've tried installing mercurial-keyring on a a different OpenSuse 12.1 pc (a virtualbox), and it ran successfully there!

So I guess this is boiling down to what is different between my two opensuse 12.1 pc's that makes it run fine on one and not the other...

---

Original comment by: Gurce Isikyildiz

**Comment by jaraco** [comment]
(Edited: previously I accidentally looked at the settings on my opensuse11.4 pc instead of my os12.1 vbox)

Ok, here are a few more details on my opensuse 12.1 vbox, where the keyring works:

"**rpm -qa | grep dbus**" outputs:

```
yast2-dbus-client-2.21.0-3.1.3.i586
dbus-1-x11-1.5.8-2.1.3.i586
dbus-1-glib-0.98-2.1.2.i586
dbus-1-devel-1.5.8-2.1.2.i586
dbus-1-python-0.83.2-7.1.3.i586
system-config-printer-dbus-service-1.3.7-2.2.2.noarch
libdbusmenu-qt2-0.9.0-2.1.2.i586
dbus-1-1.5.8-2.1.2.i586
dbus-1-glib-devel-0.98-2.1.2.i586
```

"**python -c "import dbus; print dbus.**version**"**" outputs:

**0.83.2**

These values seem to be identical to the other opensuse 12.1 where the keyring isn't working. So if the difference isn't in the rpms, I guess there's something else different between them that's causing this...

---

Original comment by: Gurce Isikyildiz

**Comment by jaraco** [comment]
Aha! I've looked for further differences between my two OS12.1 pc's, and I've found the culprit:
- My working OS12.1PC uses "**mercurial-2.4**"
- My failing OS12.1PC uses "**mercurial-2.4.1**"

I tried reverting my failing OS12.1PC back to mercurial v2.4, and hey presto! The push worked via the keyring!

As another test, I noticed the opensuse repository "devel:tools:scm" currently offers v2.5.1. I tried updating to this newer version, but this returns me to a similar exception I experienced with v2.4.1:

```
ERROR:dbus.proxies:Introspect error on :1.106:/org/freedesktop/secrets/aliases/default: dbus.exceptions.DBusException: org.freedesktop.Secret.Error.NoSuchObject: The '/org/freedesktop/secrets/aliases/default' object does not exist
ERROR:dbus.connection:Unable to set arguments ({'org.freedesktop.Secret.Item.Label': u'gurcei@@http://rapiddev.australia.shufflemaster.com/hg @ Mercurial', 'org.freedesktop.Secret.Item.Attributes': {'username': u'gurcei@@http://rapiddev.australia.shufflemaster.com/hg', 'service': u'Mercurial'}}, dbus.Struct((dbus.ObjectPath('/org/freedesktop/secrets/session/s4'), '', dbus.ByteArray('xxxxxxx'), 'application/octet-stream'), signature=None), True) according to signature None: <type 'exceptions.TypeError'>: Expected a string or unicode object
```

So for now, I'll just get by sticking with v2.4, but from what I've witnessed, this issue still remains in newer versions, including the latest v2.5.1.

So is this problem now a mercurial problem? Should I report it on their bug-tracking system?

---

Original comment by: Gurce Isikyildiz

**Comment by jaraco** [comment]
PS. Just in-case, I raised this on the mercurial bug-tracker too:

http://bz.selenic.com/show_bug.cgi?id=3842

Although they also said it's not their turf. Oh well, I hope that at least we've got a clue that whatever caused this issue is related to the changes between hg v2.4 and v2.4.1.

---

Original comment by: Gurce Isikyildiz

**Comment by jaraco** [comment]
After noticing how downgrading mercurial helped my situation, I tried another approach.
- I installed the latest mercurial v2.5.1
- I **incrementally downgraded** the python-keyring:
- on each increment, I attempt to push a commit
- v1.2.2 - asks for password and fails
- v1.2.1 - asks for password and fails
- v1.2 - asks for password and fails
- v1.1.2 - asks for password and fails
- v1.1.1 - asks for password and fails
- v1.1 - (doesn't seem to install properly: error: CHANGES.rst: No such file or directory)
- **v1.0 - doesn't ask for password, and works**

---

Interestingly, if I **incrementally upgrade** from v1.0, I see the following:
- v1.1 - doesn't install
- v1.1.1 - doesn't ask for password, and works
- v1.1.2 - doesn't ask for password, and works
- **v1.2 - asks for password and fails**

So interestingly, when incrementally downgrading, it starts working at v1.0, but when incrementallly upgrading, it fails at v1.2.

Just wanted to share this observation, in-case it provides further clues.

---

Original comment by: Gurce Isikyildiz

**Comment by jaraco** [comment]
I couldn't get mercurial_keyring extension in openSUSE 12.3 either. I tried different versions (not theat much variant were available in repositories, though), but neither actually worked. I alwyas get "Expected a string or unicode object" error.

The latest versions, which I tried were:
python-keyring 1.2.2
mercurial 2.5.4

---

Original comment by: [rntln](http://bitbucket.org/rntln)

**Comment by jaraco** [comment]
Hi rntln,

Here's how I went about the incremental downgrading:
- sudo -E easy_install keyring==1.2.1
- try to push (jot down your results)
- sudo -E easy_install keyring==1.2
- try to push (jot down your results)
- sudo -E easy_install keyring==1.1.2
- try to push (jot down your results)
- etc...

Also, if you previously obtained 'python-keyring' via your repos (and not via easy_install), then remove the repo-version, to assure the version you install via easy_install is used.

---

Original comment by: Gurce Isikyildiz

**Comment by jaraco** [comment]
Is this issue still present in 1.5? There is a big chance it isn't, because the SecretService keyring was rewritten using [secretstorage](http://pythonhosted.org/SecretStorage) in 1.3.

---

Original comment by: Dmitry Shachnev

**Comment by jaraco** [comment]
Cheers Dmitry, I tried incrementally upgrading from v1.2.2 to v1.3, the problem went away. I then upgraded to v1.5, problem went away, all fine from this end.

Thanks!

---

Original comment by: Gurce Isikyildiz

**Comment by jaraco** [comment]
@Gurce Thanks for your feedback, please close the bug then.

---

Original comment by: Dmitry Shachnev

**Comment by jaraco** [comment]
Ok, will do. I never realised I had this much power, it might go to my head ;)

---

Original comment by: Gurce Isikyildiz

**Comment by jaraco** [comment]
working fine in OpenSUSE 12.1 now after updating to V1.3 or higher

---

Original comment by: Gurce Isikyildiz
